#!/usr/bin/env node
// Closed consumer validation and owned combined obligations on actual Wasm results.
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';
import {createVirglShaderBridge} from '../../renderer/virgl-shader/index.mjs';
import {parseConstantDomain,checkRadialBank,checkLoopBank,checkFiniteBank} from '../../renderer/virgl-command/constant-domain.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),output=path.resolve(process.argv[2]);fs.mkdirSync(output,{recursive:true});
const hash=raw=>createHash('sha256').update(raw).digest('hex'),bind=p=>{const raw=fs.readFileSync(path.join(root,p));return{path:p,bytes:raw.length,sha256:hash(raw)}};
const paths=['renderer/virgl-command/constant-domain.mjs','tools/virgl-precise-word/domain.mjs','renderer/virgl-shader/tests/precise-word-cases.json','renderer/virgl-shader/build/wasm/virgl-shader.wasm'],fixture=JSON.parse(fs.readFileSync(path.join(root,paths[2])));
const bridge=await createVirglShaderBridge({wasmBinary:fs.readFileSync(path.join(root,paths[3]))});
const report={schema:'precise-consumer-domain-v1',status:'running',sources:paths.map(bind),results:[],forgeries:[],ownership:[],combined:[]};
for(const entry of fixture.cases.filter(e=>e.name.startsWith('profile-'))){
 const result=bridge.translate({stage:entry.stage,text:entry.text});assert.equal(result.ok,true,entry.name);const parsed=parseConstantDomain(result.metadata,entry.stage);assert.equal(parsed.ok,true,entry.name);assert.deepEqual(parsed.precision,entry.expected.preciseWordContract);report.results.push({name:entry.name,result:structuredClone(result),parsed});
 const base=result.metadata,checks=[['missing precision',m=>{delete m.preciseWordContract}],['extra precision field',m=>{m.preciseWordContract.extra=0}],['wrong kind',m=>{m.preciseWordContract.kind='other'}],['wrong stage',m=>{m.preciseWordContract.stage=entry.stage==='vertex'?'fragment':'vertex'}],['empty operations',m=>{m.preciseWordContract.operations=[]}],['unsupported arithmetic',m=>{m.preciseWordContract.operations=['ADD']}],['duplicates',m=>{m.preciseWordContract.operations=['MOV','MOV']}],['unsorted',m=>{m.preciseWordContract.operations=['MOV','FSEQ']}],['not string',m=>{m.preciseWordContract.operations=[false]}],['extra operation',m=>{m.preciseWordContract.operations=['FSEQ','FSNE','MAX','MOV','MOV']}],['legacy family',m=>{m.profile='virgl-webgl2-raw-bits-v1'}]];
 for(const key of ['constantDomains','constantAccesses','constantConstraints','constantRadialDomains'])if(Object.hasOwn(base,key))checks.push(['drop '+key,m=>{delete m[key]}]);
 for(const[name,mutate]of checks){const metadata=structuredClone(base);mutate(metadata);const actual=parseConstantDomain(metadata,entry.stage);assert.equal(actual.ok,false,entry.name+'/'+name);assert.equal(actual.error.code,'shader-domain-error');report.forgeries.push({case:entry.name,name,metadata,result:actual});}
 for(const field of ['kind','stage','operations']){const metadata=structuredClone(base);Object.defineProperty(metadata.preciseWordContract,field,{enumerable:true,get(){throw new Error('uninvoked precision accessor')}});const actual=parseConstantDomain(metadata,entry.stage);assert.equal(actual.ok,false);report.forgeries.push({case:entry.name,name:'accessor '+field,result:actual});}
 {const metadata=structuredClone(base);metadata.preciseWordContract.operations.length=2;const actual=parseConstantDomain(metadata,entry.stage);assert.equal(actual.ok,false,'sparse operations');report.forgeries.push({case:entry.name,name:'sparse operations',result:actual});}
 const owned=parsed.precision,before=JSON.stringify(owned);base.preciseWordContract.operations[0]='ADD';base.preciseWordContract.stage='invalid';assert.equal(JSON.stringify(owned),before);assert.equal(Object.isFrozen(owned),true);assert.equal(Object.isFrozen(owned.operations),true);report.ownership.push({case:entry.name,caller:base.preciseWordContract,owned});
 if(parsed.radialDomain){const words=Array(parsed.radialDomain.count*4).fill(0);words[16]=0x3f800000;if(parsed.constraint){words[36]=2;words[44]=0x3f800000;}const accepted=checkRadialBank(words,parsed.radialDomain.count,!!parsed.constraint);assert.equal(accepted.ok,true);words[16]=0;const rejected=checkRadialBank(words,parsed.radialDomain.count,!!parsed.constraint);assert.equal(rejected.ok,false);report.combined.push({case:entry.name,kind:'radial',accepted,rejected});}
 if(parsed.constraint){const words=Array(parsed.constraint.count*4).fill(0);words[36]=19;const actual=checkLoopBank(words,parsed.constraint.count);assert.equal(actual.ok,false);report.combined.push({case:entry.name,kind:'count',bank:words,result:actual});}
 if(parsed.domain){const words=Array(parsed.domain.count*4).fill(0);words[0]=0x7f800000;const actual=checkFiniteBank(words,parsed.domain.count);assert.equal(actual.ok,false);report.combined.push({case:entry.name,kind:'finite',bank:words,result:actual});}
}
for(const item of report.sources)assert.deepEqual(bind(item.path),item);report.status='passed';fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:'passed',profiles:report.results.length,forgeries:report.forgeries.length,combined:report.combined.length}));
