/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmlinux_free: (a: number, b: number) => void;
export const __wbg_wasmmachine_free: (a: number, b: number) => void;
export const bench: (a: number) => [number, number, number];
export const overlayDbName: (a: number, b: number) => [number, number, number, number];
export const version: () => [number, number];
export const wasmlinux_bootProfile: (a: number) => [number, number, number, number];
export const wasmlinux_closeStorage: (a: number) => [number, number];
export const wasmlinux_fetchPending: (a: number) => any;
export const wasmlinux_fetchStats: (a: number) => [number, number, number];
export const wasmlinux_hasUnpersisted: (a: number) => [number, number, number];
export const wasmlinux_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: any) => [number, number, number];
export const wasmlinux_newChunkedDisk: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: any) => [number, number, number];
export const wasmlinux_newChunkedDiskPersistent: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: any) => any;
export const wasmlinux_newDisk: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: any) => [number, number, number];
export const wasmlinux_pendingChunks: (a: number) => [number, number, number, number];
export const wasmlinux_persistPending: (a: number) => any;
export const wasmlinux_persistStats: (a: number) => [number, number, number];
export const wasmlinux_runChunk: (a: number, b: number) => [number, number, number];
export const wasmlinux_sendInput: (a: number, b: number, c: number) => [number, number];
export const wasmlinux_setDiskReadOnly: (a: number) => [number, number, number];
export const wasmmachine_getStats: (a: number) => [number, number, number];
export const wasmmachine_loadElf: (a: number, b: number, c: number) => [number, number];
export const wasmmachine_new: (a: number) => [number, number, number];
export const wasmmachine_ramLen: (a: number) => [number, number, number];
export const wasmmachine_registers: (a: number) => [number, number, number];
export const wasmmachine_run: (a: number, b: number) => [number, number, number];
export const wasmmachine_setConsole: (a: number, b: any) => [number, number];
export const wasmmachine_setTrace: (a: number, b: number) => [number, number];
export const wasmmachine_stateDigest: (a: number) => [number, number, number, number];
export const wasmmachine_step: (a: number, b: number) => [number, number, number];
export const wasmmachine_takeTrace: (a: number) => [number, number, number, number];
export const initLogging: () => void;
export const wasm_bindgen__convert__closures_____invoke__h4dab88d0e3c13e7c: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h583f8b0f4fac6275: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h268857b0ab0b8859: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h268857b0ab0b8859_2: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
