import { createResourceStore, createWebGL2TransferBackend } from '/renderer/virgl-command/resources.mjs';
import { createVirglAsyncRenderer } from '/renderer/virgl-command/state.mjs';
import { createVirglShaderBridge } from '/renderer/virgl-shader/index.mjs';
import { decodeSubmission } from '/renderer/virgl-command/decoder.mjs';
import { createGlOracle } from '/gl-oracle.mjs';

const packet=(op,words=[])=>{const b=new Uint8Array(4+words.length*4),v=new DataView(b.buffer);v.setUint32(0,op|(words.length<<16),true);words.forEach((x,i)=>v.setUint32(4+i*4,x,true));return b;};
const join=(...parts)=>{const b=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let i=0;for(const p of parts){b.set(p,i);i+=p.length;}return b;};
const transfer=(id,direction,{x=0,y=0,width=4,height=4,offset=0,stride=16}={})=>packet(43,[id,0,0,stride,0,x,y,0,width,height,1,offset,direction]);
const colors=[[[255,0,0,255],[0,255,0,255],[0,0,255,255],[255,255,0,255]],[[255,0,0,255],[0,128,0,255],[0,0,0,255],[255,128,0,255]],[[64,0,191,255],[0,64,191,255],[0,0,255,255],[64,64,191,255]]];
const texture={id:11,target:2,format:67,bind:10,width:4,height:4,depth:1,arraySize:1,lastLevel:0,nrSamples:0,flags:0};
const sha=async b=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');
export async function runAttacks(fixtures){
 let assertions=0,pixels=0,heartbeats=0;const records=[],oracles=[];
 const eq=(a,b,label)=>{assertions++;if(JSON.stringify(a)!==JSON.stringify(b))throw Error(label+': '+JSON.stringify(a)+' != '+JSON.stringify(b));};
 const ok=(r,l)=>{eq(r?.ok,true,l+' '+JSON.stringify(r?.error));return r;};
 const bad=(r,l,code)=>{eq(r?.ok,false,l);if(code)eq(r.error.code,code,l+' code');records.push({name:l,error:r.error,applied:r.appliedCommands});return r;};
 const raw=e=>Uint8Array.from(fixtures.commands.submissions.find(s=>s.event===e).data);
 const canvas=document.querySelector('#gpu'), native=canvas.getContext('webgl2',{antialias:false}), bridge=await createVirglShaderBridge();
 const tick=async()=>{await new Promise(r=>setTimeout(r,0));heartbeats++;};
 function rig(options={}){
  const oracle=createGlOracle(native);oracles.push(oracle);oracle.setStrict(true);
  const faults={release:false,fence:false}; const rawBackend=ok(createWebGL2TransferBackend(oracle.gl),'actual backend').backend; const backend={...rawBackend,releaseReadback(entry){rawBackend.releaseReadback(entry);if(faults.release){faults.release=false;throw Error('trusted release fault after deletion');}}}; const hostGl=new Proxy(oracle.gl,{get(t,k){if(k==='fenceSync')return(...args)=>{if(faults.fence){faults.fence=false;throw Error('trusted fence allocator fault');}return t.fenceSync(...args);};return t[k];}});
  const owner=ok(createResourceStore({backend,...(options.resourceLimits?{limits:options.resourceLimits}:{})}),'resource owner');
  const config={gl:hostGl,resources:owner.store,bindings:owner.bindings,asyncAccess:owner.asyncAccess,shaderBridge:bridge,...(options.jobLimits?{jobLimits:options.jobLimits}:{}),...(options.drawLimits?{drawLimits:options.drawLimits}:{})};
  const renderer=ok(createVirglAsyncRenderer(config),'async renderer').renderer;
  const r={...owner,renderer,oracle,backend:rawBackend,faults,ram:new Map(),identities:new Map(),config};
  r.context=(id=2)=>{ok(r.store.createContext(id),'resource context');ok(renderer.createContext(id),'renderer context');};
  r.attach=(id,lengths)=>{ok(r.store.attachBacking(id,lengths.map(n=>new Uint8Array(n))),'zero private backing');r.ram.set(id,new Uint8Array(lengths.reduce((a,b)=>a+b,0)));r.identities.set(id,ok(r.asyncAccess.describeBacking(id),'capture backing identity'));};
  r.cleanup=()=>{ok(renderer.dispose(),'dispose renderer');ok(r.store.dispose(),'dispose resources');for(const owner of [renderer,r.store])for(const [key,value]of Object.entries(owner.inspect().budgets))eq(value,0,'released '+key);eq(r.asyncAccess.inspect(),{ok:true,disposed:true,reads:0,transfers:0,stagingBytes:0},'async accounting zero');eq(oracle.statistics().liveBuffers,0,'native buffers zero');eq(oracle.statistics().liveSyncs,0,'native syncs zero');eq(oracle.statistics().violations,[],'no sequencing violations');eq(native.getError(),0,'native GL clean');};
  return r;
 }
 function init(r){for(const a of fixtures.initialization){if(a.type==='context_create')r.context(a.contextId);else if(a.type==='resource_create')ok(r.store.createResource(a.metadata),'resource metadata');else if(a.type==='resource_attach_iov')r.attach(a.resourceId,a.iovLengths);else ok(r.store.attachContext(a.contextId,a.resourceId),'membership');}for(const b of fixtures.backing)for(const range of b.ranges)r.ram.get(b.resourceId).set(range.data,range.offset);}
 function life(r,a){if(a.type==='ctx_detach_resource')ok(r.store.detachContext(a.contextId,a.resourceId),'ordered detach');else if(a.type==='resource_detach_iov')ok(r.store.detachBacking(a.resourceId),'ordered backing detach');else if(a.type==='resource_unref')ok(r.store.unref(a.resourceId),'ordered unref');else{ok(r.renderer.destroyContext(a.contextId),'ordered renderer destroy');ok(r.store.destroyContext(a.contextId),'ordered resource destroy');}}
 function validate(r,q){const known=r.identities.get(q.resource.id);eq(q.resource,known.resource,'exchange resource identity');eq(q.backingGeneration,known.backingGeneration,'exchange backing identity');eq(q.layout.tightBytes,q.layout.rowBytes*q.layout.rowCount,'dense shape');}
 function gather(r,q){validate(r,q);const out=new Uint8Array(q.layout.tightBytes),ram=r.ram.get(q.resource.id),l=q.layout;for(let row=0;row<l.rowCount;row++)out.set(ram.subarray(l.offset+row*l.rowStride,l.offset+row*l.rowStride+l.rowBytes),row*l.rowBytes);return out;}
 function scatter(r,q){validate(r,q);eq(q.bytes.length,q.layout.tightBytes,'output byte count');const ram=r.ram.get(q.resource.id),l=q.layout;for(let row=0;row<l.rowCount;row++)ram.set(q.bytes.subarray(row*l.rowBytes,(row+1)*l.rowBytes),l.offset+row*l.rowStride);}
 async function drain(r,job,{hook,error,seed=0}={}){
  const states=[];for(let step=0;step<2048;step++){
   const s=ok(r.renderer.step(job),'step');states.push({status:s.status,applied:s.appliedCommands});
   if(r.oracle.statistics().violations.length)throw Error('Independent GL oracle: '+JSON.stringify(r.oracle.statistics().violations));
   if(s.status==='done'){if(error)bad(s.result,'terminal '+error,error);else ok(s.result,'job success');eq(s.result.gpuComplete,true,'terminal fence signaled');return{result:s.result,states};}
   if(hook&&await hook(s,step)){await tick();continue;}
   if(s.status==='needs-input'){const input=gather(r,s.request);ok(r.renderer.provideInput(job,s.request.token,input),'fresh handoff');structuredClone(input,{transfer:[input.buffer]});bad(r.renderer.provideInput(job,s.request.token,new Uint8Array(s.request.layout.tightBytes)),'duplicate input','invalid-request');}
   if(s.status==='needs-output'){scatter(r,s.request);ok(r.renderer.acknowledgeOutput(job,s.request.token),'output acknowledged after scatter');bad(r.renderer.acknowledgeOutput(job,s.request.token),'duplicate output','invalid-request');}
   if(seed)r.oracle.delayWaits((Math.imul(step+1,seed)>>>28)%3);
   await tick();
  }throw Error('bounded pump exhausted');
 }
 async function run(r,bytes,opts){const admitted=ok(r.renderer.beginSubmission(2,bytes),'begin');bytes.fill(0xa3);structuredClone(bytes,{transfer:[bytes.buffer]});return drain(r,admitted.job,opts);}
 function literal(image,phase,label){for(let q=0;q<4;q++)for(let y=4+16*(q>>1);y<12+16*(q>>1);y++)for(let x=4+16*(q&1);x<12+16*(q&1);x++){eq([...image.subarray((y*32+x)*4,(y*32+x)*4+4)],colors[phase][q],label+' literal GPU pixel');pixels++;}}
 async function replay(seed,poison=false){const r=rig({jobLimits:{commandsPerStep:7}});init(r);let count=0;const frames=[];try{if(poison)for(const s of fixtures.referenceOutputSnapshots)s.data.fill(0x93);for(const entry of fixtures.commands.submissions){if(entry.event===249)for(const a of fixtures.lifecycle.filter(a=>a.event<249))life(r,a);const result=await run(r,Uint8Array.from(entry.data),{seed});count+=result.result.appliedCommands;const phase=[173,197,221].indexOf(entry.event);if(phase>=0){const image=r.ram.get(7).slice([64,4160,8256][phase],[64,4160,8256][phase]+4096);literal(image,phase,'original replay');frames.push(await sha(image));}}for(const a of fixtures.lifecycle.filter(a=>a.event>249))life(r,a);eq(count,210,'all original packets');eq(r.oracle.statistics().counts.drawElements,3,'three actual draws');records.push({name:'original replay',seed,poison,count,frames,events:r.oracle.events});return frames;}finally{r.cleanup();}}
 const original=await replay(0x9e3779b9);eq(await replay(0x243f6a88,true),original,'poison output snapshots irrelevant');eq(await replay(0xb7e15162),original,'third independent schedule');
 // Independent literal texture case: (1,1), padded stride, SG boundary inside row.
 const texels=Uint8Array.from({length:64},(_,i)=>i%4===3?255:((Math.floor(i/4)*13+i%4*41)%251));
 async function textureRig(){const r=rig();r.context();ok(r.store.createResource(texture),'4x4 literal texture');r.attach(11,[21,75]);ok(r.store.attachContext(2,11),'texture member');r.ram.get(11).set(texels);await run(r,transfer(11,1));return r;}
 for(const seed of [3,7,11]){const r=await textureRig();try{const ram=r.ram.get(11);ram.fill(0x57);const before=ram.slice(),job=ok(r.renderer.beginSubmission(2,transfer(11,2,{x:1,y:1,width:2,height:2,offset:18,stride:19})),'partial read').job;r.oracle.delayWaits(seed);let output;
  await drain(r,job,{hook(s){if(s.status!=='needs-output')return false;output=s.request;eq([...output.bytes],[...texels.slice(20,28),...texels.slice(36,44)],'partial literal dense GPU texels');ram[0]=0x66;ram[95]=0x77;before[0]=0x66;before[95]=0x77;scatter(r,output);ok(r.renderer.acknowledgeOutput(job,output.token),'partial scatter acknowledged');return true;}});
  before.set(texels.slice(20,28),18);before.set(texels.slice(36,44),37);eq([...ram],[...before],'only exact rows modified across SG split');records.push({name:'partial texture SG',seed,split:21,layout:output.layout,bytes:[...output.bytes],sha256:await sha(ram)});
 }finally{r.cleanup();}}
 // Malformed tails and step quotas do not rely on worker diagnostics.
 {const r=rig({jobLimits:{commandsPerStep:3}});r.context();try{const before=r.renderer.inspect(),events=r.oracle.events.length;bad(r.renderer.beginSubmission(2,join(packet(44),new Uint8Array([255,0,0,0]))),'malformed tail');eq(r.renderer.inspect(),before,'malformed admission is atomic');eq(r.oracle.events.length,events,'malformed admission makes no GL calls');const job=ok(r.renderer.beginSubmission(2,join(...Array.from({length:10},()=>packet(44)))),'bounded state-only job').job;bad(r.renderer.beginSubmission(2,new Uint8Array()),'overlap','busy');eq(ok(r.renderer.step(job),'budget step').appliedCommands,3,'exact step budget');bad(r.renderer.step({}),'foreign job','invalid-job');bad(r.renderer.destroyContext(2),'destroy active renderer','busy');await drain(r,job);bad(r.renderer.step(job),'consumed job','invalid-job');}finally{r.cleanup();}}
 // Empty cancellation before issue and while final fence waits, then successor.
 for(const beforeStep of [true,false]){const r=rig();r.context();try{const job=ok(r.renderer.beginSubmission(2,new Uint8Array()),'empty job').job;r.oracle.delayWaits(3);if(!beforeStep)eq(ok(r.renderer.step(job),'empty fence issue').status,'waiting-gpu','empty waits');ok(r.renderer.cancel(job),'empty cancel');bad(r.renderer.beginSubmission(2,new Uint8Array()),'cancel holds slot','busy');await drain(r,job,{error:'cancelled'});eq(r.oracle.statistics().counts.fenceSync,1,'one cancellation fence');eq(r.oracle.statistics().liveSyncs,0,'cancel sync freed');await run(r,new Uint8Array());records.push({name:'empty cancellation',beforeStep,events:r.oracle.events});}finally{r.cleanup();}}
 // Stale identities at an input pause fail before any upload into replacements.
 for(const mutation of ['backing','membership','resource','context']){const r=await textureRig();try{const job=ok(r.renderer.beginSubmission(2,transfer(11,1)),'pause input').job,q=ok(r.renderer.step(job),'input state').request,uploads=r.oracle.statistics().counts.texSubImage2D;
  if(mutation==='backing'){ok(r.store.detachBacking(11),'detach');r.attach(11,[96]);eq(q.backingGeneration===r.identities.get(11).backingGeneration,false,'backing generation changes');}
  else if(mutation==='membership'){ok(r.store.detachContext(2,11),'remove membership');ok(r.store.attachContext(2,11),'new membership');}
  else if(mutation==='resource'){ok(r.store.unref(11),'unref');ok(r.store.createResource(texture),'reuse ID');r.attach(11,[96]);ok(r.store.attachContext(2,11),'new identity member');eq(q.resource.generation===r.identities.get(11).resource.generation,false,'resource generation changes');}
  else{ok(r.store.destroyContext(2),'remove resource context');ok(r.store.createContext(2),'reuse resource context');ok(r.store.attachContext(2,11),'new context membership');}
  bad(r.renderer.provideInput(job,q.token,texels.slice()),'stale input '+mutation);const done=await drain(r,job,{error:mutation==='context'?'stale-context':'stale-ticket'});eq(r.oracle.statistics().counts.texSubImage2D,uploads,'stale mutation does not upload');records.push({name:'identity mutation',mutation,result:done.result});
 }finally{r.cleanup();}}
 // Cancel output; the old acknowledgement cannot touch a new attachment/job.
 {const r=await textureRig();try{const job=ok(r.renderer.beginSubmission(2,transfer(11,2)),'read then cancel').job;let stale;for(let n=0;n<256;n++){const s=ok(r.renderer.step(job),'cancel output pump');if(s.status==='needs-output'){stale=s.request;break;}await tick();}eq(!!stale,true,'output reached');ok(r.renderer.cancel(job),'cancel output');await drain(r,job,{error:'cancelled'});ok(r.store.detachBacking(11),'detach old output');r.attach(11,[96]);r.ram.get(11).fill(0x8b);bad(r.renderer.acknowledgeOutput(job,stale.token),'old job output cannot publish','invalid-job');eq([...r.ram.get(11)],Array(96).fill(0x8b),'new backing untouched');await run(r,packet(44));}finally{r.cleanup();}}
 // Original actual index staging: public upload changes revision while paused.
 {const r=rig();init(r);try{const job=ok(r.renderer.beginSubmission(2,raw(161)),'staged index mutation').job;let mutated=false;await drain(r,job,{error:'stale-storage',hook(s){if(s.status==='waiting-gpu'&&r.asyncAccess.inspect().reads===1&&!mutated){const bytes=Uint8Array.from(fixtures.backing.find(x=>x.resourceId===4).ranges[0].data);new DataView(bytes.buffer).setUint16(2,0xfffe,true);ok(r.store.writeBacking(4,0,bytes),'live index replacement bytes');const command=ok(decodeSubmission(raw(161).slice(56,112)),'independent upload packet').commands[0];const ticket=ok(r.store.prepareTransfer(2,command),'public upload').ticket;ok(r.store.executeTransfer(ticket),'replace actual index storage');mutated=true;return true;}return false;}});eq(mutated,true,'mutated after staging before draw');eq(r.oracle.statistics().counts.drawElements??0,0,'no draw with stale staged indices');}finally{r.cleanup();}}
 // Waiting failure must never collect or claim completion. Disposal revokes all.
 {const r=await textureRig();try{const job=ok(r.renderer.beginSubmission(2,transfer(11,2)),'failed wait').job;eq(ok(r.renderer.step(job),'issue read').status,'waiting-gpu','read waits');const collections=r.oracle.statistics().counts.getBufferSubData??0;r.oracle.failWait();await tick();const s=ok(r.renderer.step(job),'failed wait step');eq(s.status,'done','failed wait terminal');bad(s.result,'wait failure','backend-error');eq(s.result.gpuComplete,false,'failure does not claim completion');eq(r.oracle.statistics().counts.getBufferSubData??0,collections,'failed wait collects nothing');}finally{r.cleanup();}}
 {const r=await textureRig();const job=ok(r.renderer.beginSubmission(2,transfer(11,2)),'dispose pending').job;ok(r.renderer.step(job),'start disposed read');ok(r.store.dispose(),'store first disposal');const done=ok(r.renderer.step(job),'disposed job terminates');eq(done.status,'done','disposed terminal');eq(done.result.gpuComplete,false,'disposed no GPU promise');bad(done.result,'disposed result','stale-context');bad(r.renderer.step(job),'disposed token stale','invalid-job');r.cleanup();}
 // Input diagnostics cannot consume the valid exchange; replay after rejection.
 {const r=await textureRig();try{const job=ok(r.renderer.beginSubmission(2,transfer(11,1)),'input diagnostics').job,q=ok(r.renderer.step(job),'input pause').request;
  for(const value of [new Uint8Array(63),new Uint16Array(32),new Uint8Array(new SharedArrayBuffer(64)),{}])bad(r.renderer.provideInput(job,q.token,value),'invalid input bytes','invalid-input');
  bad(r.renderer.provideInput(job,{},texels.slice()),'foreign input token','invalid-request');
  eq(r.renderer.inspect().jobs.status,'needs-input','invalid bytes preserve exchange');await drain(r,job);
 }finally{r.cleanup();}}
 // Whole-job draw quotas persist through commandsPerStep=1 and index-read yields.
 {const r=rig({jobLimits:{commandsPerStep:1},drawLimits:{drawsPerSubmission:2}});init(r);try{await run(r,raw(161).slice(0,5684));const draw=raw(161).slice(5684);const result=await run(r,join(draw,draw,draw),{error:'limit-exceeded'});eq(result.result.appliedCommands,2,'whole-job successful command prefix');eq(result.result.draws.length,2,'whole-job successful draw prefix');eq(r.oracle.statistics().counts.drawElements,2,'only quota-permitted draws issued');await run(r,draw.slice());}finally{r.cleanup();}}
 // Tightened job/CPU/GPU budgets reject and leave no owned job reservations.
 for(const options of [{jobLimits:{jobs:0}},{jobLimits:{submissionBytes:0}},{jobLimits:{transferBytes:1}},{resourceLimits:{scratchBytes:1}},{resourceLimits:{gpuBytes:64}}]){const r=rig(options);r.context();try{ok(r.store.createResource(texture),'budget texture');r.attach(11,[64]);ok(r.store.attachContext(2,11),'budget membership');const admitted=r.renderer.beginSubmission(2,transfer(11,2));if(options.jobLimits?.jobs===0||options.jobLimits?.submissionBytes===0)bad(admitted,'job admission budget','limit-exceeded');else await drain(r,ok(admitted,'budget admitted').job,{error:'limit-exceeded'});eq(r.renderer.inspect().jobs.active,0,'budget releases active job');eq(r.asyncAccess.inspect().stagingBytes,0,'budget staging zero');}finally{r.cleanup();}}
 // Cancellation while PBO work is pending drains without collecting output.
 {const r=await textureRig();try{const job=ok(r.renderer.beginSubmission(2,transfer(11,2)),'pending cancel').job;ok(r.renderer.step(job),'issue cancelled PBO');r.oracle.delayWaits(4);const before=r.oracle.statistics().counts.getBufferSubData??0;ok(r.renderer.cancel(job),'cancel pending PBO');await drain(r,job,{error:'cancelled'});eq(r.oracle.statistics().counts.getBufferSubData??0,before,'cancelled read never exposes bytes');}finally{r.cleanup();}}
 // Trusted failure wrappers cover cleanup and exception propagation without fake GPU data.
 for(const disposal of [false,true]){const r=await textureRig();try{let token;if(disposal){const lease=ok(r.store.retainStorage(2,11,'readback'),'trusted retained texture').lease;token=ok(r.asyncAccess.beginStorageRead(lease,{x:0,y:0,z:0,width:4,height:4,depth:1}),'trusted staged storage').ticket;}else{const command=ok(decodeSubmission(transfer(11,2)),'trusted transfer decode').commands[0];token=ok(r.asyncAccess.prepareTransfer(2,command),'trusted async transfer').ticket;ok(r.asyncAccess.beginTransferRead(token),'trusted staged transfer');}r.faults.release=true;bad(disposal?r.store.dispose():r.asyncAccess.release(token),'release error still cleans ownership','backend-error');eq(r.asyncAccess.inspect().stagingBytes,0,'failed release charged staging zero');if(disposal)ok(r.asyncAccess.release(token),'post-disposal tombstone release');}finally{r.cleanup();}}
 {const r=await textureRig();try{const lease=ok(r.store.retainStorage(2,11,'readback'),'direct backend lease').lease,storage=ok(r.bindings.resolve(lease),'direct backend storage').storage,layout={box:{x:0,y:0,width:4,height:4},tightBytes:64};const entry=r.backend.beginReadback(storage,texture,layout);r.backend.releaseReadback(entry);const before=r.oracle.statistics();r.backend.releaseReadback(entry);eq(r.oracle.statistics(),before,'idempotent native read release');ok(r.store.releaseStorage(lease),'direct lease release');}finally{r.cleanup();}}
 for(const semanticFailure of [false,true]){const r=rig();r.context();try{const job=ok(r.renderer.beginSubmission(2,semanticFailure?transfer(99,2):new Uint8Array()),'trusted throwing fence').job;r.faults.fence=true;let message;try{r.renderer.step(job);}catch(e){message=e.message;}eq(message,'trusted fence allocator fault','programmer fault propagates unchanged');records.push({name:'trusted fence exception',semanticFailure,message});}finally{r.cleanup();}}
 {const r=await textureRig();try{const command=ok(decodeSubmission(transfer(11,1)),'gather fault decode').commands[0],original=globalThis.Uint8Array,before=r.store.inspect().budgets;let once=true,message;try{globalThis.Uint8Array=new Proxy(original,{construct(t,args){if(once&&args.length===1&&args[0]===64){once=false;throw Error('trusted gather allocation fault');}return Reflect.construct(t,args);}});r.store.prepareTransfer(2,command);}catch(e){message=e.message;}finally{globalThis.Uint8Array=original;}eq(message,'trusted gather allocation fault','gather fault propagated');eq(r.store.inspect().budgets,before,'gather fault returned scratch reservation');records.push({name:'trusted gather exception',message});}finally{r.cleanup();}}
 // Real context loss revokes an outstanding native PBO read without claiming a signal.
 {const r=await textureRig(),job=ok(r.renderer.beginSubmission(2,transfer(11,2)),'native context loss').job;ok(r.renderer.step(job),'issue before loss');const lose=native.getExtension('WEBGL_lose_context');eq(!!lose,true,'context-loss extension');lose.loseContext();await tick();eq(native.isContextLost(),true,'actual native context lost');const done=ok(r.renderer.step(job),'lost step');eq(done.status,'done','loss terminates');eq(done.result.ok,false,'loss fails');eq(done.result.gpuComplete,false,'loss makes no completion promise');const error=native.getError();eq([0,native.CONTEXT_LOST_WEBGL].includes(error),true,'context-loss GL diagnostic');r.cleanup();records.push({name:'actual context loss',result:done.result});}
 eq(native.getError(),0,'final GL error');return{status:'passed',assertions,pixels,heartbeats,records,oracleEvents:oracles.map(o=>o.events),oracleStatistics:oracles.map(o=>o.statistics())};
}
