import {createVirglShaderBridge} from '/renderer/virgl-shader/index.mjs';
const check=(x,m)=>{if(!x)throw Error(m);};
const eq=(a,b,m)=>check(JSON.stringify(a)===JSON.stringify(b),`${m}: expected ${JSON.stringify(b)}, got ${JSON.stringify(a)}`);
const hash=async s=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',typeof s==='string'?new TextEncoder().encode(s):s))].map(v=>v.toString(16).padStart(2,'0')).join('');
const base='/evidence/virgl-raw-bits/verifier/';
const fetchJSON=async p=>{const r=await fetch(base+p);check(r.ok,p);return r.json();};
function reference(v){const M=0xffffffffn,A=v.a.map(BigInt),B=v.b.map(BigInt),C=v.c.map(BigInt),D=v.d.map(BigInt),E=v.e.map(BigInt);const t=[(A[1]<<(B[0]&31n))&M,(A[0]<<(B[1]&31n))&M,A[2],A[3]];return t.map((x,i)=>Number((((x>>(C[i]&31n))|D[i])&E[i])^(i===3?M:0n)));}
export async function runAcceptance({sabotage=false}={}){
 const report={status:'running',guestExecution:false,productionVirgl:false,hostUniformInjectionOnly:true,sabotage,parity:[],shaders:[],vertex:[],fragment:[],objects:{created:0,deleted:0},omissions:[]};window.__independentRawReport=report;
 try{
 let module;const bridge=await createVirglShaderBridge({onRuntimeInitialized(){module=this;}}),memory=module.HEAPU8.buffer;
 const cases=await fetchJSON('native-cases.json');const nativeText=await(await fetch(base+'audit-native.jsonl')).text(),results=nativeText.trimEnd().split('\n').map(JSON.parse);
 const retained=[];report.publicGuardCases=0;
 const core=c=>{const ptr=module._malloc(c.text.length+1);check(ptr,'independent core allocation');try{for(let k=0;k<c.text.length;k++)module.HEAPU8[ptr+k]=c.text.charCodeAt(k);module.HEAPU8[ptr+c.text.length]=0;return JSON.parse(module.UTF8ToString(module._bridge_translate(c.stage==='vertex'?0:1,ptr,c.text.length)));}finally{module._free(ptr);}};
 for(let i=0;i<cases.length;i++){const c=cases[i],r=core(c);eq(r,results[3*i],`full native/Wasm ${c.name}`);const exposed=bridge.translate({stage:c.stage,text:c.text});if(/[^\x09\x0a\x0d\x20-\x7e]/.test(c.text)){eq(exposed,{ok:false,error:{code:'invalid-input',message:'TGSI must be printable ASCII without NUL bytes.'}},'unchanged JS input guard');report.publicGuardCases++;}else eq(exposed,r,'public/core equality');eq(module.HEAPU8.byteLength,16777216,'fixed heap');check(module.HEAPU8.buffer===memory,'fixed heap identity');report.parity.push({name:c.name,resultSha256:await hash(JSON.stringify(r))});if(i<4)retained.push([r,JSON.stringify(r)]);}
 for(const[r,s]of retained)eq(JSON.stringify(r),s,'retained output ownership');
 report.nativeOutputSha256=await hash(nativeText);report.parityCount=cases.length;
 const fixture=await fetchJSON('hardware-fixture.json'),shaders=new Map();
 for(const s of fixture.shaders){const result=bridge.translate({stage:s.stage,text:s.text});check(result.ok,s.name);const record={...s,inputSha256:await hash(s.text),result};report.shaders.push(record);shaders.set(s.name,record);}
 const canvas=document.querySelector('#gpu');canvas.width=canvas.height=1;const gl=canvas.getContext('webgl2',{antialias:false,preserveDrawingBuffer:true,failIfMajorPerformanceCaveat:true});check(gl instanceof WebGL2RenderingContext,'real WebGL2');const ext=gl.getExtension('WEBGL_debug_renderer_info');check(ext,'driver');report.renderer=gl.getParameter(ext.UNMASKED_RENDERER_WEBGL);check(!/swiftshader|llvmpipe|software|fake|mock/i.test(report.renderer),'hardware');
 const owned=[];
 const make=(kind,...args)=>{const o=gl['create'+kind](...args);check(o,kind);owned.push([kind,o]);report.objects.created++;return o;};
 const dropAll=()=>{while(owned.length){const[k,o]=owned.pop();gl['delete'+k](o);report.objects.deleted++;}};
 function program(v,f,tf=false){const p=make('Program'),record={vertex:v.name,fragment:f.name,compiled:[],linked:false};for(const s of[v,f]){const sh=make('Shader',s.stage==='vertex'?gl.VERTEX_SHADER:gl.FRAGMENT_SHADER);let glsl=s.result.glsl;if(sabotage&&s.name==='alias-vertex-0'){const from='raw_temp[117].y << (vsconst0[43].x & 31u)',to='raw_temp[117].x << (vsconst0[43].x & 31u)';check(glsl.includes(from),'unique semantic alias sabotage target');glsl=glsl.replace(from,to);report.omissions.push({name:s.name,from,to,original:glsl.length});}gl.shaderSource(sh,glsl);gl.compileShader(sh);const ok=gl.getShaderParameter(sh,gl.COMPILE_STATUS);record.compiled.push({stage:s.stage,ok,log:gl.getShaderInfoLog(sh)});check(ok,'compile '+s.name);gl.attachShader(p,sh);}if(tf)gl.transformFeedbackVaryings(p,['gl_Position','vso_g0'],gl.INTERLEAVED_ATTRIBS);gl.linkProgram(p);record.linked=gl.getProgramParameter(p,gl.LINK_STATUS);record.log=gl.getProgramInfoLog(p);check(record.linked,'link');gl.useProgram(p);const block=gl.getUniformBlockIndex(p,'VirglBlock');check(block!==gl.INVALID_INDEX,'system block');const size=gl.getActiveUniformBlockParameter(p,block,gl.UNIFORM_BLOCK_DATA_SIZE);eq(size,656,'system byte length');const index=gl.getUniformIndices(p,['winsys_adjust_y'])[0],offset=gl.getActiveUniforms(p,[index],gl.UNIFORM_OFFSET)[0];eq(offset,640,'system offset');const ubo=make('Buffer');gl.bindBuffer(gl.UNIFORM_BUFFER,ubo);const b=new Uint8Array(656);new DataView(b.buffer).setFloat32(640,1,true);gl.bufferData(gl.UNIFORM_BUFFER,b,gl.STATIC_DRAW);gl.uniformBlockBinding(p,block,0);gl.bindBufferBase(gl.UNIFORM_BUFFER,0,ubo);return[p,record];}
 const positions=[[-.5,-.25,.25,1],[.75,.5,-.25,1],[-.125,.875,.5,1]];
 function vertexInput(p,points){const vao=make('VertexArray');gl.bindVertexArray(vao);const b=make('Buffer');gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(points.flat()),gl.STATIC_DRAW);const loc=gl.getAttribLocation(p,'in_0');check(loc>=0,'input');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,4,gl.FLOAT,false,0,0);}
 function upload(p,prefix,v,bit=0){const words=new Uint32Array(184);for(const[index,values]of [[45,v.a],[43,v.b],[42,v.c],[41,v.d],[40,v.e],[44,[bit,bit,bit,bit]]])words.set(values,index*4);const loc=gl.getUniformLocation(p,prefix+'const0[0]');check(loc!==null,'direct raw uniform');gl.uniform4uiv(loc,words);return [...words];}
 function floatBits(values){return [...new Uint32Array(new Float32Array(values).buffer)];}
 for(let lane=0;lane<4;lane++){
  const[p,compile]=program(shaders.get('alias-vertex-'+lane),shaders.get('legacy-fragment'),true);vertexInput(p,positions);const feedback=make('TransformFeedback'),buffer=make('Buffer');gl.bindTransformFeedback(gl.TRANSFORM_FEEDBACK,feedback);gl.bindBuffer(gl.TRANSFORM_FEEDBACK_BUFFER,buffer);gl.bufferData(gl.TRANSFORM_FEEDBACK_BUFFER,112,gl.STREAM_READ);gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,buffer);const record={lane,compile,vectors:[]};report.vertex.push(record);
  for(const v of fixture.vectors){const expected=reference(v);eq(expected,v.expected,'two independent integer oracles');const words=upload(p,'vs',v),sentinel=new Uint32Array(28).fill(0xdeadc0de);gl.bindBuffer(gl.TRANSFORM_FEEDBACK_BUFFER,buffer);gl.bufferSubData(gl.TRANSFORM_FEEDBACK_BUFFER,0,sentinel);gl.enable(gl.RASTERIZER_DISCARD);gl.beginTransformFeedback(gl.POINTS);gl.drawArrays(gl.POINTS,0,3);gl.endTransformFeedback();gl.disable(gl.RASTERIZER_DISCARD);const raw=new Uint32Array(28);gl.getBufferSubData(gl.TRANSFORM_FEEDBACK_BUFFER,0,raw);eq(gl.getError(),gl.NO_ERROR,'TF errors');const enc=Array.from({length:4},(_,i)=>(0x3f000000|(((expected[lane]>>>(i*8))&255)<<15))>>>0),want=positions.flatMap(p=>[...floatBits(p),...enc]).concat([0xdeadc0de,0xdeadc0de,0xdeadc0de,0xdeadc0de]);const got=[...raw];record.vectors.push({name:v.name,uniformWords:words,expected,expectedCarrierBits:enc,rawWords:got,expectedRawWords:want});eq(got,want,`novel alias vertex ${v.name} lane ${lane}`);let reconstructed=0n;for(let i=0;i<4;i++)reconstructed|=BigInt((raw[4+i]-0x3f000000)>>>15)<<(8n*BigInt(i));eq(Number(reconstructed),expected[lane],'complete reconstructed u32');}
  gl.bindTransformFeedback(gl.TRANSFORM_FEEDBACK,null);gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,null);gl.bindVertexArray(null);dropAll();
 }
 const[p,compile]=program(shaders.get('legacy-vertex'),shaders.get('alias-fragment'));vertexInput(p,[[-1,-1,0,1],[3,-1,0,1],[-1,3,0,1]]);gl.viewport(0,0,1,1);for(const cap of [gl.BLEND,gl.DITHER,gl.CULL_FACE,gl.DEPTH_TEST,gl.SCISSOR_TEST])gl.disable(cap);
 const fb=make('Framebuffer'),texture=make('Texture');gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texture,0);eq(gl.checkFramebufferStatus(gl.FRAMEBUFFER),gl.FRAMEBUFFER_COMPLETE,'framebuffer');
 for(const v of fixture.vectors){const expected=reference(v),record={name:v.name,compile,expected,planes:[]};report.fragment.push(record);const reconstructed=[0n,0n,0n,0n];for(let bit=0;bit<32;bit++){const words=upload(p,'fs',v,bit);gl.clearColor(.5,.5,.5,.5);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawArrays(gl.TRIANGLES,0,3);const raw=new Uint8Array(4);gl.readPixels(0,0,1,1,gl.RGBA,gl.UNSIGNED_BYTE,raw);eq(gl.getError(),gl.NO_ERROR,'pixel errors');const want=expected.map(w=>((w>>>bit)&1)*255);record.planes.push({bit,selectorWords:words.slice(176,180),rawBytes:[...raw],expected:want});eq([...raw],want,`novel alias fragment ${v.name} bit ${bit}`);for(let lane=0;lane<4;lane++)if(raw[lane]===255)reconstructed[lane]|=1n<<BigInt(bit);}record.reconstructed=reconstructed.map(Number);eq(record.reconstructed,expected,'complete fragment u32');}
 gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.bindVertexArray(null);dropAll();eq(report.objects.created,report.objects.deleted,'objects released');check(!sabotage,'semantic sabotage must fail');report.status='passed';report.checkedWords=fixture.vectors.length*8;report.memoryBytes=module.HEAPU8.byteLength;document.querySelector('#status').textContent=`Independent probe passed: ${report.parityCount} complete parity cases, ${report.checkedWords} exact words, overlap and dynamic count changes`;document.querySelector('#renderer').textContent=report.renderer;return report;
 }catch(error){report.status='failed';report.failure={message:error.message,stack:error.stack};throw error;}
}
