import {createVirglShaderBridge} from '/renderer/virgl-shader/index.mjs';
const check=(x,m)=>{if(!x)throw Error(m);};
const eq=(a,b,m)=>check(JSON.stringify(a)===JSON.stringify(b),`${m}: expected ${JSON.stringify(b)}, got ${JSON.stringify(a)}`);
const hash=async s=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',typeof s==='string'?new TextEncoder().encode(s):s))].map(v=>v.toString(16).padStart(2,'0')).join('');
const base='/evidence/virgl-numeric-floats/verifier/';
const fetchJSON=async p=>{const r=await fetch(base+p);check(r.ok,p);return r.json();};
export async function runAcceptance({sabotage=false}={}){
 const report={status:'running',guestExecution:false,productionVirgl:false,hostUniformInjectionOnly:true,sabotage,parity:[],shaders:[],vertex:[],fragment:[],objects:{created:0,deleted:0},omissions:[]};window.__independentRawReport=report;
 try{
 let module;const bridge=await createVirglShaderBridge({onRuntimeInitialized(){module=this;}}),memory=module.HEAPU8.buffer;
 const cases=await fetchJSON('native-cases.json');const nativeText=await(await fetch(base+'audit-native.jsonl')).text(),results=nativeText.trimEnd().split('\n').map(JSON.parse);
 const retained=[];report.publicGuardCases=0;
 const core=c=>{const ptr=module._malloc(c.text.length+1);check(ptr,'independent core allocation');try{for(let k=0;k<c.text.length;k++)module.HEAPU8[ptr+k]=c.text.charCodeAt(k);module.HEAPU8[ptr+c.text.length]=0;return JSON.parse(module.UTF8ToString(module._bridge_translate(c.stage==='vertex'?0:1,ptr,c.text.length)));}finally{module._free(ptr);}};
 for(let i=0;i<cases.length;i++){const c=cases[i],r=core(c);eq(r,results[3*i],`full native/Wasm ${c.name}`);const exposed=bridge.translate({stage:c.stage,text:c.text});if(/[^\x09\x0a\x0d\x20-\x7e]/.test(c.text)){eq(exposed,{ok:false,error:{code:'invalid-input',message:'TGSI must be printable ASCII without NUL bytes.'}},'unchanged JS input guard');report.publicGuardCases++;}else eq(exposed,r,'public/core equality');eq(module.HEAPU8.byteLength,16777216,'fixed heap');check(module.HEAPU8.buffer===memory,'fixed heap identity');report.parity.push({name:c.name,resultSha256:await hash(JSON.stringify(r))});if(i<4)retained.push([r,JSON.stringify(r)]);}
 for(const[r,s]of retained)eq(JSON.stringify(r),s,'retained output ownership');
 report.nativeOutputSha256=await hash(nativeText);report.parityCount=cases.length;
 const fixture=await fetchJSON('hardware-fixture.json'),shaders=new Map();for(const s of fixture.shaders){const result=bridge.translate({stage:s.stage,text:s.text});check(result.ok,s.name+JSON.stringify(result));report.shaders.push({...s,result,inputSha256:await hash(s.text)});shaders.set(s.name,{...s,result});}
 const canvas=document.querySelector('#gpu');canvas.width=canvas.height=1;const gl=canvas.getContext('webgl2',{antialias:false,preserveDrawingBuffer:true,failIfMajorPerformanceCaveat:true});check(gl instanceof WebGL2RenderingContext,'hardware WebGL2');const ext=gl.getExtension('WEBGL_debug_renderer_info');check(ext,'driver');report.renderer=gl.getParameter(ext.UNMASKED_RENDERER_WEBGL);check(!/swiftshader|llvmpipe|software|fake|mock/i.test(report.renderer),'real hardware');
 const owned=[];const make=(k,...a)=>{const o=gl['create'+k](...a);check(o,k);owned.push([k,o]);report.objects.created++;return o;};const clean=()=>{while(owned.length){const[k,o]=owned.pop();gl['delete'+k](o);report.objects.deleted++;}};
 const fbits=values=>[...new Uint32Array(new Float32Array(values).buffer)];
 const reference=v=>{const p=v.a.map(x=>x/8+.5),q=v.b.map(x=>x/16),t=p.map((x,i)=>v.c[i]?x:q[i]);[t[0],t[1]]=[t[1],t[0]];const r=t.map(x=>x*.5-.25);r[2]=p[1];r[3]=q[2];return{rawBits:fbits(r),numericBits:fbits(r.map(x=>x+.5))};};
 function program(v,f,tf=false){const p=make('Program'),record={vertex:v.name,fragment:f.name,compiled:[]};for(const s of[v,f]){const sh=make('Shader',s.stage==='vertex'?gl.VERTEX_SHADER:gl.FRAGMENT_SHADER);let src=s.result.glsl;if(sabotage&&s.name==='numeric-vertex-x'){const from='float_temp[2].y',to='float_temp[2].z';check(src.includes(from),'shadow alias sabotage target');src=src.replace(from,to);report.omissions.push({name:s.name,from,to,originalGlsl:s.result.glsl,mutatedGlsl:src});}gl.shaderSource(sh,src);gl.compileShader(sh);const ok=gl.getShaderParameter(sh,gl.COMPILE_STATUS);record.compiled.push({stage:s.stage,ok,log:gl.getShaderInfoLog(sh),glslSha256:null});check(ok,'compile '+s.name);gl.attachShader(p,sh);}if(tf)gl.transformFeedbackVaryings(p,['gl_Position','vso_g0','vso_g1'],gl.INTERLEAVED_ATTRIBS);gl.linkProgram(p);record.linked=gl.getProgramParameter(p,gl.LINK_STATUS);record.log=gl.getProgramInfoLog(p);check(record.linked,'link '+JSON.stringify(record));gl.useProgram(p);const block=gl.getUniformBlockIndex(p,'VirglBlock');check(block!==gl.INVALID_INDEX,'system block');eq(gl.getActiveUniformBlockParameter(p,block,gl.UNIFORM_BLOCK_DATA_SIZE),656,'system size');const ubo=make('Buffer');gl.bindBuffer(gl.UNIFORM_BUFFER,ubo);const b=new Uint8Array(656);new DataView(b.buffer).setFloat32(640,1,true);gl.bufferData(gl.UNIFORM_BUFFER,b,gl.STATIC_DRAW);gl.uniformBlockBinding(p,block,0);gl.bindBufferBase(gl.UNIFORM_BUFFER,0,ubo);return[p,record];}
 function input(p,name,values){const loc=gl.getAttribLocation(p,name);check(loc>=0,'active '+name);const b=make('Buffer');gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(values.flat()),gl.STATIC_DRAW);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,4,gl.FLOAT,false,0,0);}
 function upload(p,prefix,v,selector=null){const words=new Uint32Array([...v.c,...(selector===null?[0x7f800001,0xffffffff,0x80000001,0x12345678]:[selector,selector,selector,selector])]);const loc=gl.getUniformLocation(p,prefix+'const0[0]');check(loc!==null,'raw constants active');gl.uniform4uiv(loc,words);return [...words];}
 for(let lane=0;lane<4;lane++){const[p,compile]=program(shaders.get('numeric-vertex-'+'xyzw'[lane]),shaders.get('legacy-fragment'),true);const vao=make('VertexArray');gl.bindVertexArray(vao);const feedback=make('TransformFeedback'),buffer=make('Buffer');gl.bindTransformFeedback(gl.TRANSFORM_FEEDBACK,feedback);gl.bindBuffer(gl.TRANSFORM_FEEDBACK_BUFFER,buffer);gl.bufferData(gl.TRANSFORM_FEEDBACK_BUFFER,64,gl.STREAM_READ);gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,buffer);const record={lane,compile,vectors:[]};report.vertex.push(record);
 for(const v of fixture.vectors){const expected=reference(v);eq(expected.rawBits,v.rawBits,'independent dyadic bit oracle');eq(expected.numericBits,v.numericBits,'independent numeric oracle');input(p,'in_0',[[.125,-.25,.5,1]]);input(p,'in_1',[v.a.map(x=>x/8)]);input(p,'in_2',[v.b.map(x=>x/8)]);const words=upload(p,'vs',v),sentinel=new Uint32Array(16).fill(0xdeadc0de);gl.bindBuffer(gl.TRANSFORM_FEEDBACK_BUFFER,buffer);gl.bufferSubData(gl.TRANSFORM_FEEDBACK_BUFFER,0,sentinel);gl.enable(gl.RASTERIZER_DISCARD);gl.beginTransformFeedback(gl.POINTS);gl.drawArrays(gl.POINTS,0,1);gl.endTransformFeedback();gl.disable(gl.RASTERIZER_DISCARD);const raw=new Uint32Array(16);gl.getBufferSubData(gl.TRANSFORM_FEEDBACK_BUFFER,0,raw);eq(gl.getError(),0,'actual transform feedback');const carriers=Array.from({length:4},(_,i)=>(0x3f000000|(((expected.rawBits[lane]>>>(8*i))&255)<<15))>>>0),want=[...fbits([.125,-.25,.5,1]),...expected.numericBits,...carriers,0xdeadc0de,0xdeadc0de,0xdeadc0de,0xdeadc0de];record.vectors.push({name:v.name,a:v.a,b:v.b,uniformWords:words,expected,rawWords:[...raw],expectedWords:want});eq([...raw],want,'independent mixed alias '+v.name+' lane '+lane);}
 gl.bindTransformFeedback(gl.TRANSFORM_FEEDBACK,null);gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,null);gl.bindVertexArray(null);clean();}
 for(const target of [3,4]){const[p,compile]=program(shaders.get('legacy-vertex'),shaders.get('texture-fragment-'+target));const vao=make('VertexArray');gl.bindVertexArray(vao);input(p,'in_0',[[-1,-1,0,1],[3,-1,0,1],[-1,3,0,1]]);input(p,'in_1',[[.25,.75,0,1],[.25,.75,0,1],[.25,.75,0,1]]);gl.viewport(0,0,1,1);for(const cap of[gl.BLEND,gl.DITHER,gl.CULL_FACE,gl.DEPTH_TEST,gl.SCISSOR_TEST])gl.disable(cap);const tex=[];for(const unit of[0,7]){const t=make('Texture');tex.push(t);gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);const loc=gl.getUniformLocation(p,'fssamp'+unit);check(loc!==null,'sampler '+unit);gl.uniform1i(loc,unit);eq(gl.getUniform(p,loc),unit,'bound sampler');}
 const frame=make('Framebuffer'),out=make('Texture');gl.activeTexture(gl.TEXTURE0+6);gl.bindTexture(gl.TEXTURE_2D,out);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.bindFramebuffer(gl.FRAMEBUFFER,frame);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,out,0);eq(gl.checkFramebufferStatus(gl.FRAMEBUFFER),gl.FRAMEBUFFER_COMPLETE,'framebuffer');
 for(const v of fixture.textures){const expected=reference(v);eq(expected.rawBits,v.rawBits,'independent texture oracle');eq(expected.numericBits,v.numericBits,'independent texture numeric oracle');for(let i=0;i<2;i++){gl.activeTexture(gl.TEXTURE0+[0,7][i]);gl.bindTexture(gl.TEXTURE_2D,tex[i]);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array((i?v.b:v.a).map(x=>x?255:0)));}const wanted=target===3?expected.rawBits:expected.numericBits,record={name:v.name,target,compile,textures:[v.a.map(x=>x?255:0),v.b.map(x=>x?255:0)],wanted,planes:[]};report.fragment.push(record);for(let bit=0;bit<32;bit++){const uniformWords=upload(p,'fs',v,bit);gl.clearColor(.5,.5,.5,.5);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawArrays(gl.TRIANGLES,0,3);const pixel=new Uint8Array(4);gl.readPixels(0,0,1,1,gl.RGBA,gl.UNSIGNED_BYTE,pixel);eq(gl.getError(),0,'actual texture-chain pixel readback');const want=wanted.map(w=>((w>>>bit)&1)*255);record.planes.push({bit,uniformWords,rawBytes:[...pixel],expected:want});eq([...pixel],want,'texture chain '+target+' '+v.name+' bit '+bit);}}
 gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.bindVertexArray(null);clean();}
 eq(report.objects.created,report.objects.deleted,'objects released');check(!sabotage,'independent sabotage must fail');report.status='passed';report.checkedWords=fixture.vectors.length*8+fixture.textures.length*8;report.memoryBytes=module.HEAPU8.byteLength;document.querySelector('#status').textContent=`Independent numeric probe passed: ${report.parityCount} complete parity cases, ${report.checkedWords} exact numeric/raw words`;document.querySelector('#renderer').textContent=report.renderer;return report;
 }catch(error){report.status='failed';report.failure={message:error.message,stack:error.stack};throw error;}
}
