#include "raw_bits.h"
#include <assert.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static uint32_t rng;static uint64_t checks,mode_checks,rejections,instructions,aliases,shadow_checks,decode_checks,op_hits[RAW_TEX+1];
static uint32_t next(void){rng^=rng<<13;rng^=rng>>17;rng^=rng<<5;return rng;}
static uint32_t bits(float f){uint32_t b;memcpy(&b,&f,4);return b;}
static float value(uint32_t b){float f;memcpy(&f,&b,4);return f;}
/* Enumerate possible exponents independently of emitter's bitwise predicate. */
static int safe(struct raw_lane a){for(unsigned e=0;e<256;++e){uint32_t w=e<<23;if((w&a.zero&0x7f800000)||((~w)&a.one&0x7f800000))continue;if(e==255)return 0;if(e==0 && (~a.zero&0x7fffff))return 0;}return 1;}
static unsigned mode(struct raw_lane a){return a.origin?a.origin:safe(a)?34:0;}
static struct raw_lane lane(const struct raw_ir *ir,struct raw_source r,unsigned l){l=r.swizzle[l];if(r.file==TEMP)return ir->temporary[r.index][l];if(r.file==IMM){uint32_t b=ir->immediates[r.index][l];return(struct raw_lane){~b,b,0};}if(r.file==IN)return(struct raw_lane){0,0,1+r.index*4+l};return(struct raw_lane){0};}
struct world{uint32_t tmp[4][4],out[4],in[2][4],con[2][4];float shadow[4][4],oshadow[4];};
static uint32_t get(const struct raw_ir *ir,const struct world*w,struct raw_source r,unsigned l){l=r.swizzle[l];return r.file==TEMP?w->tmp[r.index][l]:r.file==IN?w->in[r.index][l]:r.file==IMM?ir->immediates[r.index][l]:w->con[r.index][l];}
static float floating(const struct raw_ir*ir,const struct world*w,struct raw_source r,unsigned l,unsigned m){if(m==33)return w->shadow[r.index][r.swizzle[l]];if(m==34)return value(get(ir,w,r,l));assert(m&&m<=32);return value(w->in[(m-1)/4][(m-1)%4]);}
static uint32_t ordered(uint32_t a,uint32_t b,int ge){unsigned sa=a>>31,sb=b>>31,ea=(a>>23)&255,eb=(b>>23)&255,fa=a&0x7fffff,fb=b&0x7fffff;if((ea==255&&fa)||(eb==255&&fb))return 0;int c;if(!(ea||eb||fa||fb))c=0;else if(sa!=sb)c=sa?-1:1;else{c=ea<eb?-1:ea>eb?1:fa<fb?-1:fa>fb?1:0;if(sa)c=-c;}return(ge?c>=0:c<0)?UINT32_MAX:0;}
static uint32_t calc(unsigned op,uint32_t a,uint32_t b,uint32_t c){switch(op){case RAW_MOV:return a;case RAW_AND:return a&b;case RAW_OR:return a|b;case RAW_NOT:return~a;case RAW_SHL:return a<<(b%32);case RAW_USHR:return a>>(b%32);case RAW_UADD:return(uint32_t)((uint64_t)a+b);case RAW_ISGE:return((int64_t)a-(a>=0x80000000?4294967296LL:0))>=((int64_t)b-(b>=0x80000000?4294967296LL:0))?UINT32_MAX:0;case RAW_USEQ:return a==b?UINT32_MAX:0;case RAW_USNE:return a!=b?UINT32_MAX:0;case RAW_UCMP:return a?b:c;case RAW_FSLT:return ordered(a,b,0);case RAW_FSGE:return ordered(a,b,1);default:abort();}}
static void checkfact(struct raw_lane f,uint32_t b,const struct world*w,float shadow){assert(!(f.zero&f.one));assert(!(f.zero&b));assert(!(f.one&~b));checks++;if(f.origin==33){assert(bits(shadow)==b);shadow_checks++;}else if(f.origin){assert(w->in[(f.origin-1)/4][(f.origin-1)%4]==b);shadow_checks++;}}
int main(void){const uint32_t seeds[]={0x199a526d,0x58407ec1,0x936ff217,0xa837105b,0xc5e8321d};const uint32_t edges[]={0,0x80000000,1,0x80000001,0x7f800000,0xff800000,0x7fc00001,0x3f000000,0xbf800000,0xffffffff,0x807fffff,0x00800000,0xff7fffff};
for(unsigned si=0;si<5;++si){rng=seeds[si];for(unsigned trial=0;trial<192;++trial){struct raw_ir *ir=calloc(1,sizeof(*ir));struct world w[16]={0};assert(ir);for(unsigned s=0;s<16;++s)for(unsigned r=0;r<2;++r)for(unsigned l=0;l<4;++l){w[s].in[r][l]=bits(((int)(next()%33)-16)*0.125f);w[s].con[r][l]=s<13?edges[(s+r+l)%13]:next();}for(unsigned r=0;r<4;++r)for(unsigned l=0;l<4;++l){uint32_t b=next(),mask=next();unsigned t=next()%5;ir->temporary[r][l]=(struct raw_lane){~b&mask,b&mask,t==0?1+next()%8:t==1?33:0};if(ir->temporary[r][l].origin)ir->temporary[r][l].zero=ir->temporary[r][l].one=0;for(unsigned s=0;s<16;++s){struct raw_lane a=ir->temporary[r][l];w[s].shadow[r][l]=((int)(next()%33)-16)*0.125f;w[s].tmp[r][l]=a.origin==33?bits(w[s].shadow[r][l]):a.origin?w[s].in[(a.origin-1)/4][(a.origin-1)%4]:(next()&~(a.zero|a.one))|a.one;}ir->immediates[r][l]=edges[(trial+r*4+l)%13];}
for(unsigned step=0;step<96;++step){struct raw_instruction ins={0};ins.opcode=step<17?step:next()%17;ins.flags=RAW_MIXED;ins.dst.file=step%9?TEMP:OUT;ins.dst.index=ins.dst.file==TEMP?next()%4:0;ins.dst.mask=1+next()%15;if(ins.opcode==RAW_TEX)ins.dst.mask=15;for(unsigned j=0;j<3;++j){enum file fs[]={TEMP,IMM,IN,CONST};ins.src[j].file=fs[next()%4];ins.src[j].index=next()%(ins.src[j].file==TEMP||ins.src[j].file==IMM?4:2);for(unsigned l=0;l<4;++l)ins.src[j].swizzle[l]=next()%4;if(ins.src[j].file==ins.dst.file&&ins.src[j].index==ins.dst.index)aliases++;}unsigned count=ins.opcode==RAW_MOV||ins.opcode==RAW_NOT||ins.opcode==RAW_TEX?1:ins.opcode==RAW_UCMP||ins.opcode==RAW_MAD?3:2;unsigned consumed=ins.opcode==RAW_TEX?3:ins.dst.mask;unsigned ms[3][4]={0};int numeric=ins.opcode>=RAW_ADD,accept=1;for(unsigned j=0;j<count;++j)for(unsigned l=0;l<4;++l)if(consumed&(1u<<l)){ms[j][l]=mode(lane(ir,ins.src[j],l));if(numeric&&!ms[j][l])accept=0;}
struct raw_ir before=*ir;int ok=raw_record(ir,&ins);assert(ok==accept);if(!ok){assert(memcmp(ir,&before,sizeof(*ir))==0);rejections++;continue;}instructions++;op_hits[ins.opcode]++;struct raw_instruction got=ir->instructions[ir->count-1];for(unsigned j=0;j<3;++j)for(unsigned l=0;l<4;++l){assert(((got.float_modes[j]>>(l*8))&255)==ms[j][l]);mode_checks++;}unsigned fm=0;struct raw_lane*dest=ins.dst.file==TEMP?ir->temporary[ins.dst.index]:ir->output[0];for(unsigned l=0;l<4;++l)if((ins.dst.mask&(1u<<l))&&dest[l].origin==33)fm|=1u<<l;assert(got.float_mask==fm);
for(unsigned s=0;s<16;++s){uint32_t out[4]={0};float floats[4]={0};for(unsigned l=0;l<4;++l)if(ins.dst.mask&(1u<<l)){uint32_t a=get(&before,&w[s],ins.src[0],l),b=count>1?get(&before,&w[s],ins.src[1],l):0,c=count>2?get(&before,&w[s],ins.src[2],l):0;if(numeric){if(ins.opcode==RAW_TEX)floats[l]=(s+l)%5*0.25f;else{float x=floating(&before,&w[s],ins.src[0],l,ms[0][l]),y=floating(&before,&w[s],ins.src[1],l,ms[1][l]);volatile float v=ins.opcode==RAW_ADD?x+y:x*y;if(ins.opcode==RAW_MAD)v=v+floating(&before,&w[s],ins.src[2],l,ms[2][l]);floats[l]=v;}out[l]=bits(floats[l]);}else{out[l]=calc(ins.opcode,a,b,c);if(fm&(1u<<l)){unsigned j=ins.opcode==RAW_UCMP?(a?1:2):0;assert(ms[j][l]);floats[l]=floating(&before,&w[s],ins.src[j],l,ms[j][l]);}}for(unsigned j=0;j<count;++j)if(ms[j][l]==34 && (consumed&(1u<<l))){uint32_t z=get(&before,&w[s],ins.src[j],l),e=(z>>23)&255;assert((e>0&&e<255)||(z&0x7fffffff)==0);decode_checks++;}}
for(unsigned l=0;l<4;++l)if(ins.dst.mask&(1u<<l)){if(ins.dst.file==TEMP){w[s].tmp[ins.dst.index][l]=out[l];if(fm&(1u<<l))w[s].shadow[ins.dst.index][l]=floats[l];}else{w[s].out[l]=out[l];if(fm&(1u<<l))w[s].oshadow[l]=floats[l];}}
for(unsigned r=0;r<4;++r)for(unsigned l=0;l<4;++l)checkfact(ir->temporary[r][l],w[s].tmp[r][l],&w[s],w[s].shadow[r][l]);for(unsigned l=0;l<4;++l)checkfact(ir->output[0][l],w[s].out[l],&w[s],w[s].oshadow[l]);}
}free(ir);}}
printf("{\"ok\":true,\"instructions\":%"PRIu64",\"rejectedWithoutMutation\":%"PRIu64",\"factAssertions\":%"PRIu64",\"instructionModeAssertions\":%"PRIu64",\"shadowAssertions\":%"PRIu64",\"decodeAssertions\":%"PRIu64",\"aliases\":%"PRIu64",\"opcodes\":[",instructions,rejections,checks,mode_checks,shadow_checks,decode_checks,aliases);for(unsigned i=0;i<=RAW_TEX;++i)printf("%s%"PRIu64,i?",":"",op_hits[i]);puts("]}");}
