// AUTO-GENERATED by the E0-T08 verifier's spec-first Python model (model.py).
//! E0-T08 verifier angle-1 substitute: 41-instruction program mixing all 11
//! memory ops with computational ops, stepped as a PROGRAM; full register file and
//! a 48-byte data window compared against an independent spec-first model.
use wasm_vm_core::bus::Bus;
use wasm_vm_core::hart::Hart;
use wasm_vm_core::mmio::SystemBus;
use wasm_vm_core::ram::Ram;

const CODE: u64 = 0x80000000;
const DATA: u64 = 0x80000800;
const PROG: &[u32] = &[
    0x00000097, 0x7F808113, 0x00810113, 0x123451B7, 0x67818193, 0x00312023, 0xFFF00213, 0x00413423,
    0x00310823, 0x00411923, 0x00810283, 0x00814303, 0x01211383, 0x01215403, 0x00012483, 0x00816503,
    0x00813583, 0x00548633, 0x00C12A23, 0x01412683, 0x02010713, 0xFED73C23, 0x01813783, 0x00810813,
    0x00083803, 0x410008B3, 0xFE971F23, 0xFFE75903, 0x02891993, 0x4219DA13, 0x034100A3, 0x02110A83,
    0x00B48B3B, 0x01816B83, 0x00DBCC33, 0x001C3C93, 0x03913423, 0x02813D03, 0x00211D83, 0x00310E03,
    0x00114E83,
];
const EXPECT_REGS: [u64; 32] = [
    0x0000000000000000,
    0x0000000080000000,
    0x0000000080000800,
    0x0000000012345678,
    0xFFFFFFFFFFFFFFFF,
    0xFFFFFFFFFFFFFFFF,
    0x00000000000000FF,
    0xFFFFFFFFFFFFFFFF,
    0x000000000000FFFF,
    0x0000000012345678,
    0x00000000FFFFFFFF,
    0xFFFFFFFFFFFFFFFF,
    0x0000000012345677,
    0x0000000012345677,
    0x0000000080000820,
    0x0000000012345677,
    0xFFFFFFFFFFFFFFFF,
    0x0000000000000001,
    0x0000000000005678,
    0x0056780000000000,
    0x00000000002B3C00,
    0x0000000000000000,
    0x0000000012345677,
    0x0000000012345677,
    0x0000000000000000,
    0x0000000000000001,
    0x0000000000000001,
    0x0000000000001234,
    0x0000000000000012,
    0x0000000000000056,
    0x0000000000000000,
    0x0000000000000000,
];
const EXPECT_MEM: [u8; 48] = [
    0x78, 0x56, 0x34, 0x12, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0x78, 0x00, 0xFF, 0xFF, 0x77, 0x56, 0x34, 0x12, 0x77, 0x56, 0x34, 0x12, 0x00, 0x00, 0x78, 0x56,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
];

#[test]
fn program_differential_vs_spec_model() {
    let mut bus = SystemBus::new(Ram::new(64 * 1024).unwrap());
    let mut hart = Hart::new();
    hart.regs.pc = CODE;
    for (i, w) in PROG.iter().enumerate() {
        bus.store32(CODE + 4 * i as u64, *w).unwrap();
    }
    for i in 0..PROG.len() {
        hart.step(&mut bus)
            .unwrap_or_else(|t| panic!("step {i} trapped: {t:?}"));
    }
    assert_eq!(hart.regs.pc, CODE + 4 * PROG.len() as u64, "final pc");
    for r in 0..32u8 {
        assert_eq!(hart.regs.read(r), EXPECT_REGS[r as usize], "x{r} mismatch");
    }
    let mut got = [0u8; 48];
    bus.ram().read_slice(DATA, &mut got).unwrap();
    assert_eq!(got, EXPECT_MEM, "data window mismatch");
}
