import {createVirglShaderBridge,LIMITS} from '../index.mjs';
import {createProgram,texture2d,bindSystemBlocks,digest} from './browser.mjs';
import {approve} from './original-corpus.mjs';
import {getCases,getPairs,ENVELOPE} from '../../../tools/virgl-compiler-bounds/cases.mjs';
const require=(v,label)=>{if(!v)throw new Error(label);},equal=(a,b,label)=>require(JSON.stringify(a)===JSON.stringify(b),`${label}: ${JSON.stringify(a)} != ${JSON.stringify(b)}`);
const word=value=>new Uint32Array(new Float32Array([value]).buffer)[0],clone=value=>JSON.parse(JSON.stringify(value)),WIDTH=8;
function monitor(native,report){let serial=0;const ids=new WeakMap(),live=new Map(),objects=[];
 const creates={createShader:'Shader',createProgram:'Program',createBuffer:'Buffer',createTexture:'Texture',createFramebuffer:'Framebuffer',createVertexArray:'VertexArray',createTransformFeedback:'TransformFeedback'};
 const gl=new Proxy(native,{get(target,key){const value=Reflect.get(target,key,target);if(typeof value!=='function')return value;return(...args)=>{
  const result=value.apply(target,args);
  if(creates[key]&&result){const id=`${creates[key]}:${++serial}`;ids.set(result,id);live.set(id,creates[key]);objects.push({id,kind:creates[key],object:result});report.events.push({call:key,id});}
  if(/^delete/.test(key)&&args[0]){live.delete(ids.get(args[0]));report.events.push({call:key,id:ids.get(args[0])});}
  if(key==='shaderSource')report.events.push({call:key,id:ids.get(args[0]),source:args[1]});
  if(key==='compileShader')report.events.push({call:key,id:ids.get(args[0]),status:target.getShaderParameter(args[0],target.COMPILE_STATUS),log:target.getShaderInfoLog(args[0])});
  if(key==='linkProgram')report.events.push({call:key,id:ids.get(args[0]),status:target.getProgramParameter(args[0],target.LINK_STATUS),log:target.getProgramInfoLog(args[0])});
  if(['drawArrays','beginTransformFeedback','endTransformFeedback'].includes(key))report.events.push({call:key,args:[...args]});return result;
 };}});
 return{gl,finish(){equal(live.size,0,'all GL objects deleted');for(const e of objects)equal(native['is'+e.kind](e.object),false,'actual deletion '+e.id);report.objects={created:objects.length,live:live.size};}};
}
function vectors(seed){let state=seed;const next=()=>{state^=state<<13;state^=state>>>17;state^=state<<5;return state>>>0;},color=()=>Array.from({length:4},()=>Math.fround((next()%127+1)/128));
 return Array.from({length:48},(_,i)=>({name:'bounded-'+i,position:[Math.fround((next()%191-95)/128),Math.fround((next()%191-95)/128),.125,1],a:color(),b:color(),condition:[i%2===0?-.5:.5,.25,.75,1],alpha:Math.fround((next()%7+1)/8),baseAlpha:Math.fround((next()%7+1)/8)}));
}
// Independent scalar equations: sign-bit selection of A/B, unchanged legacy
// copy, literal IMM31 and CONST45.x. No emitted GLSL or compiler IR is interpreted.
function expected(test,vector){if(test.kind==='legacy-imm')return[.25,.5,.75,1];if(test.kind==='legacy')return test.stage==='vertex'?vector.position:vector.a;if(test.kind==='raster')return[...vector.a.slice(0,3),vector.alpha];if(test.kind==='raster-deep')return[...vector.a.slice(0,3),vector.condition[0]<0?vector.baseAlpha:vector.alpha];return vector.condition[0]<0?vector.a:vector.b;}
function attributes(gl,program,metadata,inputs){const snapshots=[];for(const a of metadata.attributes){const location=gl.getAttribLocation(program,a.name);if(location<0)continue;gl.disableVertexAttribArray(location);gl.vertexAttrib4fv(location,new Float32Array(inputs[a.index]));const observed=[...gl.getVertexAttrib(location,gl.CURRENT_VERTEX_ATTRIB)].map(word);equal(observed,inputs[a.index].map(word),'physical attribute words');snapshots.push({index:a.index,location,words:observed});}return snapshots;}
function upload(gl,program,metadata,vector){const bank=Array(184).fill(0);bank[0]=word(vector.baseAlpha);bank[180]=word(vector.alpha);const records=[];for(const u of metadata.uniforms){const location=gl.getUniformLocation(program,u.name+'[0]');require(location,'bank is active');const index=gl.getUniformIndices(program,[u.name+'[0]'])[0],type=gl.getActiveUniforms(program,[index],gl.UNIFORM_TYPE)[0],count=gl.getActiveUniforms(program,[index],gl.UNIFORM_SIZE)[0];equal(type,gl.UNSIGNED_INT_VEC4,'raw bank reflection');equal(count,46,'highest CONST45 remains active');const checked=approve(metadata,bank,count);require(checked.ok,'separate bank domain guard');gl.uniform4uiv(location,new Uint32Array(checked.words));const observed=[];for(let i=0;i<count;i++)observed.push(...gl.getUniform(program,gl.getUniformLocation(program,u.name+`[${i}]`)));equal(observed,bank,'physical bank words');records.push({name:u.name,type,count,words:bank,observed,checked});}return records;}
function ownedFault(pair,test,fault){const result=clone(pair),stage=result[test.stage==='vertex'?'vertex':'fragment'];if(!fault)return{result,mutation:null};let expression,replacement;
 if(fault==='high-register'){expression=/float_temp\[511\]\./g;replacement='float_temp[510].';}
 else if(fault==='branch-join'){expression=/if \(raw_temp\[509\]\.x != 0u\)/g;replacement='if (raw_temp[509].x == 0u)';}
 else{expression=/raw_temp\[508\]\.x \+ 1u/g;replacement='raw_temp[508].x + 0u';}
 const matches=[...stage.glsl.matchAll(expression)].length;require(matches>0,'fault reaches targeted emitted dependency');const original=stage.glsl;stage.glsl=stage.glsl.replace(expression,replacement);return{result,mutation:{fault,matches,original,served:stage.glsl}};
}
async function vertexProbe(gl,test,pair,report,values,fault){const owned=ownedFault(pair,test,fault),built=createProgram(gl,owned.result.vertex,owned.result.fragment),program=built.program,buffers=[],vao=gl.createVertexArray(),feedback=gl.createTransformFeedback(),output=gl.createBuffer();require(vao&&feedback&&output,'vertex objects');buffers.push(output);
 const record={name:test.name,kind:test.kind,source:test.text,sourceSha256:await digest(test.text),originalPair:pair,mutation:owned.mutation,logs:built.logs,varyings:['gl_Position','vso_g0'],reflection:[],vectors:[]};report.vertices.push(record);
 try{gl.transformFeedbackVaryings(program,record.varyings,gl.INTERLEAVED_ATTRIBS);gl.linkProgram(program);require(gl.getProgramParameter(program,gl.LINK_STATUS),'bounded feedback link');for(let i=0;i<2;i++){const info=gl.getTransformFeedbackVarying(program,i);equal([info.name,info.type,info.size],[record.varyings[i],gl.FLOAT_VEC4,1],'feedback reflection');record.reflection.push({name:info.name,type:info.type,size:info.size});}
  gl.useProgram(program);gl.bindVertexArray(vao);record.systemBlocks=bindSystemBlocks(gl,program,pair.vertex.metadata,buffers);gl.bindTransformFeedback(gl.TRANSFORM_FEEDBACK,feedback);gl.bindBuffer(gl.TRANSFORM_FEEDBACK_BUFFER,output);gl.bufferData(gl.TRANSFORM_FEEDBACK_BUFFER,32,gl.DYNAMIC_READ);gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,output);gl.enable(gl.RASTERIZER_DISCARD);
  for(const vector of values){const wanted=[...vector.position,...expected(test,vector)].map(word),entry={vector,expectedWords:wanted,attributes:attributes(gl,program,pair.vertex.metadata,[vector.position,vector.a,vector.b,vector.condition]),uploads:upload(gl,program,pair.vertex.metadata,vector),checks:[]};record.vectors.push(entry);gl.beginTransformFeedback(gl.POINTS);gl.drawArrays(gl.POINTS,0,1);gl.endTransformFeedback();const raw=new Uint8Array(32);gl.getBufferSubData(gl.TRANSFORM_FEEDBACK_BUFFER,0,raw);equal(gl.getError(),gl.NO_ERROR,'physical bounded feedback');const actual=[...new Uint32Array(raw.buffer)];entry.observed=actual;entry.bytes=[...raw];entry.sha256=await digest(raw);
   for(let lane=0;lane<8;lane++){const check={lane,expected:wanted[lane],actual:actual[lane]};entry.checks.push(check);if(actual[lane]!==wanted[lane]){entry.failure=check;throw new Error(`independent bound word mismatch ${test.name}/${vector.name}/lane${lane}`);}}
  }
 }finally{gl.disable(gl.RASTERIZER_DISCARD);gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,null);gl.bindTransformFeedback(gl.TRANSFORM_FEEDBACK,null);gl.bindVertexArray(null);gl.useProgram(null);gl.deleteTransformFeedback(feedback);gl.deleteVertexArray(vao);for(const b of buffers)gl.deleteBuffer(b);gl.deleteProgram(program);}
}
async function fragmentProbe(gl,test,pair,report,values){const built=createProgram(gl,pair.vertex,pair.fragment),program=built.program,buffers=[],textures=[],vao=gl.createVertexArray(),fb=gl.createFramebuffer();require(vao&&fb,'fragment objects');const record={name:test.name,kind:test.kind,source:test.text,sourceSha256:await digest(test.text),originalPair:pair,logs:built.logs,draws:[]};report.fragments.push(record);
 try{gl.useProgram(program);gl.bindVertexArray(vao);record.systemBlocks=bindSystemBlocks(gl,program,pair.vertex.metadata,buffers);const positions=gl.createBuffer();require(positions,'mesh');buffers.push(positions);gl.bindBuffer(gl.ARRAY_BUFFER,positions);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,0,1,1,-1,0,1,-1,1,0,1,-1,1,0,1,1,-1,0,1,1,1,0,1]),gl.STATIC_DRAW);const at=gl.getAttribLocation(program,'in_0');require(at>=0,'mesh attribute');gl.enableVertexAttribArray(at);gl.vertexAttribPointer(at,4,gl.FLOAT,false,16,0);
  const target=texture2d(gl,WIDTH,WIDTH,null);textures.push(target);gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,target,0);equal(gl.checkFramebufferStatus(gl.FRAMEBUFFER),gl.FRAMEBUFFER_COMPLETE,'bounded framebuffer');for(const cap of [gl.DITHER,gl.BLEND,gl.DEPTH_TEST,gl.CULL_FACE,gl.SCISSOR_TEST,gl.STENCIL_TEST])gl.disable(cap);gl.viewport(0,0,WIDTH,WIDTH);
  for(const vector of values){const expectedBytes=expected(test,vector).map(x=>Math.floor(Math.min(1,Math.max(0,x))*255+.5)),entry={vector,expectedBytes,pixelBudget:1,attributes:attributes(gl,program,{attributes:pair.vertex.metadata.attributes.filter(a=>a.index!==0)},[vector.position,vector.a,vector.b,vector.condition]),uploads:upload(gl,program,pair.fragment.metadata,vector),checkedPixels:0};record.draws.push(entry);gl.clearColor(.1,.2,.3,.4);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawArrays(gl.TRIANGLES,0,6);const raw=new Uint8Array(WIDTH*WIDTH*4);gl.readPixels(0,0,WIDTH,WIDTH,gl.RGBA,gl.UNSIGNED_BYTE,raw);equal(gl.getError(),gl.NO_ERROR,'bounded physical pixel readback');entry.rgbaBytes=[...raw];entry.sha256=await digest(raw);for(let pixel=0;pixel<WIDTH*WIDTH;pixel++){const actual=[...raw.slice(pixel*4,pixel*4+4)];if(actual.some((v,c)=>Math.abs(v-expectedBytes[c])>1)){entry.failure={pixel,expected:expectedBytes,actual};throw new Error('independent bound pixel mismatch '+test.name);}entry.checkedPixels++;}
  }
 }finally{gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.bindVertexArray(null);gl.useProgram(null);gl.deleteFramebuffer(fb);gl.deleteVertexArray(vao);for(const t of textures)gl.deleteTexture(t);for(const b of buffers)gl.deleteBuffer(b);gl.deleteProgram(program);}
}
export async function runAcceptance({seed=0x2317509d,fault=null}={}){const report={schema:'virgl-compiler-bounds-gpu-v1',status:'running',guestExecution:false,seed,fault,envelope:LIMITS,cases:[],pairs:[],vertices:[],fragments:[],events:[]};window.__virglCompilerBoundsReport=report;equal(LIMITS,ENVELOPE,'independent frontend envelope');const canvas=document.querySelector('#gpu');canvas.width=canvas.height=WIDTH;const native=canvas.getContext('webgl2',{antialias:false,preserveDrawingBuffer:true,failIfMajorPerformanceCaveat:true});require(native instanceof WebGL2RenderingContext,'actual WebGL2');const debug=native.getExtension('WEBGL_debug_renderer_info');require(debug,'GPU identity');report.renderer={vendor:native.getParameter(debug.UNMASKED_VENDOR_WEBGL),renderer:native.getParameter(debug.UNMASKED_RENDERER_WEBGL),version:native.getParameter(native.VERSION)};require(!/swiftshader|llvmpipe|softpipe|software/i.test(report.renderer.renderer),'hardware GPU');const watched=monitor(native,report),gl=watched.gl;
 try{const bridge=await createVirglShaderBridge(),cases=getCases(),pairs=getPairs(cases),values=vectors(seed);
  for(const test of cases){const result=bridge.translate({stage:test.stage,text:test.text});equal(result.ok,test.ok,'literal bound admission '+test.name);report.cases.push({...test,result});}
  for(const p of pairs){const v=cases[p.vertex],f=cases[p.fragment],result=bridge.translatePair({vertexText:v.text,fragmentText:f.text});equal(result.ok,p.ok,p.name);report.pairs.push({...p,result});}
  for(let i=0;i<cases.length;i++){const test=cases[i];if(!test.ok||['partner','text'].includes(test.kind))continue;const p=report.pairs.find(p=>p.ok&&(test.stage==='vertex'?p.vertex===i:p.fragment===i));require(p,'actual compatible pair');const selectedFault=fault&&(fault==='high-register'?test.name==='high-vertex':fault==='branch-join'?test.name==='deep-vertex':test.name==='combined-vertex')?fault:null;if(test.stage==='vertex')await vertexProbe(gl,test,p.result,report,values,selectedFault);else await fragmentProbe(gl,test,p.result,report,values);}
  require(!fault,'physical source fault must fail');report.checkedWords=report.vertices.reduce((n,v)=>n+v.vectors.reduce((n,x)=>n+x.checks.length,0),0);report.checkedPixels=report.fragments.reduce((n,f)=>n+f.draws.reduce((n,x)=>n+x.checkedPixels,0),0);report.status='passed';document.querySelector('#status').textContent=`TEMP511 · IMM31 · 768 instructions · depth16 · ${report.checkedWords} exact words · ${report.checkedPixels} pixels`;document.querySelector('#renderer').textContent=report.renderer.renderer;
 }catch(error){report.status='failed';report.failure={message:error.message};throw error;}finally{watched.finish();equal(gl.getError(),gl.NO_ERROR,'final bounded GL errors');}return report;
}
