#!/usr/bin/env node
import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {browserDocument,browserOptions,runVirglBrowser} from '../lib/virgl-browser-runner.mjs';
const options=browserOptions(['--fault','--fault-artifacts','--seed']),repo=fs.realpathSync(path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..')),fault=options.fault??null;
assert.ok(fault===null||['drop-component','missing-guard','unapproved-decode'].includes(fault));let faultWasm=null,stateModule=null,faultFiles=[];
if(fault){const manifest=JSON.parse(fs.readFileSync(path.join(options['fault-artifacts'],'manifest.json'))),record=manifest.modes[fault];for(const item of record.served){const absolute=fs.realpathSync(path.join(options['fault-artifacts'],item.path)),relative=path.relative(repo,absolute);assert.ok(relative&&!relative.startsWith('..'+path.sep)&&!path.isAbsolute(relative));faultFiles.push(relative);}if(record.wasm)faultWasm='/'+path.relative(repo,path.resolve(options['fault-artifacts'],record.wasm.path)).split(path.sep).join('/');if(record.stateModule)stateModule='/'+path.relative(repo,path.resolve(options['fault-artifacts'],record.stateModule)).split(path.sep).join('/');}
const runtime=fs.readdirSync(path.join(repo,'renderer/virgl-command')).filter(x=>x.endsWith('.mjs')).map(x=>'renderer/virgl-command/'+x);
runtime.push('renderer/virgl-command/tests/raster-bank.mjs','tools/virgl-raster-bank/oracle.mjs','tools/virgl-radial-domain/oracle.mjs','renderer/virgl-shader/tests/raster-bank-cases.json','renderer/virgl-shader/tests/precise-word-cases.json');
const fixture=JSON.parse(fs.readFileSync(path.join(repo,'renderer/virgl-shader/tests/raster-bank-cases.json')));runtime.push(...fixture.kernels.filter(k=>k.kind==='original').map(k=>k.originalPath),...faultFiles);
const pinnedFiles=[...new Set(runtime)].map(filename=>{const bytes=fs.readFileSync(path.join(repo,filename));return{path:filename,size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};});
await runVirglBrowser({options,task:'E6-T12f4b',serializedAcceptance:true,boundary:'Guarded exact bank copies in the isolated shared renderer',reportFields:{currentGuest3dAdvertisement:false},modulePath:'/renderer/virgl-command/tests/raster-bank.mjs',windowReportKey:'__virglRasterBankReport',browserArguments:{fault,faultWasm,stateModule,seed:Number(options.seed??0x31db9275)>>>0},servedFiles:runtime,pinnedFiles,coveragePaths:['renderer/virgl-command/tests/raster-bank.mjs','tools/virgl-raster-bank/oracle.mjs','renderer/virgl-command/state.mjs','renderer/virgl-command/constant-domain.mjs'],html:browserDocument({title:'Copied bank raster proof',heading:'Owned bank generation and bounded output authority',description:'Untouched gradients, exact flat words and before-effect domain rejection'}),validate(r){assert.equal(r.status,'passed');assert.equal(r.rigs.length,40);assert.equal(r.drawCount,192);assert.equal(r.checkedWords,400);assert.equal(r.checkedPixels,192*4096);assert.ok(r.rigs.every(x=>x.glObjects.live===0&&x.oracleStops.length===0));},successMessage:r=>`${r.checkedWords} exact copied words; ${r.checkedPixels} checked pixels.`});
