#!/usr/bin/env node
import assert from 'node:assert/strict';import fs from 'node:fs';
import {createVirglShaderBridge} from '../../renderer/virgl-shader/index.mjs';
import {parseConstantDomain,checkRasterBank,rasterBinary32Word} from '../../renderer/virgl-command/constant-domain.mjs';
import {proof} from './oracle.mjs';
const fixture=JSON.parse(fs.readFileSync(new URL('../../renderer/virgl-shader/tests/raster-bank-cases.json',import.meta.url))),bridge=await createVirglShaderBridge({wasmBinary:fs.readFileSync(new URL('../../renderer/virgl-shader/build/wasm/virgl-shader.wasm',import.meta.url))});
const clone=value=>JSON.parse(JSON.stringify(value)),report={schema:'raster-bank-consumer-v1',status:'running',domain:[],contracts:[],banks:[],hostile:[]};
for(const entry of proof().cases){assert.equal(rasterBinary32Word(entry.word),entry.admitted);report.domain.push(entry);}
for(const input of fixture.cases.filter(e=>e.ok&&e.expected.constantRasterDomains)){
 const result=bridge.translate({stage:input.stage,text:input.text});assert.equal(result.ok,true,input.name);
 const checked=parseConstantDomain(result.metadata,input.stage);assert.equal(checked.ok,true,input.name);
 assert.deepEqual(checked.rasterDomain,input.expected.constantRasterDomains[0]);assert.equal(Object.isFrozen(checked.rasterDomain.components),true);
 const erased=[];for(const key of ['rasterBaseProfile','constantRasterDomains','constantDomains','constantAccesses','constantConstraints','constantRadialDomains','preciseWordContract'])if(Object.hasOwn(result.metadata,key)){const bad=clone(result.metadata);delete bad[key];assert.equal(parseConstantDomain(bad,input.stage).ok,false,key+'/'+input.name);erased.push(key);}
 for(const [name,mutate]of [['base-downgrade',m=>m.rasterBaseProfile='virgl-webgl2-raw-bits-v1'],['recursive-wrapper',m=>m.rasterBaseProfile=m.profile],['legacy-raster',m=>m.profile=m.rasterBaseProfile],['extra',m=>m.extra=1]]){const bad=clone(result.metadata);mutate(bad);assert.equal(parseConstantDomain(bad,input.stage).ok,false,name);}
 report.contracts.push({name:input.name,stage:input.stage,rasterDomain:checked.rasterDomain,erased});
 const words=Array(checked.rasterDomain.count*4).fill(0);if(checked.constraint)words[36]=2;if(checked.radialDomain)words[16]=0x3f800000;
 const approve=values=>checkRasterBank(values,checked.rasterDomain,Boolean(checked.constraint),Boolean(checked.radialDomain));
 const owned=approve(words);assert.equal(owned.ok,true,input.name);assert.notEqual(owned.words,words);assert.deepEqual(owned.words,words);assert.equal(Object.isFrozen(owned.words),true);words[0]=0x3f800000;assert.equal(owned.words[0],0);
 const first=checked.rasterDomain.components[0],lane=Math.clz32(first.mask&-first.mask)^31,at=first.register*4+lane;
 for(const word of[0,0x80000000,0x007fffff,0x807fffff,0x00800000,0x80800000,0x00800001,0x80800001,0x7f7fffff,0xff7fffff,1,0x80000001,0x7f800000,0xff800000,0x7fa00123,0xffc00123]){const bank=owned.words.slice();bank[at]=word;const actual=approve(bank),wanted=proof().cases.find(e=>e.word===word)?.admitted??((word&0x7fffffff)===0||((word&0x7f800000)!==0&&(word&0x7f800000)!==0x7f800000));assert.equal(actual.ok,wanted,input.name+'/'+word);if(!wanted)assert.equal(actual.error.code,(word&0x7f800000)===0x7f800000?'constant-domain-error':'constant-raster-domain-error');report.banks.push({name:input.name,register:first.register,lane,word,accepted:actual.ok,error:actual.error?.code??null});}
 if(checked.constraint){for(const count of[0,1,2,18,19,0x3f800000,0x80000000,0x80000001,0xbf800000,0xffffffff]){const bank=owned.words.slice();bank[36]=count;const actual=approve(bank);assert.equal(actual.ok,(count>=0x80000000||count<=18)&&Number.isFinite((()=>{const b=new ArrayBuffer(4),v=new DataView(b);v.setUint32(0,count,true);return v.getFloat32(0,true);})()));report.banks.push({name:input.name,count,accepted:actual.ok,error:actual.error?.code??null});}const bad=clone(result.metadata);bad.constantRasterDomains[0].components.unshift({register:9,mask:1});assert.equal(parseConstantDomain(bad,input.stage).ok,false);}
 if(checked.radialDomain){const bank=owned.words.slice();bank[16]=0;const actual=approve(bank);assert.equal(actual.ok,false);assert.equal(actual.error.code,'constant-radial-domain-error');report.banks.push({name:input.name,coefficient:0,accepted:false,error:actual.error.code});}
 for(const component of checked.rasterDomain.components)for(let lane=0;lane<4;lane++)if(component.mask&(1<<lane)){const bank=owned.words.slice();bank[component.register*4+lane]=1;const actual=approve(bank);assert.equal(actual.ok,false,'every copied component');assert.equal(actual.error.code,'constant-raster-domain-error');report.banks.push({name:input.name,register:component.register,lane,word:1,accepted:false,error:actual.error.code,coverage:'every copied component'});}
 const bank=owned.words.slice();bank.push(0x7fc12345,0,0,0);assert.equal(approve(bank).ok,bank.length<=184,'full prefix and maximum bank extent checked');
 for(const [name,bad]of [['short',owned.words.slice(0,-1)],['hole',(()=>{const b=owned.words.slice();delete b[0];return b;})()],['boolean',(()=>{const b=owned.words.slice();b[0]=true;return b;})()],['fraction',(()=>{const b=owned.words.slice();b[0]=.5;return b;})()]]){assert.equal(approve(bad).ok,false,name);report.hostile.push({name:input.name,bank:name});}
}
const domain=fixture.cases.find(e=>e.name==='copy-xyzw-direct-vertex').expected.constantRasterDomains[0],words=Array(24).fill(0);let invoked=0;
for(const [name,mutate]of [['zero-mask',d=>d.components[0].mask=0],['wide-mask',d=>d.components[0].mask=16],['boolean-mask',d=>d.components[0].mask=true],['duplicate',d=>d.components.push({...d.components[0]})],['unsorted',d=>d.components=[{register:1,mask:1},{register:0,mask:1}]],['absent',d=>d.components=[]],['register-extent',d=>d.components[0].register=6],['count-fraction',d=>d.count=6.5],['wrong-stage',d=>d.stage='fragment'],['unknown',d=>d.extra=1],['accessor',d=>Object.defineProperty(d.components[0],'mask',{get(){invoked++;return 15;},enumerable:true})]]){const bad=clone(domain);mutate(bad);assert.equal(checkRasterBank(words,bad).ok,false,name);report.hostile.push({domain:name});}
const bank=words.slice();Object.defineProperty(bank,'0',{get(){invoked++;return 0;},enumerable:true});assert.equal(checkRasterBank(bank,domain).ok,false);assert.equal(invoked,0,'hostile accessors never invoked');
report.hostile.push({bank:'accessor',invoked});report.status='passed';process.stdout.write(JSON.stringify(report)+'\n');
