// Physical GL sampling/attachment pixels are separate from inverse guest bytes.
import { computeTransferLayout, createResourceStore, createWebGL2TransferBackend } from '../resources.mjs';
import { decodeSubmission } from '../decoder.mjs';
import { createVirglStateRenderer, createVirglDrawRenderer } from '../state.mjs';
import { createVirglShaderBridge } from '../../virgl-shader/index.mjs';

const meta=(format,bind=10,id=1,width=3,height=2)=>({id,target:2,format,bind,width,height,depth:1,arraySize:1,lastLevel:0,nrSamples:0,flags:0});
const region=(width=3,height=2)=>({x:0,y:0,z:0,width,height,depth:1});
const transfer=(id,direction=1)=>({opcode:43,fields:{resourceHandle:id,level:0,usage:0,stride:17,layerStride:34,box:region(),dataOffset:5,direction}});
const copied=(id,staging,flags)=>({opcode:45,fields:{resourceHandle:id,level:0,usage:0,stride:17,layerStride:34,box:region(),stagingResourceHandle:staging,stagingOffset:5,flags}});
// Literal guest encodings and independent native RGBA channels. In particular,
// the packed inputs are NOT generated by a copy of the runtime's bit shuffle.
const INPUTS={
  2:{bytes:[37,5,231,0, 91,177,23,57, 213,29,47,255, 1,254,17,11, 129,3,217,201, 7,113,199,0],
     rgba:[[231,5,37,255],[23,177,91,255],[47,29,213,255],[17,254,1,255],[217,3,129,255],[199,113,7,255]]},
  67:{bytes:[37,5,231,12, 91,177,23,99, 213,29,47,0, 1,254,17,255, 129,3,217,201, 7,113,199,17],
      rgba:[[37,5,231,12],[91,177,23,99],[213,29,47,0],[1,254,17,255],[129,3,217,201],[7,113,199,17]]},
  233:{bytes:[254,7,20,0, 85,5,40,192, 3,68,208,191, 0,252,255,127, 255,7,240,31, 255,252,27,193],
       rgba:[[1,257,1022,3],[2,513,341,3],[1021,17,3,3],[1023,1023,0,3],[511,1,1023,3],[17,767,255,3]]},
};
function checks(){
  const rows=[];
  const equal=(actual,expected,label)=>{
    const held=JSON.stringify(actual)===JSON.stringify(expected);
    rows.push({prediction:label,expected,observed:actual,held});
    if(!held)throw new Error(`${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
  };
  const ok=(r,label)=>{equal(r?.ok,true,`${label} (${r?.error?.code??''}: ${r?.error?.message??''})`);return r;};
  const bad=(r,label,code)=>{equal(r?.ok,false,label+' rejects');if(code)equal(r.error.code,code,label+' code');return r;};
  return{equal,ok,bad,rows};
}
function packet(op,type,words){const b=new Uint8Array(4+words.length*4),v=new DataView(b.buffer);v.setUint32(0,op|(type<<8)|(words.length<<16),true);words.forEach((w,i)=>v.setUint32(4+i*4,w,true));return b;}
function clear(alpha=0){return packet(7,0,[4,0,0,0,alpha?0x3f800000:0,0,0x3ff00000,0]);}
function padded(bytes){const b=new Uint8Array(41).fill(0xa7);b.set(bytes.slice(0,12),5);b.set(bytes.slice(12),22);return b;}
function readPadded(store,id,c){return [...c.ok(store.readBacking(id,0,24),'bounded backing prefix').bytes,...c.ok(store.readBacking(id,24,17),'bounded backing suffix').bytes];}
function writePadded(store,id,bytes,c){c.ok(store.writeBacking(id,0,bytes.slice(0,24)),'bounded backing prefix write');c.ok(store.writeBacking(id,24,bytes.slice(24)),'bounded backing suffix write');}
function canonical(format){const b=Uint8Array.from(INPUTS[format].bytes);if(format===2)for(let i=3;i<b.length;i+=4)b[i]=255;else if(format===233)for(let i=3;i<b.length;i+=4)b[i]|=192;return b;}
async function sha(b){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(v=>v.toString(16).padStart(2,'0')).join('');}
function cleanup(store,c,label){c.ok(store.dispose(),label+' dispose');for(const[k,v]of Object.entries(c.ok(store.inspect(),label+' inspect').budgets))c.equal(v,0,label+' final '+k);}

export function runNativeColorAcceptance(){
  const c=checks(),cases=[];
  const backend={maxTextureSize:16384,allocate:m=>({kind:'texture',metadata:m}),destroy(){},upload(){},readback:(s,m,l)=>new Uint8Array(l.tightBytes),dispose(){}};
  for(const format of [2,67,233])for(const bind of [2,8,10,10|262144,10|1048576,1310730]){
    const{store,bindings}=c.ok(createResourceStore({backend}),'native color store');c.ok(store.createContext(1),'native context');
    const created=c.ok(store.createResource(meta(format,bind)),'admitted color metadata').resource;
    c.equal(created.byteLength,24,'conservative four-byte logical allocation');
    c.ok(store.attachContext(1,1),'native attachment');
    for(const[role,allowed]of [['view',Boolean(bind&8)],['surface',Boolean(bind&2)],['vertex',false],['index',false],['readback',true]]){
      const r=store.retainStorage(1,1,role);
      if(allowed){const lease=c.ok(r,'allowed '+role).lease;c.equal(c.ok(bindings.resolve(lease),'resolved exact format').metadata.format,format,'lease preserves format');c.ok(store.releaseStorage(lease),'release role');}
      else c.bad(r,'forbidden '+role,'unsupported-resource');
    }
    if(format!==67||!(bind&2))c.bad(bindings.retainScanout(1,created.generation),'scanout profile remains separate','unsupported-resource');
    else c.ok(store.releaseStorage(c.ok(bindings.retainScanout(1,created.generation),'existing RGBA render scanout').lease),'release scanout');
    cleanup(store,c,'native color');cases.push({format,bind});
  }
  for(const changed of [{format:1},{format:134},{format:16},{format:68},{bind:0},{bind:1},{bind:16},{bind:64},{bind:10|4194304},{flags:1},{target:0},{target:1},{lastLevel:1},{arraySize:2},{nrSamples:4}]){
    const{store}=c.ok(createResourceStore({backend}),'invalid color store');c.bad(store.createResource({...meta(233),...changed}),'unsupported color request','unsupported-resource');cleanup(store,c,'invalid color');
  }
  for(const format of [2,67,233]){
    const fields=transfer(1).fields;
    const layout=c.ok(computeTransferLayout(meta(format),fields,34),'odd stride exact fit').layout;
    c.equal([layout.rowBytes,layout.rowStride,layout.tightBytes,layout.requiredEnd],[12,17,24,34],'guest strides stay four-byte pixels');
    c.bad(computeTransferLayout(meta(format),fields,33),'short odd-row backing','out-of-bounds');
  }
  return{status:'passed',boundary:'Metadata/role/layout checks only; this memory backend is not GPU evidence.',cases,assertions:c.rows};
}

function rig(gl,c,{draw=false,bridge,limits}={}){
  const allocations=new Map(),calls=[];
  const traced=new Proxy(gl,{get(target,key){const value=Reflect.get(target,key,target);if(typeof value!=='function')return value;return(...args)=>{
    if(key==='texStorage2D')calls.push({op:key,internalFormat:args[2],width:args[3],height:args[4]});
    if(key==='texSubImage2D')calls.push({op:key,format:args[6],type:args[7],elements:args[8].length,bytes:args[8].byteLength,first:[...args[8].slice(0,12)]});
    if(key==='readPixels')calls.push({op:key,format:args[4],type:args[5],pbo:typeof args[6]==='number',width:args[2],height:args[3]});
    if(key==='drawElements')calls.push({op:key,count:args[1],colorMask:[...target.getParameter(target.COLOR_WRITEMASK)]});
    return value.apply(target,args);
  };}});
  const native=c.ok(createWebGL2TransferBackend(traced),'real color backend').backend;
  const backend={...native,allocate(m){const s=native.allocate(m);allocations.set(m.id,s);return s;}};
  const capabilities=c.ok(createResourceStore({backend,...(limits?{limits}:{})}),'real color store');
  const shaderBridge=bridge??{translate(){throw new Error('state-only color proof must not translate a shader');}};
  const renderer=c.ok((draw?createVirglDrawRenderer:createVirglStateRenderer)({gl:traced,resources:capabilities.store,bindings:capabilities.bindings,shaderBridge}),'real color renderer').renderer;
  return{...capabilities,renderer,allocations,calls,backend};
}
function readNative(gl,texture,format,width,height){
  const fb=gl.createFramebuffer();gl.bindFramebuffer(gl.READ_FRAMEBUFFER,fb);
  try{
    gl.framebufferTexture2D(gl.READ_FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texture,0);gl.readBuffer(gl.COLOR_ATTACHMENT0);
    if(gl.checkFramebufferStatus(gl.READ_FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw new Error('independent physical framebuffer incomplete');
    const bits=[gl.FRAMEBUFFER_ATTACHMENT_RED_SIZE,gl.FRAMEBUFFER_ATTACHMENT_GREEN_SIZE,gl.FRAMEBUFFER_ATTACHMENT_BLUE_SIZE,gl.FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE].map(p=>gl.getFramebufferAttachmentParameter(gl.READ_FRAMEBUFFER,gl.COLOR_ATTACHMENT0,p));
    const data=format===233?new Uint32Array(width*height):new Uint8Array(width*height*4);
    gl.bindBuffer(gl.PIXEL_PACK_BUFFER,null);gl.pixelStorei(gl.PACK_ALIGNMENT,1);gl.pixelStorei(gl.PACK_ROW_LENGTH,0);gl.pixelStorei(gl.PACK_SKIP_PIXELS,0);gl.pixelStorei(gl.PACK_SKIP_ROWS,0);
    gl.readPixels(0,0,width,height,gl.RGBA,format===233?gl.UNSIGNED_INT_2_10_10_10_REV:gl.UNSIGNED_BYTE,data);
    const rgba=[];
    for(let i=0;i<width*height;i++)rgba.push(format===233?[data[i]&1023,(data[i]>>>10)&1023,(data[i]>>>20)&1023,data[i]>>>30]:[...data.slice(i*4,i*4+4)]);
    return{bits,rgba,data};
  }finally{gl.framebufferTexture2D(gl.READ_FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,null,0);gl.deleteFramebuffer(fb);}
}
function program(gl,fragment){
  const shaders=[];const p=gl.createProgram();
  for(const[type,text]of [[gl.VERTEX_SHADER,'#version 300 es\nvoid main(){vec2 p=vec2(float((gl_VertexID<<1)&2),float(gl_VertexID&2));gl_Position=vec4(p*2.0-1.0,0,1);}'],[gl.FRAGMENT_SHADER,'#version 300 es\nprecision highp float;'+fragment]]){
    const s=gl.createShader(type);shaders.push(s);gl.shaderSource(s,text);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));gl.attachShader(p,s);
  }
  gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));
  return{p,dispose(){gl.deleteProgram(p);shaders.forEach(s=>gl.deleteShader(s));}};
}
function sampleNative(gl,texture,format,width=3,height=2){
  const output=gl.createTexture(),fb=gl.createFramebuffer(),vao=gl.createVertexArray();
  const shader=program(gl,'uniform sampler2D src;out vec4 color;void main(){color=texelFetch(src,ivec2(gl_FragCoord.xy),0);}');
  try{
    gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,output);gl.texStorage2D(gl.TEXTURE_2D,1,format===233?gl.RGB10_A2:gl.RGBA8,width,height);
    gl.bindFramebuffer(gl.DRAW_FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.DRAW_FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,output,0);gl.drawBuffers([gl.COLOR_ATTACHMENT0]);
    gl.bindVertexArray(vao);gl.viewport(0,0,width,height);gl.useProgram(shader.p);
    for(const cap of [gl.BLEND,gl.DEPTH_TEST,gl.STENCIL_TEST,gl.SCISSOR_TEST,gl.CULL_FACE,gl.DITHER,gl.RASTERIZER_DISCARD])gl.disable(cap);
    gl.colorMask(true,true,true,true);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);gl.bindSampler(0,null);gl.uniform1i(gl.getUniformLocation(shader.p,'src'),0);gl.drawArrays(gl.TRIANGLES,0,3);
    return readNative(gl,output,format===233?233:67,width,height);
  }finally{shader.dispose();gl.deleteVertexArray(vao);gl.deleteFramebuffer(fb);gl.deleteTexture(output);}
}
async function awaitRead(access,ticket,c,delay=0){
  for(let i=0;i<1000;i++){
    await new Promise(resolve=>setTimeout(resolve,delay));
    const polled=c.ok(access.poll(ticket),'later-task staged read poll');
    if(polled.status==='ready')return polled.bytes;
    c.equal(polled.status,'pending','bounded fence poll');
  }
  throw new Error('bounded color readback did not signal');
}
async function rows(gl,format,c){
  const{store,bindings,asyncAccess,renderer,allocations,calls}=rig(gl,c,{limits:{resourceBytes:64,cpuBytes:65,gpuBytes:48,scratchBytes:24}});
  c.ok(store.createContext(1),'row context');c.ok(store.createResource(meta(format)),'row texture');c.ok(store.attachContext(1,1),'row attach');
  const initial=readNative(gl,allocations.get(1).texture,format,3,2);
  c.equal(initial.bits,format===2?[8,8,8,0]:format===233?[10,10,10,2]:[8,8,8,8],'actual native component bits');
  c.equal(initial.rgba.map(p=>p[3]),Array(6).fill(format===233?3:format===2?255:0),'initial destination alpha');
  const input=padded(INPUTS[format].bytes);c.ok(store.attachBacking(1,[input.slice(0,3),input.slice(3,19),input.slice(19)]),'split odd backing');input.fill(0);
  const ticket=c.ok(store.prepareTransfer(1,transfer(1)),'owned sync upload').ticket;
  c.equal(c.ok(store.inspect(),'pending budgets').budgets.scratchBytes,24,'one dense conversion scratch reservation');
  c.ok(store.executeTransfer(ticket),'sync conversion upload');
  c.equal(readPadded(store,1,c),[...padded(INPUTS[format].bytes)],'conversion cannot mutate guest backing');
  const sampled=sampleNative(gl,allocations.get(1).texture,format);
  c.equal(sampled.rgba,INPUTS[format].rgba,'physical sampled RGBA '+format+' keeps channels/precision/alpha/origin');
  const lease=c.ok(store.retainStorage(1,1,'view'),'read exact storage').lease;
  c.equal([...c.ok(store.readStorage(lease),'sync inverse readback').bytes],[...canonical(format)],'sync inverse guest bytes '+format);
  const poison=new Uint8Array(41).fill(0xa7);writePadded(store,1,poison,c);
  c.ok(store.executeTransfer(c.ok(store.prepareTransfer(1,transfer(1,2)),'sync strided readback').ticket),'sync scatter');
  c.equal(readPadded(store,1,c),[...padded(canonical(format))],'inverse readback preserves odd padding '+format);
  const asyncUpload=c.ok(asyncAccess.prepareTransfer(1,transfer(1)),'prepare async upload').ticket;
  const owned=Uint8Array.from(INPUTS[format].bytes);c.ok(asyncAccess.provideInput(asyncUpload,owned),'clone dense async input');owned.fill(0);c.ok(asyncAccess.upload(asyncUpload),'async upload');c.ok(asyncAccess.release(asyncUpload),'release upload');
  for(const delay of [0,1,3]){
    const read=c.ok(asyncAccess.beginStorageRead(lease,region()),'real async PBO read').ticket;
    const budget=c.ok(store.inspect(),'PBO budgets').budgets;
    c.equal([budget.gpuBytes,budget.scratchBytes,budget.cpuBytes],[48,24,65],'PBO and CPU conversion charged at exact limits');
    c.equal([...await awaitRead(asyncAccess,read,c,delay)],[...canonical(format)],'async inverse guest bytes '+format+' schedule '+delay);
    c.ok(asyncAccess.release(read),'release native staging');
    c.equal([c.ok(store.inspect(),'released PBO').budgets.gpuBytes,c.ok(store.inspect(),'released scratch').budgets.scratchBytes],[24,0],'async reservations released once');
  }
  // A stale lease rejects before collecting into CPU scratch.
  const stale=c.ok(asyncAccess.beginStorageRead(lease,region()),'stale read start').ticket;c.ok(store.releaseStorage(lease),'revoke lease');
  c.bad(asyncAccess.poll(stale),'revoked lease cannot collect','stale-storage');c.ok(asyncAccess.release(stale),'release stale PBO');
  c.ok(renderer.dispose(),'row state dispose');cleanup(store,c,'row resource');c.equal(gl.getError(),gl.NO_ERROR,'row GL errors');
  return{format,physicalRgba:sampled.rgba,componentBits:initial.bits,sampledSha256:await sha(new Uint8Array(sampled.data.buffer)),calls};
}

async function copyCases(gl,format,c){
  const r=rig(gl,c,{limits:{resourceBytes:64,cpuBytes:66,gpuBytes:48,scratchBytes:24}}),{store,asyncAccess,renderer,allocations}=r;
  c.ok(store.createContext(1),'copy context');c.ok(store.createResource(meta(format)),'copy texture');c.ok(store.attachContext(1,1),'copy primary attach');
  c.ok(store.attachBacking(1,[new Uint8Array([77])]),'copy read primary backing is presence only');
  c.ok(store.createResource({id:2,target:0,format:64,bind:524288,width:41,height:1,depth:1,arraySize:1,lastLevel:0,nrSamples:0,flags:0}),'copy staging metadata');c.ok(store.attachContext(1,2),'copy staging attach');
  const source=padded(INPUTS[format].bytes);c.ok(store.attachBacking(2,[source.slice(0,7),source.slice(7,24),source.slice(24)]),'copy split staging backing');source.fill(0);
  c.equal(r.calls.filter(x=>x.op==='texStorage2D').length,1,'staging allocates no additional GPU image');
  c.ok(store.executeTransfer(c.ok(store.prepareTransfer(1,copied(1,2,1)),'sync copy upload prepare').ticket),'sync copy upload');
  c.equal(sampleNative(gl,allocations.get(1).texture,format).rgba,INPUTS[format].rgba,'copy upload physical pixels '+format);
  writePadded(store,2,new Uint8Array(41).fill(0xa7),c);
  c.ok(store.executeTransfer(c.ok(store.prepareTransfer(1,copied(1,2,3)),'sync copy inverse prepare').ticket),'sync copy inverse scatter');
  c.equal(readPadded(store,2,c),[...padded(canonical(format))],'copy inverse preserves staging padding '+format);
  c.equal([...c.ok(store.readBacking(1,0,1),'copy primary read').bytes],[77],'copy readback never writes primary backing');
  const upload=c.ok(asyncAccess.prepareTransfer(1,copied(1,2,1)),'async copy upload prepare');c.equal(upload.resource.id,2,'async upload names staging backing');
  const owned=Uint8Array.from(INPUTS[format].bytes);c.ok(asyncAccess.provideInput(upload.ticket,owned),'async copy owned input');owned.fill(0);c.ok(asyncAccess.upload(upload.ticket),'async copy upload');c.ok(asyncAccess.release(upload.ticket),'async copy release');
  writePadded(store,2,new Uint8Array(41).fill(0xa7),c);
  const read=c.ok(asyncAccess.prepareTransfer(1,copied(1,2,3)),'async copy read prepare');c.equal([read.resource.id,read.layout.offset,read.layout.rowStride],[2,5,17],'async read describes exact staging scatter');
  c.ok(asyncAccess.beginTransferRead(read.ticket),'async copy actual PBO issue');
  const dense=await awaitRead(asyncAccess,read.ticket,c,2);c.equal([...dense],[...canonical(format)],'async copy inverse guest bytes '+format);
  c.ok(asyncAccess.release(read.ticket),'async copy read release');
  c.equal(readPadded(store,2,c),Array(41).fill(0xa7),'async output never writes private backing before external DMA');
  const external=new Uint8Array(41).fill(0xa7);external.set(dense.subarray(0,12),read.layout.offset);external.set(dense.subarray(12),read.layout.offset+read.layout.rowStride);
  c.equal([...external],[...padded(canonical(format))],'caller scatter leaves odd padding untouched '+format);
  c.ok(renderer.dispose(),'copy renderer dispose');cleanup(store,c,'copy resources');c.equal(gl.getError(),gl.NO_ERROR,'copy GL errors');return{format,calls:r.calls};
}

async function generationCases(gl,c){
  const reports=[];
  for(const[oldFormat,newFormat]of [[2,233],[233,2],[67,233]]){
    const r=rig(gl,c,{limits:{resourceBytes:64,cpuBytes:65,gpuBytes:72,scratchBytes:48}}),{store,bindings,asyncAccess,renderer,allocations}=r;
    c.ok(store.createContext(1),'reuse context');const old=c.ok(store.createResource(meta(oldFormat)),'old generation').resource;c.ok(store.attachContext(1,1),'old attach');c.ok(store.attachBacking(1,[padded(INPUTS[oldFormat].bytes)]),'old backing');
    c.ok(store.executeTransfer(c.ok(store.prepareTransfer(1,transfer(1)),'old upload prepare').ticket),'old upload');
    const lease=c.ok(store.retainStorage(1,1,'view'),'old lease').lease,read=c.ok(asyncAccess.beginStorageRead(lease,region()),'old PBO snapshot').ticket;
    c.ok(store.unref(1),'remove old public ID');const fresh=c.ok(store.createResource(meta(newFormat)),'same ID different format').resource;c.ok(store.attachContext(1,1),'fresh attach');
    c.equal(fresh.generation>old.generation,true,'resource generation increases');c.equal(c.ok(bindings.resolve(lease),'old lease still resolves').metadata.format,oldFormat,'lease cannot reinterpret format after ID reuse');
    c.equal(c.ok(store.inspect(),'retained GPU accounting').budgets.gpuBytes,72,'both generations and PBO count against GPU budget');
    c.equal([...await awaitRead(asyncAccess,read,c,1)],[...canonical(oldFormat)],'PBO collect uses retained old format '+oldFormat+' despite new '+newFormat);
    c.ok(asyncAccess.release(read),'old read release');c.ok(store.releaseStorage(lease),'old storage release');
    c.equal(c.ok(store.inspect(),'old release accounting').budgets.gpuBytes,24,'old generation collected exactly once');
    c.ok(store.attachBacking(1,[padded(INPUTS[newFormat].bytes)]),'fresh backing');c.ok(store.executeTransfer(c.ok(store.prepareTransfer(1,transfer(1)),'fresh upload prepare').ticket),'fresh upload');
    c.equal(sampleNative(gl,allocations.get(1).texture,newFormat).rgba,INPUTS[newFormat].rgba,'new generation physical channels');
    c.ok(renderer.dispose(),'reuse state disposal');cleanup(store,c,'reuse resources');c.equal(gl.getError(),gl.NO_ERROR,'reuse GL errors');reports.push({oldFormat,newFormat,oldGeneration:old.generation,newGeneration:fresh.generation,calls:r.calls});
  }
  return reports;
}

async function budgetCases(gl,c){
  const reports=[];
  for(const format of [2,233])for(const limits of [{gpuBytes:47},{cpuBytes:64},{scratchBytes:23}]){
    const r=rig(gl,c,{limits}),{store,asyncAccess,renderer}=r;c.ok(store.createContext(1),'pressure context');c.ok(store.createResource(meta(format)),'pressure texture');c.ok(store.attachContext(1,1),'pressure attach');c.ok(store.attachBacking(1,[padded(INPUTS[format].bytes)]),'pressure backing');
    const lease=c.ok(store.retainStorage(1,1,'readback'),'pressure lease').lease;
    const before=c.ok(store.inspect(),'pressure before').budgets;c.bad(asyncAccess.beginStorageRead(lease,region()),'one-byte-short '+Object.keys(limits)[0],'limit-exceeded');
    c.equal(c.ok(store.inspect(),'pressure rollback').budgets,before,'failed PBO preparation releases all reservations');c.equal(r.calls.filter(x=>x.op==='readPixels').length,0,'pressure rejects before GL read');
    c.ok(store.releaseStorage(lease),'pressure lease release');c.ok(renderer.dispose(),'pressure state dispose');cleanup(store,c,'pressure resources');c.equal(gl.getError(),gl.NO_ERROR,'pressure GL errors');reports.push({format,limits});
  }
  // A trusted-host allocation failure is injected without introducing GL errors.
  // Real texture creation/deletion still runs; failed storage never publishes.
  let fail=true,deleted=0;
  const fault=new Proxy(gl,{get(t,k){if(k==='checkFramebufferStatus')return target=>fail&&target===t.DRAW_FRAMEBUFFER?t.FRAMEBUFFER_INCOMPLETE_ATTACHMENT:t.checkFramebufferStatus(target);if(k==='deleteTexture')return texture=>{deleted++;t.deleteTexture(texture);};const v=Reflect.get(t,k,t);return typeof v==='function'?v.bind(t):v;}});
  const r=rig(fault,c),{store,renderer}=r;gl.colorMask(false,true,false,false);gl.disable(gl.SCISSOR_TEST);
  c.bad(store.createResource(meta(233)),'injected packed framebuffer initialization failure','backend-error');c.equal(deleted,1,'unpublished packed texture deleted');
  c.equal([...gl.getParameter(gl.COLOR_WRITEMASK)],[false,true,false,false],'failed initialization restores mask');c.equal(gl.isEnabled(gl.SCISSOR_TEST),false,'failed initialization restores disabled scissor');
  c.equal(c.ok(store.inspect(),'failed packed allocation').budgets.gpuBytes,0,'failed packed allocation has no GPU charge');
  fail=false;c.ok(store.createResource(meta(233)),'same ID succeeds after failure');c.ok(renderer.dispose(),'allocation fault state dispose');cleanup(store,c,'allocation fault resources');c.equal(gl.getError(),gl.NO_ERROR,'allocation fault leaves zero GL errors');
  return{pressure:reports,injectedIncompleteFramebuffer:true,deletedTextures:deleted};
}

async function original(gl,fixtures,c){
  const results=[];
  for(const source of fixtures.colors){
    gl.colorMask(false,true,false,false);gl.enable(gl.SCISSOR_TEST);gl.scissor(0,0,0,0);
    const r=rig(gl,c),{store,renderer,allocations}=r;
    c.ok(store.createContext(source.contextId),'original color context');c.ok(store.createResource(source.metadata),'unchanged original color create');
    if(source.metadata.format===233){c.equal([...gl.getParameter(gl.COLOR_WRITEMASK)],[false,true,false,false],'packed initialization restores mask');c.equal(gl.isEnabled(gl.SCISSOR_TEST),true,'packed initialization restores scissor');}
    c.ok(store.attachContext(source.contextId,source.metadata.id),'original color attach');c.ok(renderer.createContext(source.contextId),'original state context');
    const decoded=c.ok(decodeSubmission(Uint8Array.from(source.packet)),'original surface decoder');c.equal(decoded.commands[0].fields.format,source.metadata.format,'original surface format retained');
    c.ok(renderer.executeSubmission(source.contextId,Uint8Array.from(source.packet)),'unchanged original surface packet');
    c.ok(renderer.executeSubmission(source.contextId,packet(5,0,[1,0,source.handle])),'synthetic color-only framebuffer selection');
    c.ok(renderer.executeSubmission(source.contextId,clear(0)),'production clear with alpha zero');
    const physical=readNative(gl,allocations.get(source.metadata.id).texture,source.metadata.format,source.metadata.width,source.metadata.height);
    c.equal(physical.rgba.every(p=>p[3]===(source.metadata.format===233?3:255)),true,'original X destination alpha remains one after clear');
    results.push({workload:source.workload,metadata:source.metadata,citation:source.citation,componentBits:physical.bits,physicalSha256:await sha(new Uint8Array(physical.data.buffer)),calls:r.calls});
    c.ok(renderer.dispose(),'original state disposal');cleanup(store,c,'original color');
  }
  const source=fixtures.upload,r=rig(gl,c),{store,renderer,allocations}=r;
  c.ok(store.createContext(source.contextId),'original upload context');c.ok(store.createResource(source.metadata),'unchanged original sampled texture');c.ok(store.attachContext(source.contextId,source.metadata.id),'original sampled attachment');
  const input=Uint8Array.from(source.bytes);let offset=0;const segments=source.iovLengths.map(n=>{const b=input.slice(offset,offset+n);offset+=n;return b;});
  c.ok(store.attachBacking(source.metadata.id,segments),'original upload backing');
  const command=c.ok(decodeSubmission(Uint8Array.from(source.packet)),'original RGBA transfer decoder').commands[0];
  c.ok(store.executeTransfer(c.ok(store.prepareTransfer(source.contextId,command),'original RGBA transfer prepare').ticket),'unchanged original RGBA transfer');
  const physical=readNative(gl,allocations.get(source.metadata.id).texture,67,512,512);
  c.equal(await sha(physical.data),source.backingSha256,'original CPU upload matches actual GPU RGBA bytes');
  results.push({format:67,citation:source.citation,backingEvent:source.backingEvent,backingSha256:source.backingSha256,physicalSha256:await sha(physical.data),calls:r.calls});
  c.ok(renderer.dispose(),'original upload state disposal');cleanup(store,c,'original upload');return results;
}

async function drawAlpha(gl,bridge,fixtures,format,c){
  const r=rig(gl,c,{draw:true,bridge}),{store,renderer,allocations}=r;
  for(const action of fixtures.initialization){
    if(action.type==='context_create'){c.ok(store.createContext(2),'tiny context');c.ok(renderer.createContext(2),'tiny state context');}
    else if(action.type==='resource_create')c.ok(store.createResource({...action.metadata,...(action.resourceId===5?{format}: {})}),'tiny format variant resource');
    else if(action.type==='ctx_attach_resource')c.ok(store.attachContext(2,action.resourceId),'tiny attach');
    else if(action.type==='resource_attach_iov')c.ok(store.attachBacking(action.resourceId,action.iovLengths.map(n=>new Uint8Array(n))),'tiny original zero attachment');
    else throw new Error('unexpected original initialization');
  }
  for(const b of fixtures.backing)for(const range of b.ranges)c.ok(store.writeBacking(b.resourceId,range.offset,Uint8Array.from(range.data)),'tiny original CPU inputs');
  const bytes=Uint8Array.from(fixtures.commands.submissions.find(s=>s.event===161).data),v=new DataView(bytes.buffer),mutations=[];
  for(let offset=0;offset<bytes.length;){
    const h=v.getUint32(offset,true),op=h&255,type=(h>>>8)&255,len=((h>>>16)+1)*4;
    if(op===1&&type===8&&v.getUint32(offset+8,true)===5){v.setUint32(offset+12,format,true);mutations.push({byteOffset:offset+12,field:'color surface format',value:format});}
    if(op===12&&v.getUint32(offset+4,true)===1){c.equal(len,28,'original fragment constant bank length');v.setUint32(offset+24,0,true);mutations.push({byteOffset:offset+24,field:'fragment alpha',value:0});}
    offset+=len;
  }
  c.equal(mutations.length,2,'synthetic variant changes exactly surface format and fragment alpha');
  const drawn=c.ok(renderer.executeSubmission(2,bytes),'real production draw to format '+format);c.equal(drawn.draws.length,1,'one actual guest-command draw');
  const physical=readNative(gl,allocations.get(5).texture,format,32,32),a=format===233?3:format===2?255:0,peak=format===233?1023:255;
  for(const[x,y,rgb]of [[8,8,[peak,0,0]],[24,8,[0,peak,0]],[8,24,[0,0,peak]],[24,24,[peak,peak,0]]])c.equal(physical.rgba[y*32+x],[...rgb,a],'draw '+format+' physical channels and destination alpha at '+x+','+y);
  c.equal(r.calls.filter(x=>x.op==='drawElements')[0].colorMask,[true,true,true,format===67],'actual draw destination alpha mask '+format);
  // Independent DST_ALPHA RGB blend reveals the stored destination alpha.
  // It does not admit this currently unsupported guest blend factor.
  const fbo=gl.createFramebuffer(),vao=gl.createVertexArray(),shader=program(gl,'out vec4 color;void main(){color=vec4(1,0,0,0);}');
  gl.bindFramebuffer(gl.DRAW_FRAMEBUFFER,fbo);gl.framebufferTexture2D(gl.DRAW_FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,allocations.get(5).texture,0);gl.drawBuffers([gl.COLOR_ATTACHMENT0]);
  gl.bindVertexArray(vao);gl.useProgram(shader.p);gl.viewport(0,0,32,32);gl.enable(gl.BLEND);gl.blendEquationSeparate(gl.FUNC_ADD,gl.FUNC_ADD);gl.blendFuncSeparate(gl.DST_ALPHA,gl.ZERO,gl.ZERO,gl.ONE);gl.colorMask(true,true,true,false);
  gl.drawArrays(gl.TRIANGLES,0,3);const blended=readNative(gl,allocations.get(5).texture,format,32,32);
  c.equal(blended.rgba[8*32+8],[format===67?0:peak,0,0,a],'physical DST_ALPHA blend '+format);
  shader.dispose();gl.deleteVertexArray(vao);gl.deleteFramebuffer(fbo);
  // Alpha-zero guest fragments must still contribute zero RGB under SRC_ALPHA,
  // even when the destination is an X format with its stored alpha fixed at one.
  const rt=1|(3<<4)|(19<<9)|(1<<17)|(19<<22)|(15<<27);
  c.ok(renderer.executeSubmission(2,packet(1,1,[99,0,0,rt,0,0,0,0,0,0,0])),'synthetic SRC_ALPHA blend object');
  c.ok(renderer.executeSubmission(2,packet(2,1,[99])),'synthetic source-alpha blend binding');
  c.ok(renderer.executeSubmission(2,clear(0)),'clear before source-alpha draw');
  const command=c.ok(decodeSubmission(bytes),'independent draw packet location').commands.find(x=>x.opcode===8);
  c.ok(renderer.executeSubmission(2,bytes.slice(command.byteOffset,command.byteOffset+command.byteLength)),'guest source-alpha draw');
  const sourceBlend=readNative(gl,allocations.get(5).texture,format,32,32);
  c.equal(sourceBlend.rgba[8*32+8],[0,0,0,a],'physical SRC_ALPHA keeps fragment alpha zero '+format);
  c.ok(renderer.dispose(),'draw state disposal');cleanup(store,c,'draw format');c.equal(gl.getError(),gl.NO_ERROR,'draw GL errors');
  return{format,mutations,draw:drawn.draws[0],physicalCorners:[physical.rgba[264],physical.rgba[280],physical.rgba[776],physical.rgba[792]],destinationAlphaBlend:blended.rgba[264],sourceAlphaBlend:sourceBlend.rgba[264],calls:r.calls};
}

export async function runBrowserColorAcceptance(fixtures){
  const c=checks(),canvas=document.querySelector('#gpu'),gl=canvas.getContext('webgl2',{antialias:false,preserveDrawingBuffer:true});c.equal(Boolean(gl),true,'actual WebGL2');
  const debug=gl.getExtension('WEBGL_debug_renderer_info'),renderer=debug?gl.getParameter(debug.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER);
  c.equal(/swiftshader|llvmpipe|softpipe|lavapipe/i.test(renderer),false,'hardware renderer required');
  const originals=await original(gl,fixtures,c),formats=[];
  for(const format of [2,67,233])formats.push(await rows(gl,format,c));
  const bridge=await createVirglShaderBridge(),draws=[];
  for(const format of [233,2,67])draws.push(await drawAlpha(gl,bridge,fixtures.tiny,format,c));
  const copies=[];for(const format of [2,67,233])copies.push(await copyCases(gl,format,c));
  const generations=await generationCases(gl,c),budgets=await budgetCases(gl,c);
  c.equal(gl.getError(),gl.NO_ERROR,'final physical GL errors');
  return{status:'passed',guestExecution:false,boundary:'Original selected color packets and synthetic hardware storage/draw variants; no full gears/browser offload claim.',renderer,originals,formats,draws,copies,generations,budgets,assertions:c.rows};
}
