#!/usr/bin/env node
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {browserDocument,browserOptions,runVirglBrowser} from '../lib/virgl-browser-runner.mjs';
const options=browserOptions(['--seed','--fault-wasm','--fault-original']),manifest=JSON.parse(fs.readFileSync('renderer/virgl-shader/tests/original-corpus.json'));
const files=['renderer/virgl-shader/tests/original-corpus.json','renderer/virgl-shader/tests/captured-grammar-migrations.json','renderer/virgl-shader/tests/captured-invalid.json','renderer/virgl-command/constant-domain.mjs','tools/virgl-original-corpus/oracle.mjs','tools/virgl-radial-domain/oracle.mjs',...manifest.originals.map(e=>e.path)];if(options['fault-wasm'])files.push(options['fault-wasm'].replace(/^\//,''));
const pinnedFiles=files.map(path=>{const raw=fs.readFileSync(path);return{path,size:raw.length,sha256:createHash('sha256').update(raw).digest('hex')};});
await runVirglBrowser({options,task:'E6-T12f6',serializedAcceptance:true,boundary:'Nineteen unchanged captured TGSI bodies on actual WebGL2; explicit existing runtime domains',reportFields:{currentGuest3dAdvertisement:false},modulePath:'/renderer/virgl-shader/tests/original-corpus.mjs',windowReportKey:'__virglOriginalCorpusReport',browserArguments:{seed:Number(options.seed??0x619eca43)>>>0,faultWasm:options['fault-wasm']??null,faultOriginal:options['fault-original']??null},servedFiles:files,pinnedFiles,coveragePaths:['renderer/virgl-shader/tests/original-corpus.mjs','tools/virgl-original-corpus/oracle.mjs','renderer/virgl-command/constant-domain.mjs'],html:browserDocument({title:'Unchanged shader corpus',heading:'Captured original shader closure',description:'Physical compile/link, written-lane numerical capture and original fragment pixels; guest GPU remains disabled'}),validate(r){assert.equal(r.status,'passed');assert.equal(r.originals.length,19);assert.equal(r.pairs.length,88);assert.equal(r.pairs.filter(e=>e.ok).length,57);assert.equal(r.vertices.length,8);assert.equal(r.fragments.length,11);assert.equal(r.objects.live,0);},successMessage:r=>`19 unchanged bodies, 57 native programs; ${r.checkedVertexWords} vertex words, ${r.checkedPixels} actual pixels.`});
