import {header,outerTransfer,decodeHeader} from '/wire-oracle.mjs';
import {GPU_BOTTOM_UP_RGBA,CANVAS_TOP_DOWN_RGBA,assertLiteralCanvas,CANONICAL_BGRA_WORDS} from '/pixel-oracle.mjs';
import {createVirglScanoutBridge} from '/renderer/virgl-command/control-bridge.mjs';
import {createVirglShaderBridge} from '/renderer/virgl-shader/index.mjs';
import {createVirglScanoutPresenter} from '/web/dist/src/sink/virgl-scanout-presenter.js';
import {createGlOracle} from '/gl-oracle.mjs';
const hex=n=>BigInt(n).toString(16).padStart(16,'0');
const set32=(b,o,n)=>new DataView(b.buffer).setUint32(o,n,true);
const get16=b=>new DataView(b.buffer,b.byteOffset,b.byteLength).getUint16(0,true);
const get32=(b,n=0)=>new DataView(b.buffer,b.byteOffset,b.byteLength).getUint32(n,true);
const packet=(t,n,ctx=0)=>{const b=new Uint8Array(n);b.set(header(t,{flags:0,context:ctx}));return b;};
const context=(id=2)=>packet(0x200,96,id);
const idPacket=(t,id,ctx=0)=>{const b=packet(t,32,ctx);set32(b,24,id);return b;};
const create=(id=11,w=3,h=2)=>{const b=packet(0x204,72);[id,2,67,10,w,h,1,1,0,0,0,0].forEach((x,i)=>set32(b,24+4*i,x));return b;};
const backing=(id,addr,len)=>{const b=packet(0x106,48);set32(b,24,id);set32(b,28,1);new DataView(b.buffer).setBigUint64(32,addr,true);set32(b,40,len);return b;};
const display=(t=0x103,id=11,w=3,h=2,fence=0xffffffffffffffffn)=>{const b=packet(t,48);b.set(header(t,{flags:1,context:0,fence}));[0,0,w,h].forEach((v,i)=>set32(b,24+4*i,v));set32(b,t===0x103?44:40,id);return b;};
export async function runAttacks({WasmVirglScanoutProof,wasmMemory}){
 let assertions=0,turns=0;const records=[],oracles=[];
 const eq=(a,b,label)=>{assertions++;if(JSON.stringify(a)!==JSON.stringify(b))throw Error(label+': '+JSON.stringify(a)+' != '+JSON.stringify(b));};
 const ok=(r,label)=>{eq(r?.ok,true,label+' '+JSON.stringify(r?.error));return r;};
 const bad=(r,label)=>{eq(r?.ok,false,label);records.push({label,error:r.error});return r;};
 const throws=(fn,label)=>{let caught;try{fn();}catch(e){caught=e.message;}eq(typeof caught,'string',label);records.push({label,caught});};
 const gl=document.querySelector('#gpu').getContext('webgl2',{antialias:false}),shaderBridge=await createVirglShaderBridge();
 const tick=async()=>{await new Promise(r=>setTimeout(r,0));turns++;};
 class Queue{
  constructor(callback,frameCallback,proof=true){this.vm=new WasmVirglScanoutProof(callback,frameCallback,proof);this.base=BigInt('0x'+this.vm.layout().ramBase);this.desc=this.base+0x4000n;this.avail=this.base+0x6000n;this.used=this.base+0x7000n;this.next=0;this.configure(proof);}
  write(address,bytes){this.vm.writeRam(hex(address),bytes);}read(address,length){return this.vm.readRam(hex(address),length);}
  configure(proof=true){this.next=0;this.write(this.avail,new Uint8Array(520));this.write(this.used,new Uint8Array(2056));this.vm.writeMmio(0x30,0);this.vm.writeMmio(0x38,256);for(const[o,a]of[[0x80,this.desc],[0x90,this.avail],[0xa0,this.used]]){this.vm.writeMmio(o,Number(a&0xffffffffn));this.vm.writeMmio(o+4,Number(a>>32n));}this.vm.writeMmio(0x44,1);this.vm.writeMmio(0x70,3);this.vm.writeMmio(0x24,0);this.vm.writeMmio(0x20,proof?1:0);this.vm.writeMmio(0x24,1);this.vm.writeMmio(0x20,1);this.vm.writeMmio(0x70,11);this.vm.writeMmio(0x70,15);}
  descriptor(index,address,len,flags,next=0){const b=new Uint8Array(16),v=new DataView(b.buffer);v.setBigUint64(0,address,true);v.setUint32(8,len,true);v.setUint16(12,flags,true);v.setUint16(14,next,true);this.write(this.desc+16n*BigInt(index),b);}
  enqueue(request,capacity=24){const n=this.next++,head=(n%128)*2,src=this.base+0x10000n+BigInt(n*256),dst=this.base+0x80000n+BigInt(n*64);this.write(src,request);this.write(dst,new Uint8Array(64).fill(0xa7));this.descriptor(head,src,request.length,1,head+1);this.descriptor(head+1,dst,capacity,2);const b=new Uint8Array(2),v=new DataView(b.buffer);v.setUint16(0,head,true);this.write(this.avail+4n+BigInt((n%256)*2),b);v.setUint16(0,this.next,true);this.write(this.avail+2n,b);return{n,head,src,dst,request:request.slice(),capacity};}
  usedIndex(){return get16(this.read(this.used+2n,2));}run(){eq(this.vm.run1().outcome,'MaxInstrs','Machine boundary');}kick(){this.vm.writeMmio(0x50,0);}
  check(e,type=0x1100){const bytes=this.read(e.dst,24),got=decodeHeader(bytes),sent=decodeHeader(e.request);eq(got.type,type,'exact response type');eq(got.flags,sent.flags&1,'fence flag echo');eq(got.fence,sent.flags&1?sent.fence:'0000000000000000','full fence echo');eq(got.context,sent.context,'context echo');const used=this.read(this.used+4n+BigInt(e.n*8),8);eq([get32(used),get32(used,4)],[e.head,24],'used head/length');eq([...this.read(e.dst+24n,40)],Array(40).fill(0xa7),'response guard');return{n:e.n,request:[...e.request],response:[...bytes],used:[...used]};}
 }
 function rig(options={}){const oracle=createGlOracle(gl);oracle.setStrict(true);oracles.push(oracle);let q,next=1;const scheduled=new Map(),cancelled=[],callbacks=[],rawFrames=[],hooks={};
  const canvas=document.createElement('canvas');canvas.style.cssText='width:240px;height:160px;image-rendering:pixelated;border:3px solid #888;background:#333';document.querySelector('#frames').append(canvas);
  const presenter=ok(createVirglScanoutPresenter({canvas,requestFrame(fn){const n=next++;scheduled.set(n,fn);return n;},cancelFrame(n){cancelled.push(n);},controllerOptions:{defaultBackend:'canvas2d'}}),'presenter').presenter;
  const host=ok(createVirglScanoutBridge({gl:oracle.gl,shaderBridge,presenter:options.presenter?options.presenter(presenter):presenter,transport:{gatherInput(...a){return q.vm.gatherInput(...a);},scatterOutput(...a){return q.vm.scatterOutput(...a);},complete(...a){const before=q.usedIndex();eq(oracle.statistics().violations.length,0,'mailbox completion follows independently checked staging collection');hooks.beforeComplete?.();const r=q.vm.complete(...a);eq(q.usedIndex(),before,'mailbox does not publish used');return r;}}}),'bridge');
  q=new Queue(event=>{callbacks.push(event);hooks.onEvent?.(event);return host.bridge.apply(event);},frame=>{rawFrames.push(frame);return hooks.frame?hooks.frame(frame):host.bridge.present2D(frame);});
  async function pump(){await tick();const before=q.usedIndex(),r=host.bridge.pump();eq(q.usedIndex(),before,'host pump never publishes used');if(oracle.statistics().violations.length)throw Error(oracle.statistics().violations[0].message);return ok(r,'host pump '+JSON.stringify(host.bridge.inspect().lastFailure));}
  async function drain(){for(let n=0;n<1024;n++){const before=oracle.statistics().counts.clientWaitSync??0;q.run();eq(oracle.statistics().counts.clientWaitSync??0,before,'Machine never polls GL');if(q.usedIndex()===q.next)return; if(!q.vm.submitInspect().ready)await pump();}throw Error('drain exceeded bound');}
  async function send(request,type=0x1100){const e=q.enqueue(request);q.kick();await drain();q.check(e,type);q.vm.writeMmio(0x64,1);return e;}
  function paint(){const active=[...scheduled].filter(([id])=>!cancelled.includes(id)).at(-1);eq(Boolean(active),true,'one live animation request');active[1]();scheduled.delete(active[0]);return ok(presenter.readPixels(),'actual canvas pixels').bytes;}
  async function setup(){await send(context());await send(create());await send(backing(11,q.base+0x100000n,24));await send(idPacket(0x202,11,2));q.write(q.base+0x100000n,Uint8Array.from(GPU_BOTTOM_UP_RGBA));const e=q.enqueue(outerTransfer('toHost',{width:3,height:2,stride:12}));q.kick();q.run();const snapshot=q.vm.submitState();eq(snapshot.pending.context.id,2,'pending transfer keeps context authority');eq(snapshot.pending.byteLength,hex(72),'pending transfer diagnostic size');await drain();q.check(e);await send(display());}
  function cleanup(){records.push({label:'rig counters before cleanup',scanout:host.bridge.inspect().scanout,native:oracle.statistics()});ok(host.bridge.dispose(),'dispose');q.vm.free();eq(oracle.statistics().liveBuffers,0,'all actual native buffers released');eq(oracle.statistics().liveSyncs,0,'all actual native syncs released');eq(gl.getError(),0,'actual GL error zero');}
  return{q,host,oracle,presenter,scheduled,cancelled,callbacks,rawFrames,hooks,pump,drain,send,paint,setup,cleanup};
 }
 // A real issued snapshot outlives content revision, released read lease and guest RAM mutation.
 for(const delay of[2,5,9]){const r=rig();try{await r.setup();const submitWire=packet(0x207,32,2),pending=r.q.enqueue(submitWire);r.q.kick();r.q.run();eq(r.q.vm.submitState().pending.context.id,2,'pending command keeps context authority');eq(r.q.vm.submitState().pending.byteLength,hex(0),'empty command diagnostic size');await r.drain();r.q.check(pending);const q=r.q,owners=r.host.probes.owners(),lease=ok(owners.store.retainStorage(2,11,'readback'),'mutable read lease').lease;
  const read=ok(owners.asyncAccess.beginStorageRead(lease,{x:0,y:0,z:0,width:3,height:2,depth:1}),'mutable storage read').ticket;
  const flush=q.enqueue(display(0x104));q.kick();q.run();r.oracle.delayWaits(delay);await r.pump();eq(r.oracle.statistics().counts.readPixels,2,'both real PBO reads issued');
  const command={opcode:43,fields:{resourceHandle:11,level:0,usage:0,stride:12,layerStride:0,box:{x:0,y:0,z:0,width:3,height:2,depth:1},dataOffset:0,direction:1}};
  const ticket=ok(owners.asyncAccess.prepareTransfer(2,command),'independent host upload ticket').ticket;
  ok(owners.asyncAccess.provideInput(ticket,new Uint8Array(24).fill(255)),'white later contents');ok(owners.asyncAccess.upload(ticket),'real later GPU write');ok(owners.asyncAccess.release(ticket),'release upload');
  bad(owners.asyncAccess.validate(read),'mutable read revision remains rejected');ok(owners.asyncAccess.release(read),'release stale mutable read');ok(owners.store.releaseStorage(lease),'release mutable lease');
  q.write(q.base+0x100000n,new Uint8Array(24).fill(0));wasmMemory.grow(1);await r.drain();q.check(flush);eq(r.presenter.inspect().drawn,0,'successful FLUSH has not painted');eq(r.presenter.inspect().pending,1,'exactly one owned queued frame');eq(r.host.bridge.inspect().scanout.retainedFrames,1,'PBO ticket held until actual paint');
  const pixels=r.paint();assertLiteralCanvas(pixels);assertions+=24;eq(r.host.bridge.inspect().scanout.retainedFrames,0,'actual paint retires ticket');eq(r.presenter.inspect().drawn,1,'separate actual-draw acknowledgement');
  const c=r.host.bridge.inspect().scanout;eq([c.readbackBytes,c.rgbaConversionBytes,c.rowMoveBytes,c.presenter.controllerOwnershipCopyBytes,c.presenter.presentationUploadBytes,c.presenter.backendStagingCopyBytes,c.presenter.imageDataCopyBytes],[24,24,24,24,24,24,24],'literal measured copy counters');
  records.push({label:'capture A survives real GPU write B, strict mutable reads remain',delay,pixels:[...pixels],scanout:c,trace:q.vm.commandTrace()});if(delay===2)await globalThis.captureLiveFrame();
 }finally{r.cleanup();}}
 // Context destruction does not revoke global display; public unref rejects future flush while an accepted frame survives exact ID reuse.
 {const r=rig();try{await r.setup();await r.send(header(0x201,{flags:0,context:2}));await r.send(display(0x104));const generation=r.q.vm.scanoutState().binding.target.resource.generation;await r.send(idPacket(0x102,11));await r.send(display(0x104),0x1203);await r.send(create(11,2,3));await r.send(display(0x104),0x1205);const pixels=r.paint();assertLiteralCanvas(pixels);assertions+=24;records.push({label:'global identity survives context destroy and accepted unref/reuse',generation,pixels:[...pixels]});
  await r.send(display(0x103,11,2,3));eq(r.host.bridge.inspect().scanout.binding.target.metadata.width,2,'replacement requires explicit rebind');await r.send(context(3));await r.send(backing(11,r.q.base+0x120000n,24));await r.send(idPacket(0x202,11,3));const blue=Uint8Array.from({length:24},(_,i)=>i%4===2||i%4===3?255:0);r.q.write(r.q.base+0x120000n,blue);await r.send(outerTransfer('toHost',{context:3,width:2,height:3,stride:8}));await r.send(display(0x104,11,2,3));eq([...r.paint()],[...blue],'reused 2x3 blue resource actually paints only after new binding');eq([r.presenter.canvas.width,r.presenter.canvas.height],[2,3],'replacement changes actual canvas dimensions');records.push({label:'replacement 2x3 distinct blue actual frame',pixels:[...blue]});
 }finally{r.cleanup();}}
 // Supersession uses one animation request and exact-once retirement; stale callbacks after rebind/reset do nothing.
 {const r=rig();try{await r.setup();await r.send(display(0x104));const old=[...r.scheduled.values()].at(-1);await r.send(display(0x104));eq(r.presenter.inspect().pending,1,'one pending frame after supersession');eq(r.presenter.inspect().superseded,1,'old frame explicitly superseded');eq(r.host.bridge.inspect().scanout.retainedFrames,1,'only replacement retains staging');
  await r.send(display(0x103,0,0,0));const before=r.presenter.inspect();old();eq(r.presenter.inspect(),before,'cancelled scheduler token cannot draw');eq(r.host.bridge.inspect().scanout.retainedFrames,0,'disable releases retained pixels');await r.send(display());await r.send(display(0x104));const late=[...r.scheduled.values()].at(-1);r.q.vm.writeMmio(0x70,0);const reset=r.presenter.inspect();late();eq(r.presenter.inspect(),reset,'late callback after reset cannot draw');records.push({label:'one-frame replacement plus disable/reset stale callbacks',before,reset});
 }finally{r.cleanup();}}
 // Unsupported global wire does not consume binding generation or cancel a queued valid frame.
 {const r=rig();try{await r.setup();await r.send(display(0x104));const before=r.q.vm.scanoutState(),p=r.presenter.inspect();const badWire=[];
  for(const [offset,value]of[[16,2],[20,1],[40,1],[24,1],[32,2]]){const b=display();set32(b,offset,value);badWire.push(b);}
  const surplus=new Uint8Array(49);surplus.set(display());badWire.push(surplus);
  for(const b of badWire){await r.send(b,0x1205);eq(r.q.vm.scanoutState(),before,'bad binding preserves canonical state');eq(r.presenter.inspect(),p,'bad binding preserves queued frame');}
  for(const [offset,value]of[[16,2],[44,1],[24,1],[32,2]]){const b=display(0x104);set32(b,offset,value);await r.send(b,0x1205);}
  const calls=r.callbacks.length,e=r.q.enqueue(display(),23);r.q.kick();await r.drain();eq(r.callbacks.length,calls,'short reply prevents host binding mutation');eq([...r.q.read(e.dst,64)],Array(64).fill(0xa7),'short reply bytes unchanged');eq(get32(r.q.read(r.q.used+4n+BigInt(e.n*8),8),4),0,'short reply used length zero');assertLiteralCanvas(r.paint());assertions+=24;records.push({label:'strict wire profile and full reply preflight',mutations:badWire.map(x=>[...x])});
 }finally{r.cleanup();}}
 // A scanout job has no context/DMA authority, cannot invent command counts, and reset rejects late completion.
 {const r=rig();try{await r.setup();const e=r.q.enqueue(display(0x104,11,3,2,0x8000000000000001n));r.q.kick();r.q.run();const a=r.q.vm.submitInspect().active,resource=r.callbacks.find(x=>x.type==='createResource').resource;
  throws(()=>r.q.vm.gatherInput(a.epoch,a.sequence,hex(1),11,resource.generation,hex(1),hex(0),24,24,1),'global capture cannot borrow context DMA');
  throws(()=>r.q.vm.complete(a.epoch,a.sequence,hex(0),0,true,1,0),'global capture cannot claim commands');throws(()=>r.q.vm.complete(a.epoch,a.sequence,hex(0),0,true,0,1),'global capture cannot claim draws');
  await r.drain();r.q.check(e);r.paint();r.q.vm.writeMmio(0x70,0);throws(()=>r.q.vm.complete(a.epoch,a.sequence,hex(0),0,true,0,0),'late capture callback after reset');records.push({label:'global capture mailbox authority',identity:a});
 }finally{r.cleanup();}}
 // Ordinary borrowed 2D frames copy immediately before Wasm growth and use the very same display owner.
 {const r=rig();try{await r.setup();await r.send(display(0x104));const stale=[...r.scheduled.values()].at(-1);const b=packet(0x101,40);[12,1,3,2].forEach((v,i)=>set32(b,24+4*i,v));await r.send(b);await r.send(backing(12,r.q.base+0x110000n,24));const bytes=new Uint8Array(Uint32Array.from(CANONICAL_BGRA_WORDS).buffer);r.q.write(r.q.base+0x110000n,bytes);
  const up=packet(0x105,56);[0,0,3,2].forEach((v,i)=>set32(up,24+i*4,v));set32(up,48,12);await r.send(up);await r.send(display(0x103,12));await r.send(display(0x104,12));eq(r.rawFrames.length,1,'ordinary core FrameSink actually invoked');r.q.write(r.q.base+0x110000n,new Uint8Array(24).fill(255));wasmMemory.grow(1);stale();eq(r.presenter.inspect().drawn,0,'stale 3D callback cannot paint pending 2D');assertLiteralCanvas(r.paint());assertions+=24;eq(r.host.bridge.inspect().scanout.borrowed2dCopyBytes,24,'borrowed Wasm 2D copy measured');await r.send(display());await r.send(display(0x104));assertLiteralCanvas(r.paint());assertions+=24;records.push({label:'3D to 2D borrowed-memory growth to 3D actual canvas',diagnostics:r.q.vm.frameDiagnostics(),presenter:r.presenter.inspect()});
 }finally{r.cleanup();}}
 // New strict scanout routes reject unnegotiated, truncated and invalid 2D-region requests.
 {const r=rig();try{r.q.vm.writeMmio(0x70,0);r.q.configure(false);await r.send(display(0x104),0x1200);r.q.vm.writeMmio(0x70,0);r.q.configure();await r.send(header(0x104,{flags:0,context:0}),0x1205);const b=packet(0x101,40);[12,1,3,2].forEach((v,i)=>set32(b,24+4*i,v));await r.send(b);await r.send(display(0x103,12,4,2),0x1205);records.push({label:'scanout preflight negative negotiation, short capture and invalid 2D rectangle'});}finally{r.cleanup();}}
 // Trusted transport exceptions before completion poison the bridge, reject 2D use and reset retires queued data.
 {const r=rig();try{await r.setup();const e=r.q.enqueue(display(0x104));r.q.kick();r.q.run();r.hooks.beforeComplete=()=>{delete r.hooks.beforeComplete;throw 17;};let failed;
  for(let n=0;n<50;n++){await tick();const v=r.host.bridge.pump();if(!v.ok){failed=v;break;}}bad(failed,'non-Error capture completion transport exception');eq(r.host.bridge.inspect().poisoned,true,'uncertain capture poisons');bad(r.host.bridge.present2D({}),'poisoned bridge rejects borrowed frame');r.q.run();r.q.check(e,0x1200);r.q.vm.writeMmio(0x70,0);eq(r.presenter.inspect().pending,0,'reset retires uncertain queued frame');r.q.configure();await r.send(context());records.push({label:'uncertain capture transport exception and reset',failure:failed});
 }finally{r.cleanup();}}
 // Exactly bounded retired-frame diagnostics, even when trusted retirement callbacks throw.
 {let callback;const canvas=document.createElement('canvas'),p=ok(createVirglScanoutPresenter({canvas,requestFrame(fn){callback=fn;return 1;},cancelFrame(){}}),'bounded callback presenter').presenter;
  ok(p.rebind(hex(1)),'bounded bind');const frame={scanout:0,format:1,rect:{x:0,y:0,width:1,height:1},resourceWidth:1,resourceHeight:1,pixels:Uint32Array.of(0xffff0000)};
  for(let n=0;n<260;n++){ok(p.enqueueOwned({bindingGeneration:hex(1),frame},()=>{bad(p.dispose(),'reentrant callback dispose rejected');throw 17;}),'bounded enqueue');callback();}
  eq(p.inspect().drawn,260,'trusted callback exceptions cannot erase actual draws');eq(p.inspect().errors.length,256,'bounded presenter error log');ok(p.dispose(),'bounded presenter cleanup');records.push({label:'trusted callback reentrancy and bounded diagnostics',drawn:260,errors:256});
 }
 // Frame diagnostics preserve the ordinary infallible 2D sink contract, while reporting a rejected host frame explicitly.
 {const r=rig();try{r.hooks.onEvent=()=>throws(()=>r.q.vm.scanoutState(),'scanoutState rejects reentrant Machine borrow');await r.send(context());delete r.hooks.onEvent;
  const b=packet(0x101,40);[12,1,1,1].forEach((v,i)=>set32(b,24+4*i,v));await r.send(b);await r.send(display(0x103,12,1,1));r.hooks.frame=()=>({ok:false,error:{code:'invalid-parameter',message:'verifier rejected borrowed frame'}});await r.send(display(0x104,12,1,1));eq(r.q.vm.frameDiagnostics().rejected,hex(1),'explicit rejected FrameSink diagnostic');eq(r.q.vm.frameDiagnostics().lastError,'invalid-parameter','exact FrameSink error diagnostic');delete r.hooks.frame;
  for(let n=0;n<260;n++){ok(r.host.bridge.present2D({scanout:0,format:1,rect:{x:0,y:0,width:1,height:1},resourceWidth:1,resourceHeight:1,pixels:Uint32Array.of(0xffff0000)}),'bounded 2D frame');r.paint();}
  eq(r.host.bridge.inspect().scanout.retirements.length,256,'bounded correlated retirement records');eq(r.presenter.inspect().drawn,260,'all bounded frames actually painted');records.push({label:'FrameSink error diagnostic and bounded correlated retirement records',diagnostics:r.q.vm.frameDiagnostics(),retirements:r.host.bridge.inspect().scanout.retirements.length});
 }finally{r.cleanup();}}
 {const q=new Queue(()=>({ok:true}),()=>({ok:true}),false);eq(q.vm.scanoutState(),null,'ordinary constructor has no scanout proof state');q.vm.writeMmio(0x14,0);eq(q.vm.readMmio(0x10)&1,0,'ordinary GPU does not advertise VIRGL');q.vm.free();records.push({label:'ordinary constructor production capability isolation'});}
 // Trusted presenter rejection, Promise and throw never become accepted pixels.
 {const r=rig({presenter:p=>({...p,enqueueOwned(){return {ok:false,error:{code:'invalid-parameter',message:'verifier enqueue rejection'}};}})});try{const b=packet(0x101,40);[12,1,1,1].forEach((v,i)=>set32(b,24+4*i,v));await r.send(b);await r.send(display(0x103,12,1,1));await r.send(display(0x104,12,1,1));eq(r.q.vm.frameDiagnostics().rejected,hex(1),'real bridge enqueue rejection reaches 2D diagnostic');eq(r.presenter.inspect().queued,0,'rejected 2D is never accepted');records.push({label:'2D presenter enqueue rejection'});}finally{r.cleanup();}}
 for(const mode of ['promise','throw']){const r=rig({presenter:p=>({...p,enqueueOwned(){if(mode==='promise')return Promise.resolve({ok:true});throw 17;}})});try{await r.setup();const e=r.q.enqueue(display(0x104));r.q.kick();r.q.run();let failed;for(let n=0;n<50;n++){await tick();const v=r.host.bridge.pump();if(!v.ok){failed=v;break;}}bad(failed,'trusted '+mode+' enqueue rejected');eq(r.presenter.inspect().queued,0,'asynchronous or throwing enqueue cannot accept pixels');eq(r.host.bridge.inspect().poisoned,true,'uncertain enqueue poisons bridge');r.q.run();r.q.check(e,0x1200);r.q.vm.writeMmio(0x70,0);eq(r.host.bridge.inspect().scanout.retainedFrames,0,'reset releases uncertain retained snapshot');records.push({label:'trusted '+mode+' enqueue terminal failure'});}finally{r.cleanup();}}
 return{status:'passed',assertions,turns,records,native:oracles.map(x=>({statistics:x.statistics(),events:x.events}))};
}
