import {header,submit,outerTransfer,decodeHeader,dirtyAddresses,expectedScatter} from '/wire-oracle.mjs';
import {createVirglSubmitBridge} from '/renderer/virgl-command/control-bridge.mjs';
import {createVirglShaderBridge} from '/renderer/virgl-shader/index.mjs';
import {createGlOracle} from '/gl-oracle.mjs';
const hex=n=>BigInt(n).toString(16).padStart(16,'0');
const set32=(bytes,offset,n)=>new DataView(bytes.buffer).setUint32(offset,n,true);
const get16=b=>new DataView(b.buffer,b.byteOffset,b.byteLength).getUint16(0,true);
const get32=(b,n=0)=>new DataView(b.buffer,b.byteOffset,b.byteLength).getUint32(n,true);
const packet=(type,length,context=0)=>{const out=new Uint8Array(length);out.set(header(type,{flags:0,context}));return out;};
const context=(id=2)=>packet(0x200,96,id);
const idPacket=(type,id,ctx=0)=>{const p=packet(type,32,ctx);set32(p,24,id);return p;};
const create=(id=11)=>{const p=packet(0x204,72);[id,2,67,10,4,4,1,1,0,0,0,0].forEach((x,i)=>set32(p,24+4*i,x));return p;};
const backing=(id,segments)=>{const p=packet(0x106,32+16*segments.length);set32(p,24,id);set32(p,28,segments.length);for(let i=0;i<segments.length;i++){new DataView(p.buffer).setBigUint64(32+16*i,segments[i].address,true);set32(p,40+16*i,segments[i].length);}return p;};
const embedded=(direction,options={})=>{const {x=0,y=0,width=4,height=4,offset=0,stride=16,id=11}=options;const p=new Uint8Array(56);set32(p,0,43+(13<<16));[id,0,0,stride,0,x,y,0,width,height,1,offset,direction].forEach((v,i)=>set32(p,4+4*i,v));return p;};
export async function runAttacks({WasmVirglSubmitProof,wasmMemory}){
 let assertions=0,turns=0;const records=[],events=[],oracles=[];
 const eq=(a,b,label)=>{assertions++;if(JSON.stringify(a)!==JSON.stringify(b))throw Error(label+': '+JSON.stringify(a)+' != '+JSON.stringify(b));};
 const ok=(r,label)=>{eq(r?.ok,true,label+' '+JSON.stringify(r?.error));return r;};
 const throws=(fn,label)=>{let caught;try{fn();}catch(e){caught=e.message;}eq(typeof caught,'string',label);records.push({label,caught});return caught;};
 const gl=document.querySelector('#gpu').getContext('webgl2',{antialias:false}),shaderBridge=await createVirglShaderBridge();
 const tick=async()=>{await new Promise(r=>setTimeout(r,0));turns++;};
 class Queue{
  constructor(callback,proof=true){this.vm=new WasmVirglSubmitProof(callback,proof);this.base=BigInt('0x'+this.vm.layout().ramBase);this.desc=this.base+0x4000n;this.avail=this.base+0x6000n;this.used=this.base+0x7000n;this.next=0;this.configure(proof);}
  write(address,bytes){this.vm.writeRam(hex(address),bytes);}read(address,length){return this.vm.readRam(hex(address),length);}
  configure(proof=true){this.next=0;this.write(this.avail,new Uint8Array(520));this.write(this.used,new Uint8Array(2056));this.vm.writeMmio(0x30,0);this.vm.writeMmio(0x38,256);for(const[o,a]of[[0x80,this.desc],[0x90,this.avail],[0xa0,this.used]]){this.vm.writeMmio(o,Number(a&0xffffffffn));this.vm.writeMmio(o+4,Number(a>>32n));}this.vm.writeMmio(0x44,1);this.vm.writeMmio(0x70,3);this.vm.writeMmio(0x24,0);this.vm.writeMmio(0x20,proof?1:0);this.vm.writeMmio(0x24,1);this.vm.writeMmio(0x20,1);this.vm.writeMmio(0x70,11);this.vm.writeMmio(0x70,15);}
  descriptor(index,address,len,flags,next=0){const b=new Uint8Array(16),v=new DataView(b.buffer);v.setBigUint64(0,address,true);v.setUint32(8,len,true);v.setUint16(12,flags,true);v.setUint16(14,next,true);this.write(this.desc+16n*BigInt(index),b);}
  enqueue(request,capacity=24){const n=this.next++,head=(n%128)*2,src=this.base+0x10000n+BigInt(n*256),dst=this.base+0x80000n+BigInt(n*64);this.write(src,request);this.write(dst,new Uint8Array(64).fill(0xa7));this.descriptor(head,src,request.length,1,head+1);this.descriptor(head+1,dst,capacity,2);const b=new Uint8Array(2),v=new DataView(b.buffer);v.setUint16(0,head,true);this.write(this.avail+4n+BigInt((n%256)*2),b);v.setUint16(0,this.next,true);this.write(this.avail+2n,b);return{n,head,src,dst,request:request.slice(),capacity};}
  usedIndex(){return get16(this.read(this.used+2n,2));}run(){eq(this.vm.run1().outcome,'MaxInstrs','Machine boundary');}kick(){this.vm.writeMmio(0x50,0);}
  check(e,type=0x1100){const bytes=this.read(e.dst,24),got=decodeHeader(bytes),sent=decodeHeader(e.request);eq(got.type,type,'exact response type');eq(got.flags,sent.flags&1,'fence flag echo');eq(got.fence,sent.flags&1?sent.fence:'0000000000000000','full fence echo');eq(got.context,sent.context,'context echo');const used=this.read(this.used+4n+BigInt(e.n*8),8);eq([get32(used),get32(used,4)],[e.head,24],'used head/length');eq([...this.read(e.dst+24n,40)],Array(40).fill(0xa7),'response guard');return{n:e.n,request:[...e.request],response:[...bytes],used:[...used]};}
 }
 function rig(options={}){const oracle=createGlOracle(gl);oracle.setStrict(true);oracles.push(oracle);let q;const callbackEvents=[],exchanges=[],completions=[],hooks={};
  const host=ok(createVirglSubmitBridge({gl:oracle.gl,shaderBridge,transport:{gatherInput(...args){const bytes=q.vm.gatherInput(...args);exchanges.push({kind:'input',args,bytes:[...bytes]});hooks.afterGather?.(args,bytes);return bytes;},scatterOutput(...args){const before=q.usedIndex();const result=q.vm.scatterOutput(...args);eq(q.usedIndex(),before,'scatter cannot publish used');exchanges.push({kind:'output',args:args.slice(0,-1),bytes:[...args.at(-1)]});hooks.afterScatter?.(args);return result;},complete(...args){const active=q.vm.submitInspect().active;eq(args.slice(0,2),[active.epoch,active.sequence],'completion identity must match active head');if(args[4])eq(oracle.statistics().liveSyncs,0,'completion waits for all native fences');const before=q.usedIndex(),result=q.vm.complete(...args);eq(q.usedIndex(),before,'mailbox does not publish used');completions.push(args);hooks.afterComplete?.(args);return result;}}}),'bridge');
  q=new Queue(event=>{callbackEvents.push(event);return hooks.callback?hooks.callback(event):host.bridge.apply(event);},options.proof??true);
  async function pump(){await tick();const before=q.usedIndex(),r=host.bridge.pump();eq(q.usedIndex(),before,'host pump cannot publish used');if(!r.ok&&/completion identity must match active head/.test(host.bridge.inspect().lastFailure?.message))throw Error(host.bridge.inspect().lastFailure.message);if(oracle.statistics().violations.length)throw Error('Independent GL oracle '+JSON.stringify(oracle.statistics().violations));return r;}
  async function drain(){for(let n=0;n<1024;n++){const waits=oracle.statistics().counts.clientWaitSync??0;q.run();eq(oracle.statistics().counts.clientWaitSync??0,waits,'Machine.run never polls GPU');if(q.usedIndex()===q.next)return;if(q.vm.submitInspect().ready)continue;ok(await pump(),'pump');}throw Error('bounded host pump exhausted');}
  async function send(request,type=0x1100){const e=q.enqueue(request);q.kick();await drain();const record=q.check(e,type);q.vm.writeMmio(0x64,1);return record;}
  function cleanup(){ok(host.bridge.dispose(),'dispose host');q.vm.free();eq(oracle.statistics().liveBuffers,0,'native buffers released');eq(oracle.statistics().liveSyncs,0,'native syncs released');eq(gl.getError(),0,'native GL error');events.push(callbackEvents.map(e=>({type:e.type,epoch:e.epoch,sequence:e.sequence})));}
  return{q,host,oracle,hooks,callbackEvents,exchanges,completions,pump,drain,send,cleanup};
 }
 // Three independent schedules, literal texels, actual RAM SG, captured reply span.
 const texels=Uint8Array.from({length:64},(_,i)=>i%4===3?255:(Math.floor(i/4)*11+i%4*47)%251);
 for(const delay of[2,5,9]){const r=rig();try{const q=r.q,sg=[{address:q.base+0x100010n,length:21},{address:q.base+0x100080n,length:75}];await r.send(context());await r.send(create());await r.send(backing(11,sg));await r.send(idPacket(0x202,11,2));if(delay===2){await r.send(outerTransfer('toHost',{height:2,stride:0xffffffff,layerStride:0xffffffff}),0x1205);records.push({label:'explicit layer stride multiplication overflow rejects'});}
  const up=q.enqueue(outerTransfer('toHost',{fence:0x8000000000000001n}));q.kick();q.run();q.write(sg[0].address,texels.slice(0,21));q.write(sg[1].address,texels.slice(21));const originalEvent=r.callbackEvents.at(-1),pendingState=q.vm.submitState();eq(pendingState.pending.byteLength,hex(72),'pending transfer diagnostic length');eq(pendingState.pending.backingEntries,2,'pending SG diagnostic count');records.push({label:'pending transfer canonical state',pendingState});wasmMemory.grow(1);eq(originalEvent.kind,'transfer','original callback survives growth');await r.drain();q.check(up);q.vm.writeMmio(0x64,1);
  const rangeStart=q.base+0x100000n,before=new Uint8Array(256).fill(0x67);q.write(rangeStart,before);const read=q.enqueue(outerTransfer('fromHost',{x:1,y:1,width:2,height:2,offset:18n,stride:19,fence:0xffffffffffffffffn}));q.kick();q.run();r.oracle.delayWaits(delay);
  // Descriptor and original request mutations cannot redirect the admitted head.
  q.descriptor(read.head+1,q.base+0x90000n,24,2);q.write(read.src,new Uint8Array(read.request.length).fill(0xff));q.write(rangeStart+0x60n,Uint8Array.of(0x39));before[0x60]=0x39;
  await r.drain();const dense=Uint8Array.from([...texels.slice(20,28),...texels.slice(36,44)]),addresses=dirtyAddresses(sg,{offset:18n,rowBytes:8,rowStride:19,rowCount:2},q.base,q.base+4194304n),expected=expectedScatter(before,rangeStart,addresses,dense);eq([...q.read(rangeStart,256)],[...expected],'literal GPU output only dirty physical bytes');eq([...q.read(q.base+0x90000n,24)],Array(24).fill(0),'rewritten response descriptor ignored');const record=q.check(read);records.push({label:'literal SG and owned reply',delay,record,exchanges:r.exchanges,completions:r.completions,destination:[...expected]});
  // Embedded upload/read use the same actual DMA; old response descriptor no longer matters.
  q.write(sg[0].address,texels.slice(0,21));q.write(sg[1].address,texels.slice(21));await r.send(submit(embedded(1),{fence:7n}));await r.send(submit(embedded(2,{x:1,y:1,width:2,height:2,offset:18,stride:19}),{fence:7n}));
 }finally{r.cleanup();}}
 // One head admits at a time; high-bit duplicate fences never become identities.
 {const r=rig();try{const q=r.q;await r.send(context());const list=[];for(let i=0;i<100;i++)list.push(q.enqueue(submit(Uint8Array.of(44,0,0,0),{fence:[0xffffffffffffffffn,3n,3n,0n,0x8000000000000001n][i%5]})));const destroy=q.enqueue(header(0x201,{flags:0,context:2}));q.kick();q.run();eq(r.callbackEvents.filter(e=>e.type==='beginJob').length,1,'only one host job admitted');eq(q.usedIndex(),1,'pending first head not published');const pendingState=q.vm.submitState();eq(pendingState.pending.byteLength,hex(4),'pending command diagnostic length');records.push({label:'pending command canonical state',pendingState});r.oracle.delayWaits(7);await r.drain();const responses=list.map(e=>q.check(e));q.check(destroy);eq(r.callbackEvents.at(-1).type,'destroyContext','destroy follows 100 completions');eq(r.completions.length,100,'exactly 100 completions');records.push({label:'100 fenced heads and destroy',responses,completions:r.completions});}finally{r.cleanup();}}
 // Callbacks after reset/configuration changes cannot touch replacement rings/RAM.
 for(const reset of[true,false]){const r=rig();try{const q=r.q;await r.send(context());const entry=q.enqueue(submit(new Uint8Array(),{fence:9n}));q.kick();q.run();await r.pump();const key=q.vm.submitInspect().active,oldRing=[...q.read(q.used,2056)],oldResponse=[...q.read(entry.dst,64)];if(reset)q.vm.writeMmio(0x70,0);else{q.vm.writeMmio(0x44,0);q.vm.writeMmio(0x44,1);q.run();}throws(()=>q.vm.complete(key.epoch,key.sequence,hex(0),0,true,0,0),'late callback after revocation');eq([...q.read(q.used,2056)],oldRing,'late callback old ring unchanged');eq([...q.read(entry.dst,64)],oldResponse,'late callback old response unchanged');if(!reset)q.vm.writeMmio(0x70,0);q.configure();await r.send(context());await r.send(submit(new Uint8Array(),{fence:9n}));throws(()=>q.vm.complete(key.epoch,key.sequence,hex(0),0,true,0,0),'old epoch after identical reuse');records.push({label:'reset/configuration identity',reset});}finally{r.cleanup();}}
 // Rejected exchanges are atomic and do not consume the next valid sequence.
 {const r=rig();try{const q=r.q,sg=[{address:q.base+0x120000n,length:21},{address:q.base+0x121000n,length:75}];await r.send(context());await r.send(create());await r.send(backing(11,sg));await r.send(idPacket(0x202,11,2));q.write(sg[0].address,texels.slice(0,21));q.write(sg[1].address,texels.slice(21));const entry=q.enqueue(submit(embedded(1),{fence:0xfedcba9876543210n}));q.kick();q.run();const event=r.callbackEvents.at(-1),resource=event.resources.find(x=>x.identity.id===11),args=[event.epoch,event.sequence,hex(1),11,resource.identity.generation,resource.backing.generation,hex(0),64,64,1],before=[...q.read(sg[0].address,21),...q.read(sg[1].address,75)],state=q.vm.submitInspect();
  for(const [slot,value,label]of[[0,hex(0),'wrong epoch'],[1,hex(0),'wrong request'],[2,hex(2),'skipped exchange'],[4,hex(0),'wrong storage generation'],[5,hex(0),'wrong backing generation'],[6,hex(0xffffffffffffffffn),'full u64 overflow'],[7,65,'oversized dense row'],[8,63,'overlapping logical row'],[9,0xffffffff,'row count overflow']]){const altered=args.slice();altered[slot]=value;throws(()=>q.vm.scatterOutput(...altered,new Uint8Array(64)),label);eq([...q.read(sg[0].address,21),...q.read(sg[1].address,75)],before,label+' no partial write');eq(q.vm.submitInspect(),state,label+' exchange not consumed');}
  throws(()=>q.vm.scatterOutput(...args,new Uint8Array(63)),'short dense output');throws(()=>q.vm.complete(event.epoch,event.sequence,hex(1),0,true,0,0),'completion cannot skip exchange');throws(()=>q.vm.complete(event.epoch,event.sequence,hex(0),0,false,0,0),'success without GPU completion');
  const raw=event.commands.slice();wasmMemory.grow(2);eq([...event.commands],[...raw],'raw original callback bytes survive Wasm growth');q.write(entry.src,new Uint8Array(entry.request.length).fill(0xa2));await r.drain();q.check(entry);const used=q.usedIndex();throws(()=>q.vm.gatherInput(...args),'duplicate consumed gather');eq(q.usedIndex(),used,'stale gather no publication');records.push({label:'exchange validation and raw Wasm ownership',generation:resource.identity.generation,backingGeneration:resource.backing.generation});
 }finally{r.cleanup();}}
 // Literal malformed wire and incomplete reply capacity cannot begin host work.
 {const r=rig();try{const q=r.q;await r.send(context());const malformed=[submit(Uint8Array.of(255,0,0,0)),submit(Uint8Array.of(44)),outerTransfer('toHost',{offset:0xffffffffffffffffn})];const surplus=new Uint8Array(36);surplus.set(submit(new Uint8Array()));malformed.push(surplus);const reserved=submit(new Uint8Array());reserved[28]=1;malformed.push(reserved);for(const request of malformed){const e=q.enqueue(request);q.kick();await r.drain();const response=decodeHeader(q.read(e.dst,24));eq(response.type>=0x1200&&response.type<=0x1205,true,'malformed wire structured error');q.check(e,response.type);records.push({label:'malformed wire',request:[...request],response});}const count=r.callbackEvents.filter(e=>e.type==='beginJob').length,e=q.enqueue(submit(new Uint8Array()),23);q.kick();await r.drain();eq(r.callbackEvents.filter(e=>e.type==='beginJob').length,count,'short reply never invokes host');eq([...q.read(e.dst,64)],Array(64).fill(0xa7),'short response untouched');eq(get32(q.read(q.used+4n+BigInt(e.n*8),8),4),0,'short reply used length zero');await r.send(submit(new Uint8Array()),0x1100);
 }finally{r.cleanup();}}
 // Later heads stay guest-owned; detach cannot overtake a pending upload.
 {const r=rig();try{const q=r.q,sg=[{address:q.base+0x140000n,length:64}];await r.send(context());await r.send(context(3));await r.send(create());eq(r.host.bridge.inspect().resources[0].backing,null,'unattached diagnostic identity');await r.send(backing(11,sg));await r.send(idPacket(0x202,11,2));q.write(sg[0].address,texels);const up=q.enqueue(outerTransfer('toHost',{fence:31n})),detach=q.enqueue(idPacket(0x107,11)),read=q.enqueue(outerTransfer('fromHost',{fence:30n})),later=q.enqueue(submit(Uint8Array.of(255,0,0,0),{fence:31n,context:3}));q.kick();q.run();eq(r.callbackEvents.at(-1).type,'beginJob','first job parks before detach');const replacement=submit(Uint8Array.of(44,0,0,0),{fence:31n,context:3});q.write(later.src,replacement);later.request=replacement;r.oracle.delayWaits(6);await r.drain();q.check(up);q.check(detach);q.check(read,0x1205);q.check(later);const previous=r.callbackEvents.find(e=>e.type==='createResource').resource;await r.send(idPacket(0x102,11));await r.send(create());const recreated=r.callbackEvents.filter(e=>e.type==='createResource').at(-1).resource;eq(previous.generation===recreated.generation,false,'resource reuse has fresh generation');records.push({label:'queued detach, later mutation, contexts and ID reuse',previous,recreated,responses:[up,detach,read,later].map(e=>decodeHeader(q.read(e.dst,24)))});}finally{r.cleanup();}}
 // Readable descriptor holes reject header and payload gather without a host callback.
 {const r=rig();try{const q=r.q;await r.send(context());for(const [wire,split,label]of[[submit(new Uint8Array()),24,'split submit header hole'],[submit(Uint8Array.of(44,0,0,0)),32,'submit payload hole'],[outerTransfer('toHost'),24,'split transfer header hole']]){const e=q.enqueue(wire),before=r.callbackEvents.length;q.descriptor(e.head,e.src,split,1,e.head+2);q.descriptor(e.head+2,q.base+4194304n,wire.length-split,1,e.head+1);q.kick();q.run();eq(q.usedIndex(),e.n,label+' unpublishable descriptor not consumed');eq(Boolean(q.vm.readMmio(0x70)&64),true,label+' transport requires reset');eq(r.callbackEvents.length,before,label+' never reaches host');records.push({label,transportRejectedBeforeAdmission:true});q.vm.writeMmio(0x70,0);q.configure();await r.send(context());}await r.send(header(0x207),0x1205);}finally{r.cleanup();}}
 // Cached queue reconstruction and unpublishable response guards.
 {const r=rig();try{const q=r.q;await r.send(context());q.vm.writeMmio(0x38,128);q.write(q.avail,new Uint8Array(520));q.write(q.used,new Uint8Array(2056));q.next=0;await r.send(context(3));const e=q.enqueue(submit(new Uint8Array())),count=r.callbackEvents.length;q.descriptor(e.head+1,q.base+4194304n,24,2);q.kick();q.run();eq(r.callbackEvents.length,count,'invalid response RAM prevents callback');eq(q.usedIndex(),1,'unwritable response cannot publish used');eq(Boolean(q.vm.readMmio(0x70)&64),true,'unwritable response requests reset');records.push({label:'queue cache rebuild and response RAM rejection'});}finally{r.cleanup();}}
 // A terminal callback failure poisons Rust admission until reset.
 {const r=rig();try{const q=r.q;await r.send(context());r.hooks.callback=event=>event.type==='beginJob'?{ok:false,error:{code:'bridge-poisoned',message:'verifier terminal callback error'}}:r.host.bridge.apply(event);await r.send(submit(new Uint8Array()),0x1200);const before=r.callbackEvents.length;await r.send(submit(new Uint8Array()),0x1200);eq(r.callbackEvents.length,before,'poisoned core rejects new admission before callback');delete r.hooks.callback;q.vm.writeMmio(0x70,0);q.configure();await r.send(context());await r.send(submit(new Uint8Array()));records.push({label:'core poison rejects next admission and reset recovers'});}finally{r.cleanup();}}
 // A non-Error host exception receives bounded fallback diagnostics.
 {const r=rig();try{await r.send(context());r.hooks.afterComplete=()=>{delete r.hooks.afterComplete;throw 17;};const e=r.q.enqueue(submit(new Uint8Array()));r.q.kick();r.q.run();let answer;for(let i=0;i<100;i++){answer=await r.pump();if(!answer.ok)break;}eq(answer.ok,false,'non-Error capability exception fails explicitly');eq(r.host.bridge.inspect().lastFailure.message,'Host exchange failed.','non-Error fallback message');r.q.run();r.q.check(e);records.push({label:'non-Error post-commit host exception'});}finally{r.cleanup();}}
 // Probe a trusted completion capability throwing after it posts a valid success.
 {const r=rig();try{const q=r.q;await r.send(context());r.hooks.afterComplete=()=>{delete r.hooks.afterComplete;throw Error('verifier exception after accepted completion post');};const entry=q.enqueue(submit(new Uint8Array(),{fence:0x8000000000000001n}));q.kick();q.run();let answer;for(let i=0;i<100;i++){answer=await r.pump();if(!answer.ok)break;}eq(answer.ok,false,'post-then-throw is explicit host failure');q.run();eq(decodeHeader(q.read(entry.dst,24)).type,0x1100,'accepted final post is the commit point');eq(r.host.bridge.inspect().poisoned,true,'post wrapper failure still poisons bridge');records.push({label:'completion post then throw observation',bridge:r.host.bridge.inspect(),mailbox:q.vm.submitInspect(),response:decodeHeader(q.read(entry.dst,24)),used:q.usedIndex()});}finally{r.cleanup();}}
 return{status:'passed',assertions,turns,records,events,glEvents:oracles.map(o=>o.events)};
}
