import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {createServer} from 'node:http';
const repo=process.cwd(),out=path.dirname(fileURLToPath(import.meta.url)),hash=b=>createHash('sha256').update(b).digest('hex');
const sources=['renderer/virgl-command/decoder.mjs','renderer/virgl-command/resources.mjs','renderer/virgl-command/state.mjs','renderer/virgl-command/control-bridge.mjs','renderer/virgl-shader/index.mjs','renderer/virgl-shader/build/wasm/virgl-shader.mjs','renderer/virgl-shader/build/wasm/virgl-shader.wasm','target/virgl-submit/pkg/wasm_vm_wasm.js','target/virgl-submit/pkg/wasm_vm_wasm_bg.wasm'];
const variant=process.argv[2]??'baseline';assert.ok(['baseline','early-readback','wrong-completion'].includes(variant));const prefix=variant==='baseline'?'attack':variant;
const report={variant,task:'E6-T11b2',gitHead:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),status:'running',sources:[],started:new Date().toISOString(),errors:{console:[],page:[],request:[]}};let browser,server;
try{
 const modules=new Map();
 for(const name of sources){const bytes=await fs.readFile(path.join(repo,name));modules.set('/'+name,bytes);report.sources.push({path:name,sha256:hash(bytes)});}
 for(const name of ['attack-cases.mjs','wire-oracle.mjs','run-attacks.mjs','predictions.md']){const bytes=await fs.readFile(path.join(out,name));report.sources.push({path:path.relative(repo,path.join(out,name)),sha256:hash(bytes)});if(name.endsWith('.mjs'))modules.set('/'+name,bytes);}
 const oracle='evidence/virgl-async/verifier/gl-oracle.mjs',oracleBytes=await fs.readFile(path.join(repo,oracle));modules.set('/gl-oracle.mjs',oracleBytes);report.sources.push({path:oracle,sha256:hash(oracleBytes)});
 for(const entry of await fs.readdir(path.join(repo,'target/virgl-submit/pkg/snippets'),{withFileTypes:true}).catch(()=>[])){if(entry.isDirectory())for(const file of await fs.readdir(path.join(repo,'target/virgl-submit/pkg/snippets',entry.name))){const name='target/virgl-submit/pkg/snippets/'+entry.name+'/'+file,bytes=await fs.readFile(path.join(repo,name));modules.set('/'+name,bytes);report.sources.push({path:name,sha256:hash(bytes)});}}
 if(variant!=='baseline'){const source=variant==='early-readback'?'renderer/virgl-command/resources.mjs':'renderer/virgl-command/control-bridge.mjs',before=modules.get('/'+source).toString(),anchor=variant==='early-readback'?'entry.ready = status !== gl.TIMEOUT_EXPIRED; check();':'transport.complete(job.epoch, job.sequence, job.exchangeSequence, code, gpuComplete, appliedCommands, draws)',replacement=variant==='early-readback'?'entry.ready = true; check();':'transport.complete(job.epoch, nextHex(job.sequence), job.exchangeSequence, code, gpuComplete, appliedCommands, draws)';assert.equal(before.split(anchor).length,2);const after=Buffer.from(before.replace(anchor,replacement));modules.set('/'+source,after);report.mutation={source,anchor,replacement,originalSha256:hash(Buffer.from(before)),servedSha256:hash(after)};}
 modules.set('/',Buffer.from('<!doctype html><title>Independent submission verification</title><h1>Independent VirtIO submission attacks</h1><canvas id="gpu" width="64" height="64"></canvas><pre id="result">Running</pre>'));
 server=createServer((req,res)=>{if(req.url==='/favicon.ico'){res.writeHead(204).end();return;}const bytes=modules.get(req.url);if(!bytes){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':req.url.endsWith('.wasm')?'application/wasm':req.url.endsWith('.js')||req.url.endsWith('.mjs')?'text/javascript':'text/html','Cache-Control':'no-store','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Embedder-Policy':'require-corp'}).end(bytes);});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const{chromium}=await import(pathToFileURL(path.join(repo,'web/node_modules/playwright/index.mjs')));browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:false,args:['--enable-gpu']});const bs=await browser.newBrowserCDPSession();report.browser={version:browser.version(),system:await bs.send('SystemInfo.getInfo'),commandLine:await bs.send('Browser.getBrowserCommandLine')};assert.equal(report.browser.system.gpu.featureStatus.webgl2??report.browser.system.gpu.featureStatus.webgl,'enabled');
 const context=await browser.newContext({viewport:{width:1100,height:920}}),page=await context.newPage();page.on('console',m=>{if(m.type()==='error')report.errors.console.push(m.text());});page.on('pageerror',e=>report.errors.page.push(e.message));page.on('requestfailed',r=>report.errors.request.push(r.url()));await page.goto(`http://127.0.0.1:${server.address().port}/`);
 const cdp=await context.newCDPSession(page);await cdp.send('Profiler.enable');await cdp.send('Profiler.startPreciseCoverage',{callCount:true,detailed:true});
 report.result=await page.evaluate(async()=>{try{const wasm=await import('/target/virgl-submit/pkg/wasm_vm_wasm.js'),exports=await wasm.default(),{runAttacks}=await import('/attack-cases.mjs');const value=await runAttacks({WasmVirglSubmitProof:wasm.WasmVirglSubmitProof,wasmMemory:exports.memory});document.querySelector('#result').textContent=JSON.stringify({status:value.status,assertions:value.assertions,turns:value.turns,records:value.records.length,observations:value.records.filter(r=>r.label==='completion post then throw observation')},null,2);return value;}catch(e){document.querySelector('#result').textContent=e.stack;return{status:'failed',error:{message:e.message,stack:e.stack}};}});
 const coverage=await cdp.send('Profiler.takePreciseCoverage'),scripts=coverage.result.filter(s=>['/control-bridge.mjs','/resources.mjs','/state.mjs'].some(x=>s.url.endsWith(x)));await fs.writeFile(path.join(out,prefix+'-coverage.json'),JSON.stringify({scripts},null,2)+'\n');report.coverageSha256=hash(await fs.readFile(path.join(out,prefix+'-coverage.json')));await page.screenshot({path:path.join(out,prefix+'.png'),fullPage:true});report.screenshotSha256=hash(await fs.readFile(path.join(out,prefix+'.png')));if(variant==='baseline')assert.equal(report.result.status,'passed',report.result.error?.message);else{assert.equal(report.result.status,'failed');const expected=variant==='early-readback'?/CPU collection preceded matching staging fence signal/:/completion identity must match active head/;assert.match(report.result.error.message,expected);report.control='caught intended sequencing violation';}assert.deepEqual(report.errors,{console:[],page:[],request:[]});for(const source of report.sources)assert.equal(hash(await fs.readFile(path.join(repo,source.path))),source.sha256,'source drift '+source.path);report.status='passed';
}catch(e){report.status='failed';report.error={message:e.message,stack:e.stack};process.exitCode=1;}finally{report.finished=new Date().toISOString();await fs.writeFile(path.join(out,variant==='baseline'?'attacks.json':variant+'.json'),JSON.stringify(report,null,2)+'\n');await browser?.close();if(server)await new Promise(resolve=>server.close(resolve));}
console.log(JSON.stringify({status:report.status,assertions:report.result?.assertions,records:report.result?.records?.length,error:report.error},null,2));
