//! Actual generated FDIV.S modules with interpreter and independent literal goldens.
use wasm_vm_core::Machine;
use wasm_vm_core::bus::{Bus, mmap::DRAM_BASE};
use wasm_vm_core::csr::{CsrOp, FFLAGS, FRM, MSTATUS};
use wasm_vm_core::decode::decode;
use wasm_vm_core::decode_c::expand_c;
use wasm_vm_core::dispatch::{DecodedBlock, MicroOp};
use wasm_vm_core::hart::{Exception, Hart, Trap};
use wasm_vm_core::jit::{CompiledBlockExecutor, ExitCode, JitExit};
use wasm_vm_core::mmio::SystemBus;
use wasm_vm_core::ram::Ram;

pub type Factory = fn(&Machine) -> Box<dyn CompiledBlockExecutor>;
pub const BAD: u64 = 0x5000_0000;
pub const fn boxed(bits: u32) -> u64 {
    0xffff_ffff_0000_0000 | bits as u64
}
pub fn division(rm: u32, rd: u32, rs1: u32, rs2: u32) -> u32 {
    (12 << 25) | (rs2 << 20) | (rs1 << 15) | (rm << 12) | (rd << 7) | 0x53
}
pub fn block(pc: u64, parcels: &[u32]) -> DecodedBlock {
    let ops: Vec<_> = parcels
        .iter()
        .map(|&raw| {
            let short = raw & 3 != 3;
            MicroOp {
                raw,
                len: if short { 2 } else { 4 },
                instr: decode(if short {
                    expand_c(raw as u16).unwrap()
                } else {
                    raw
                })
                .unwrap(),
            }
        })
        .collect();
    let len = ops.iter().map(|op| u64::from(op.len)).sum();
    DecodedBlock::new(pc, ops, len)
}
pub fn fs(h: &mut Hart, value: u64) {
    h.csr
        .access(MSTATUS, CsrOp::Write, value << 13, false, false, 0)
        .unwrap();
}
pub fn execute(
    e: &mut dyn CompiledBlockExecutor,
    m: &mut Machine,
    pc: u64,
    fuel: u64,
    chain: bool,
) -> JitExit {
    let ptr: *mut Machine = m;
    // The machine owns the disjoint hart and bus throughout the synchronous call.
    unsafe {
        e.execute_with_budget(pc, (*ptr).hart_mut(), (*ptr).bus_mut(), fuel, fuel, chain)
            .unwrap()
    }
}
fn seed(m: &mut Machine, enabled: u64, mode: u8, flags: u8) {
    let h = m.hart_mut();
    for r in 0..32 {
        h.regs.write(r, 0x1234_5678_0000_0000 | u64::from(r));
        h.fregs.write_raw(r, 0x0abc_def0_0000_0000 | u64::from(r));
    }
    h.regs.pc = 0x4000_2000;
    h.regs.write(8, BAD);
    h.resv = Some((DRAM_BASE + 0x6000, 8));
    fs(h, enabled);
    h.csr.fflags = flags;
    h.csr.frm = mode;
}
fn compare(e: &mut dyn CompiledBlockExecutor, m: &mut Machine, b: &DecodedBlock) -> u64 {
    let h = m.hart();
    let mut oracle = Hart {
        regs: h.regs.clone(),
        fregs: h.fregs.clone(),
        csr: h.csr.clone(),
        resv: h.resv,
        ..Hart::default()
    };
    let mut bus = SystemBus::new(Ram::new(64 * 1024).unwrap());
    let mut trap = None;
    let mut retired = 0;
    for op in &b.ops {
        match oracle.exec_oracle(&mut bus, op.instr, op.len.into(), op.raw.into()) {
            Ok(_) => retired += 1,
            Err(t) => {
                trap = Some(t);
                break;
            }
        }
    }
    let exit = execute(e, m, b.phys_start, 256, false);
    let actual_trap = if exit.code == ExitCode::IllegalInstruction {
        Some(Trap {
            cause: Exception::IllegalInstruction,
            tval: exit.exit_info,
        })
    } else {
        exit.trap
    };
    assert_eq!(
        actual_trap, trap,
        "actual cause and original instruction bits"
    );
    assert_eq!(
        exit.next_pc, oracle.regs.pc,
        "virtual PC / completed prefix"
    );
    if exit.retired != 0 {
        assert_eq!(exit.retired, retired);
    }
    m.hart_mut().regs.pc = exit.next_pc;
    let mut digest = 0xcbf2_9ce4_8422_2325_u64;
    for r in 0..32 {
        assert_eq!(m.hart().regs.read(r), oracle.regs.read(r), "x{r}");
        assert_eq!(
            m.hart().fregs.read_raw(r),
            oracle.fregs.read_raw(r),
            "f{r} architectural result"
        );
        for word in [m.hart().regs.read(r), m.hart().fregs.read_raw(r)] {
            for byte in word.to_le_bytes() {
                digest = (digest ^ u64::from(byte)).wrapping_mul(0x100_0000_01b3);
            }
        }
    }
    assert_eq!(m.hart().csr.fflags, oracle.csr.fflags, "sticky flags");
    assert_eq!(m.hart().csr.frm, oracle.csr.frm, "rounding mode unchanged");
    assert_eq!(m.hart().resv, oracle.resv);
    let status = m.hart_mut().csr.read(MSTATUS);
    assert_eq!(status, oracle.csr.read(MSTATUS));
    for word in [
        exit.next_pc,
        retired,
        status,
        u64::from(m.hart().csr.fflags),
        u64::from(m.hart().csr.frm),
        trap.map_or(0, |t| t.tval),
    ] {
        for byte in word.to_le_bytes() {
            digest = (digest ^ u64::from(byte)).wrapping_mul(0x100_0000_01b3);
        }
    }
    digest
}

// Independent exact-rational goldens, generated by derive-goldens.py.
// Arrays are [RNE, RTZ, RDN, RUP, RMM]; flags include unbounded-exponent tininess.
const GOLDENS: &[(u64, u64, [u32; 5], [u8; 5])] = &[
    (
        0xffffffff3f800000,
        0xffffffff40400000,
        [0x3eaaaaab, 0x3eaaaaaa, 0x3eaaaaaa, 0x3eaaaaab, 0x3eaaaaab],
        [1, 1, 1, 1, 1],
    ),
    (
        0xffffffffbf800000,
        0xffffffff40400000,
        [0xbeaaaaab, 0xbeaaaaaa, 0xbeaaaaab, 0xbeaaaaaa, 0xbeaaaaab],
        [1, 1, 1, 1, 1],
    ),
    (
        0xffffffff40400000,
        0xffffffff40000000,
        [0x3fc00000, 0x3fc00000, 0x3fc00000, 0x3fc00000, 0x3fc00000],
        [0, 0, 0, 0, 0],
    ),
    (
        0xffffffff3f800000,
        0xffffffffc0000000,
        [0xbf000000, 0xbf000000, 0xbf000000, 0xbf000000, 0xbf000000],
        [0, 0, 0, 0, 0],
    ),
    (
        0xffffffff00000000,
        0xffffffffbf800000,
        [0x80000000, 0x80000000, 0x80000000, 0x80000000, 0x80000000],
        [0, 0, 0, 0, 0],
    ),
    (
        0xffffffff80000000,
        0xffffffffbf800000,
        [0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000],
        [0, 0, 0, 0, 0],
    ),
    (
        0xffffffff3f800000,
        0xffffffff00000000,
        [0x7f800000, 0x7f800000, 0x7f800000, 0x7f800000, 0x7f800000],
        [8, 8, 8, 8, 8],
    ),
    (
        0xffffffffbf800000,
        0xffffffff00000000,
        [0xff800000, 0xff800000, 0xff800000, 0xff800000, 0xff800000],
        [8, 8, 8, 8, 8],
    ),
    (
        0xffffffff7f800000,
        0xffffffff00000000,
        [0x7f800000, 0x7f800000, 0x7f800000, 0x7f800000, 0x7f800000],
        [0, 0, 0, 0, 0],
    ),
    (
        0xffffffffff800000,
        0xffffffff80000000,
        [0x7f800000, 0x7f800000, 0x7f800000, 0x7f800000, 0x7f800000],
        [0, 0, 0, 0, 0],
    ),
    (
        0xffffffff00000000,
        0xffffffff00000000,
        [0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000],
        [16, 16, 16, 16, 16],
    ),
    (
        0xffffffff80000000,
        0xffffffff00000000,
        [0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000],
        [16, 16, 16, 16, 16],
    ),
    (
        0xffffffff7f800000,
        0xffffffff7f800000,
        [0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000],
        [16, 16, 16, 16, 16],
    ),
    (
        0xffffffff3f800000,
        0xffffffff7f800000,
        [0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000],
        [0, 0, 0, 0, 0],
    ),
    (
        0xffffffffbf800000,
        0xffffffff7f800000,
        [0x80000000, 0x80000000, 0x80000000, 0x80000000, 0x80000000],
        [0, 0, 0, 0, 0],
    ),
    (
        0xffffffff7f800000,
        0xffffffffbf800000,
        [0xff800000, 0xff800000, 0xff800000, 0xff800000, 0xff800000],
        [0, 0, 0, 0, 0],
    ),
    (
        0xffffffff7fc01234,
        0xffffffff3f800000,
        [0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000],
        [0, 0, 0, 0, 0],
    ),
    (
        0xffffffffff800001,
        0xffffffff3f800000,
        [0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000],
        [16, 16, 16, 16, 16],
    ),
    (
        0xffffffff3f800000,
        0xffffffff7f800001,
        [0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000],
        [16, 16, 16, 16, 16],
    ),
    (
        0xffffffff00800000,
        0xffffffff40000000,
        [0x00400000, 0x00400000, 0x00400000, 0x00400000, 0x00400000],
        [0, 0, 0, 0, 0],
    ),
    (
        0xffffffff00000001,
        0xffffffff40000000,
        [0x00000000, 0x00000000, 0x00000000, 0x00000001, 0x00000001],
        [3, 3, 3, 3, 3],
    ),
    (
        0xffffffff80000001,
        0xffffffff40000000,
        [0x80000000, 0x80000000, 0x80000001, 0x80000000, 0x80000001],
        [3, 3, 3, 3, 3],
    ),
    (
        0xffffffff00000003,
        0xffffffff40000000,
        [0x00000002, 0x00000001, 0x00000001, 0x00000002, 0x00000002],
        [3, 3, 3, 3, 3],
    ),
    (
        0xffffffff00ffffff,
        0xffffffff40000000,
        [0x00800000, 0x007fffff, 0x007fffff, 0x00800000, 0x00800000],
        [3, 3, 3, 3, 3],
    ),
    (
        0xffffffff80ffffff,
        0xffffffff40000000,
        [0x80800000, 0x807fffff, 0x80800000, 0x807fffff, 0x80800000],
        [3, 3, 3, 3, 3],
    ),
    (
        0xffffffff00800000,
        0xffffffff3f800001,
        [0x007fffff, 0x007fffff, 0x007fffff, 0x00800000, 0x007fffff],
        [3, 3, 3, 3, 3],
    ),
    (
        0xffffffff007fffff,
        0xffffffff3f7fffff,
        [0x007fffff, 0x007fffff, 0x007fffff, 0x00800000, 0x007fffff],
        [3, 3, 3, 3, 3],
    ),
    (
        0xffffffff00000001,
        0xffffffff34000001,
        [0x007fffff, 0x007fffff, 0x007fffff, 0x00800000, 0x007fffff],
        [3, 3, 3, 3, 3],
    ),
    (
        0xffffffff7f7fffff,
        0xffffffff3f000000,
        [0x7f800000, 0x7f7fffff, 0x7f7fffff, 0x7f800000, 0x7f800000],
        [5, 5, 5, 5, 5],
    ),
    (
        0xffffffffff7fffff,
        0xffffffff3f000000,
        [0xff800000, 0xff7fffff, 0xff800000, 0xff7fffff, 0xff800000],
        [5, 5, 5, 5, 5],
    ),
    (
        0xffffffff7f7fffff,
        0xffffffff3f7fffff,
        [0x7f800000, 0x7f7fffff, 0x7f7fffff, 0x7f800000, 0x7f800000],
        [5, 5, 5, 5, 5],
    ),
    (
        0xffffffffff7fffff,
        0xffffffff3f7fffff,
        [0xff800000, 0xff7fffff, 0xff800000, 0xff7fffff, 0xff800000],
        [5, 5, 5, 5, 5],
    ),
    (
        0xffffffff7f7ffffe,
        0xffffffff3f7fffff,
        [0x7f7fffff, 0x7f7ffffe, 0x7f7ffffe, 0x7f7fffff, 0x7f7fffff],
        [1, 1, 1, 1, 1],
    ),
    (
        0xffffffffff7ffffe,
        0xffffffff3f7fffff,
        [0xff7fffff, 0xff7ffffe, 0xff7fffff, 0xff7ffffe, 0xff7fffff],
        [1, 1, 1, 1, 1],
    ),
    (
        0xffffffff00000001,
        0xffffffff00000001,
        [0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000],
        [0, 0, 0, 0, 0],
    ),
    (
        0xffffffff00800000,
        0xffffffff7f7fffff,
        [0x00000000, 0x00000000, 0x00000000, 0x00000001, 0x00000000],
        [3, 3, 3, 3, 3],
    ),
    (
        0xffffffff7f7fffff,
        0xffffffff00000001,
        [0x7f800000, 0x7f7fffff, 0x7f7fffff, 0x7f800000, 0x7f800000],
        [5, 5, 5, 5, 5],
    ),
    (
        0x123456787f800001,
        0xffffffff3f800000,
        [0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000],
        [0, 0, 0, 0, 0],
    ),
    (
        0xffffffff3f800000,
        0xfffffffeff800001,
        [0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000, 0x7fc00000],
        [0, 0, 0, 0, 0],
    ),
];

pub fn corpus(make: Factory) {
    let mut m = Machine::new(64 * 1024);
    let mut e = make(&m);
    let mut cases = 0_u64;
    let mut digest = 0_u64;
    let mut blocks = 0_u64;
    for rm in 0..8 {
        for rd in [0, 5, 31] {
            let b = block(
                DRAM_BASE + blocks * 0x100,
                &[0x0305, division(rm, rd, 0, 31), 0x0013_8393],
            );
            blocks += 1;
            e.install(&b);
            assert!(e.is_compiled(b.phys_start));
            for enabled in 0..=3 {
                for mode in 0..8 {
                    for &(a, z, results, flags) in GOLDENS {
                        let prior = (cases as u8).wrapping_mul(7) & 31;
                        seed(&mut m, enabled, mode, prior);
                        m.hart_mut().fregs.write_raw(0, a);
                        m.hart_mut().fregs.write_raw(31, z);
                        digest ^= compare(e.as_mut(), &mut m, &b).rotate_left((cases % 64) as u32);
                        let resolved = if rm == 7 { u32::from(mode) } else { rm };
                        if enabled != 0 && resolved <= 4 {
                            assert_eq!(
                                m.hart().fregs.read_raw(rd as u8),
                                boxed(results[resolved as usize]),
                                "literal division result rm={rm} frm={mode} a={a:x} b={z:x}"
                            );
                            assert_eq!(
                                m.hart().csr.fflags,
                                prior | flags[resolved as usize],
                                "literal division flags rm={rm} frm={mode} a={a:x} b={z:x} prior={prior}"
                            );
                            assert_eq!(m.hart().csr.fs(), 3);
                        }
                        cases += 1;
                    }
                }
            }
            let mut random = 0x7128_f94c_e604_a35b_u64 ^ blocks;
            for n in 0..32 {
                random ^= random << 13;
                random ^= random >> 7;
                random ^= random << 17;
                let a = if n % 11 == 0 {
                    random
                } else {
                    boxed(random as u32)
                };
                random ^= random << 13;
                random ^= random >> 7;
                random ^= random << 17;
                seed(&mut m, 1 + n % 3, (n % 8) as u8, (n % 32) as u8);
                m.hart_mut().fregs.write_raw(0, a);
                m.hart_mut().fregs.write_raw(31, boxed(random as u32));
                digest ^= compare(e.as_mut(), &mut m, &b).rotate_left((n % 64) as u32);
                cases += 1;
            }
        }
    }
    assert_eq!(cases, 30720);
    eprintln!("FP_DIVISION corpus cases={cases} register_flags_fnv={digest:016x}");
}

pub fn handoff_and_faults(make: Factory) {
    let mut m = Machine::new(64 * 1024);
    let mut e = make(&m);
    let ratio = block(DRAM_BASE, &[division(7, 5, 0, 31)]);
    let fault = block(
        DRAM_BASE + 0x100,
        &[division(0, 6, 0, 0), 0x0004_3283, division(7, 0, 0, 31)],
    );
    let invalid = block(
        DRAM_BASE + 0x200,
        &[division(0, 6, 0, 31), division(6, 5, 0, 31)],
    );
    let aliases = block(
        DRAM_BASE + 0x300,
        &[division(7, 0, 0, 0), division(7, 31, 31, 31)],
    );
    for b in [&ratio, &fault, &invalid, &aliases] {
        e.install(b);
        assert!(e.is_compiled(b.phys_start));
    }
    for phase in 0..16 {
        seed(&mut m, 2, 0, phase);
        m.hart_mut().fregs.write_raw(0, boxed(0x3f80_0000));
        m.hart_mut().fregs.write_raw(31, boxed(0x4040_0000));
        compare(e.as_mut(), &mut m, &ratio);
        assert_eq!(m.hart().fregs.read_raw(5), boxed(0x3eaa_aaab));
        assert_eq!(m.hart().csr.fflags, phase | 1);
        m.hart_mut()
            .csr
            .access(FFLAGS, CsrOp::Write, 8, false, false, 0)
            .unwrap();
        m.hart_mut()
            .csr
            .access(FRM, CsrOp::Write, 2, false, false, 0)
            .unwrap();
        m.hart_mut().regs.pc = 0x4000_2000;
        compare(e.as_mut(), &mut m, &ratio);
        assert_eq!(m.hart().fregs.read_raw(5), boxed(0x3eaa_aaaa));
        assert_eq!(m.hart().csr.fflags, 9);
        m.hart_mut()
            .csr
            .access(FFLAGS, CsrOp::Write, 8, false, false, 0)
            .unwrap();
        m.hart_mut().regs.pc = 0x4000_2000;
        compare(e.as_mut(), &mut m, &fault);
        assert_eq!(m.hart().fregs.read_raw(6), boxed(0x3f80_0000));
        assert_eq!(
            m.hart().csr.fflags,
            8,
            "exact division does not resurrect cleared NX"
        );
        assert_eq!(m.hart().regs.pc, 0x4000_2004);
        for b in [&invalid, &aliases] {
            m.hart_mut().regs.pc = 0x4000_2000;
            compare(e.as_mut(), &mut m, b);
        }
    }
    eprintln!("FP_DIVISION CSR/later-fault/invalid-prefix/aliases cases=80");
}

pub fn runloop(make: Factory) {
    use wasm_vm_core::csr::{MCAUSE, MEPC, MTVAL, MTVEC};
    let mut m = Machine::new(64 * 1024);
    let programs = [
        vec![0x0305, division(7, 5, 0, 31), 0x0010_0073],
        vec![0x0305, division(7, 5, 0, 31), 0x0010_0073],
        vec![division(7, 5, 0, 31), 0x0004_3283, 0x0010_0073],
    ];
    let mut e = make(&m);
    for (i, p) in programs.iter().enumerate() {
        let b = block(DRAM_BASE + i as u64 * 0x100, p);
        let mut pc = b.phys_start;
        for op in &b.ops {
            m.bus_mut()
                .ram_mut()
                .write_slice(pc, &op.raw.to_le_bytes()[..op.len as usize])
                .unwrap();
            pc += u64::from(op.len);
        }
        e.install(&b);
        assert!(e.is_compiled(b.phys_start));
    }
    for offset in [0x400, 0x404, 0x408] {
        m.bus_mut()
            .store32(DRAM_BASE + offset, 0x3000_2073)
            .unwrap();
    }
    m.bus_mut().store32(DRAM_BASE + 0x40c, 0x0000_006f).unwrap();
    m.set_block_cache(true);
    m.set_interrupt_batching(true);
    m.set_hotness_threshold(1);
    m.set_executor(e);
    m.set_jit(true);
    for i in 0..3 {
        let pc = DRAM_BASE + i * 0x100;
        seed(&mut m, 2, 0, 2);
        m.hart_mut().regs.pc = pc;
        m.run(4);
        seed(
            &mut m,
            if i == 0 { 0 } else { 2 },
            if i == 1 { 7 } else { 0 },
            2,
        );
        m.hart_mut().regs.pc = pc;
        m.hart_mut().fregs.write_raw(0, boxed(0x3f80_0000));
        m.hart_mut().fregs.write_raw(31, boxed(0x4040_0000));
        m.hart_mut()
            .csr
            .access(MTVEC, CsrOp::Write, DRAM_BASE + 0x400, false, false, 0)
            .unwrap();
        let before = m.executor().unwrap().retired_via_jit();
        let calls = m.executor().unwrap().executed_blocks();
        m.run(4);
        assert!(m.executor().unwrap().executed_blocks() > calls);
        assert_eq!(m.executor().unwrap().retired_via_jit() - before, 1);
        assert_eq!(m.hart_mut().csr.read(MEPC), pc + if i < 2 { 2 } else { 4 });
        assert_eq!(m.hart_mut().csr.read(MCAUSE), if i < 2 { 2 } else { 5 });
        assert_eq!(
            m.hart_mut().csr.read(MTVAL),
            if i < 2 {
                u64::from(programs[i as usize][1])
            } else {
                BAD
            }
        );
        assert_eq!(m.hart().csr.fflags, if i < 2 { 2 } else { 3 });
    }
    eprintln!("FP_DIVISION runloop FS-off/invalid-rm prefix=1 bytes=2 later-fault-flags=3");
}
