import {createVirglShaderBridge,LIMITS} from '/renderer/virgl-shader/index.mjs';
const stable=x=>JSON.stringify(x,(_,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v);
export async function run(variant='baseline'){
 let assertions=0,pixels=0;const records=[],objects=new Map();let gl;
 const check=(v,m)=>{assertions++;if(!v)throw new Error(m);};
 const eq=(a,b,m)=>check(stable(a)===stable(b),`${m}: expected ${stable(b)}, actual ${stable(a)}`);
 const digest=async x=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',typeof x==='string'?new TextEncoder().encode(x):x))).map(x=>x.toString(16).padStart(2,'0')).join('');
 try{
  const bridge=await createVirglShaderBridge(),cases=[...await (await fetch('/browser-cases.json')).json(),...await (await fetch('/supplemental-cases.json')).json()],originals=new Map();
  eq([LIMITS.registerIndex,LIMITS.temporaryRegisterIndex,LIMITS.instructions,LIMITS.tokens,LIMITS.textBytes],[7,9,128,8192,16384],'frozen limits');
  for(const c of cases){const r=bridge.translate({stage:c.stage?'fragment':'vertex',text:c.text});eq(r,c.native,`independent native/Wasm ${c.name}`);if(c.name.startsWith('original-'))originals.set(c.name.slice(9),r);}
  records.push({label:'independent native/Wasm parity',cases:cases.length,originalAccepted:[...originals.values()].filter(x=>x.ok).length});
  const canvas=document.querySelector('#gpu');canvas.width=32;canvas.height=32;gl=canvas.getContext('webgl2',{alpha:true,antialias:false,premultipliedAlpha:false,preserveDrawingBuffer:true});check(gl,'actual WebGL2');
  const ext=gl.getExtension('WEBGL_debug_renderer_info');records.push({label:'actual GPU',renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER)});
  for(const kind of ['Buffer','Texture','Framebuffer','Renderbuffer','Shader','Program','VertexArray','TransformFeedback']){
   const create=gl['create'+kind].bind(gl),remove=gl['delete'+kind].bind(gl),s=new Set();objects.set(kind,s);
   gl['create'+kind]=(...a)=>{const o=create(...a);check(o,`allocate ${kind}`);s.add(o);return o;};gl['delete'+kind]=o=>{if(o)s.delete(o);return remove(o);};
  }
  const compile=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);check(gl.getShaderParameter(s,gl.COMPILE_STATUS),'compile '+gl.getShaderInfoLog(s));return s;};
  const program=(vs,fs,tf=[])=>{const p=gl.createProgram(),v=compile(gl.VERTEX_SHADER,vs),f=compile(gl.FRAGMENT_SHADER,fs);gl.attachShader(p,v);gl.attachShader(p,f);if(tf.length)gl.transformFeedbackVaryings(p,tf,gl.INTERLEAVED_ATTRIBS);gl.linkProgram(p);check(gl.getProgramParameter(p,gl.LINK_STATUS),'link '+gl.getProgramInfoLog(p));gl.deleteShader(v);gl.deleteShader(f);return p;};
  const attr=(p,name,n,values)=>{const loc=gl.getAttribLocation(p,name);check(loc>=0,'attribute '+name);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(values),gl.STATIC_DRAW);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,n,gl.FLOAT,false,0,0);return b;};
  const tile=label=>{const img=document.createElement('img'),fig=document.createElement('figure'),cap=document.createElement('figcaption');img.src=canvas.toDataURL();img.style.width='160px';img.style.imageRendering='pixelated';cap.textContent=label;fig.append(img,cap);document.querySelector('#frames').append(fig);};
  gl.disable(gl.BLEND);gl.disable(gl.DITHER);gl.disable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.viewport(0,0,32,32);
  const quad=[-1,-1,1,-1,-1,1,-1,1,1,-1,1,1],rawVS='#version 300 es\nprecision highp float;in vec2 p;uniform vec3 u;out vec4 vso_g0;void main(){gl_Position=vec4(p,0,1);vso_g0=vec4(u,0);}',texels=[200,0,0,255,0,120,0,128,0,0,80,64,40,60,100,192],expectedTex=[[100,0,0,255],[0,60,0,128],[0,0,40,64],[20,30,50,192]];
  for(const hash of ['003270109615e05345631cf8a2273ebc1bf3d86c7590e05ddc8424c441db7605','9819066def2df1cd09f36f142fd2bc6b659395aa21bea6db7f58fbcc122c7c83']){
   const p=program(rawVS,originals.get(hash).glsl),vao=gl.createVertexArray();gl.bindVertexArray(vao);gl.useProgram(p);const b=attr(p,'p',2,quad),t=gl.createTexture();gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,2,2,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array(texels));gl.uniform1i(gl.getUniformLocation(p,'fssamp0'),0);
   for(let i=0;i<4;i++){const uv=[i%2?.75:.25,i>=2?.75:.25];gl.uniform3f(gl.getUniformLocation(p,'u'),.5,...uv);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawArrays(gl.TRIANGLES,0,6);const actual=new Uint8Array(32*32*4);gl.readPixels(0,0,32,32,gl.RGBA,gl.UNSIGNED_BYTE,actual);for(let y=4;y<28;y++)for(let x=4;x<28;x++){eq(Array.from(actual.subarray((y*32+x)*4,(y*32+x)*4+4)),expectedTex[i],`texture ${hash} texel${i} pixel${x},${y}`);pixels++;}records.push({label:'original fragment actual pixels',hash,brightness:.5,uv,expected:expectedTex[i],readbackSha256:await digest(actual)});tile(hash.slice(0,8)+' texel '+i);}
   gl.deleteBuffer(b);gl.deleteTexture(t);gl.deleteVertexArray(vao);gl.deleteProgram(p);
  }
  const affine=[[.5,.125,.25,9],[-.25,.5,-.125,8],[.125,-.25,.5,7]],matrix=[[.5,.125,.25,.125],[-.25,.5,-.125,-.25],[.125,-.25,.5,.25],[.125,.25,-.25,1]],input=[.5,-.5,.75,1],triangle=[[-1,-1,.25,1],[1,-1,.25,1],[0,1,.25,1]];
  const cross=(a,b,p)=>(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]);
  for(const [hash,constants,expected,hasGeneric] of [
   ['403b0529c632d3d2ffe4584ede810f5745e8b76ca2ab4f575e1073d8f29fcf0c',affine,[.5,-.4375,.6875,1],true],
   ['e9bc6d3b61e3cda2c215ac8b44a432e2eb1bd4891cfa921c6f914fd3fd86b551',matrix,[.59375,-.125,.3125,1.375],false]]){
   let vs=originals.get(hash).glsl;const originalGlslSha256=await digest(vs);
   if(variant==='wrong-z-swizzle'&&hasGeneric){const anchor='(in_0.yyyx)';check(vs.split(anchor).length===2,'unique z-source mutation');vs=vs.replace(anchor,'(in_0.yyxx)');records.push({label:'z-only source selector mutation',originalGlslSha256,mutatedSha256:await digest(vs),anchor,replacement:'(in_0.yyxx)'});}
   const fs=hasGeneric?'#version 300 es\nprecision highp float;in vec4 vso_g0;out vec4 color;void main(){color=vec4(vso_g0.xy,0.5,1);}':'#version 300 es\nprecision highp float;out vec4 color;void main(){color=vec4(0.25,0.75,0.5,1);}';
   const p=program(vs,fs,hasGeneric?['gl_Position','vso_g0']:['gl_Position']),vao=gl.createVertexArray();gl.bindVertexArray(vao);gl.useProgram(p);const b=attr(p,'in_0',4,input),extra=hasGeneric?attr(p,'in_1',4,[.25,.75,99,88]):null;
   const f32=new Float32Array(constants.flat()),bits=new Uint32Array(f32.buffer);gl.uniform4uiv(gl.getUniformLocation(p,'vsconst0[0]'),bits);
   const bi=gl.getUniformBlockIndex(p,'VirglBlock');check(bi!==gl.INVALID_INDEX,'system block reflected');const blockSize=gl.getActiveUniformBlockParameter(p,bi,gl.UNIFORM_BLOCK_DATA_SIZE);eq(blockSize,656,'system block byte length');const member=gl.getUniformIndices(p,['winsys_adjust_y']);eq(gl.getActiveUniforms(p,member,gl.UNIFORM_OFFSET)[0],640,'system block y offset');const ub=gl.createBuffer(),bytes=new ArrayBuffer(656);new DataView(bytes).setFloat32(640,1,true);gl.bindBuffer(gl.UNIFORM_BUFFER,ub);gl.bufferData(gl.UNIFORM_BUFFER,bytes,gl.STATIC_DRAW);gl.bindBufferBase(gl.UNIFORM_BUFFER,0,ub);gl.uniformBlockBinding(p,bi,0);
   const tf=gl.createTransformFeedback(),tb=gl.createBuffer();gl.bindTransformFeedback(gl.TRANSFORM_FEEDBACK,tf);gl.bindBuffer(gl.TRANSFORM_FEEDBACK_BUFFER,tb);gl.bufferData(gl.TRANSFORM_FEEDBACK_BUFFER,hasGeneric?32:16,gl.STREAM_READ);gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,tb);gl.enable(gl.RASTERIZER_DISCARD);gl.beginTransformFeedback(gl.POINTS);gl.drawArrays(gl.POINTS,0,1);gl.endTransformFeedback();gl.disable(gl.RASTERIZER_DISCARD);const captured=new Float32Array(hasGeneric?8:4);gl.getBufferSubData(gl.TRANSFORM_FEEDBACK_BUFFER,0,captured);eq(gl.getError(),gl.NO_ERROR,'actual transform feedback');records.push({label:'original vertex actual clip-vector',hash,input,constants,expected,actual:Array.from(captured.slice(0,4)),varying:hasGeneric?Array.from(captured.slice(4,6)):null});eq(Array.from(captured.slice(0,4)),expected,'all four actual clip components '+hash);if(hasGeneric)eq(Array.from(captured.slice(4,6)),[.25,.75],'affine original varying xy');
   gl.bindTransformFeedback(gl.TRANSFORM_FEEDBACK,null);gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,null);
   gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(triangle.flat()),gl.STATIC_DRAW);if(extra){gl.bindBuffer(gl.ARRAY_BUFFER,extra);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([.25,.75,99,88,.25,.75,99,88,.25,.75,99,88]),gl.STATIC_DRAW);}
   gl.clearColor(0,0,0,1);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawArrays(gl.TRIANGLES,0,3);const actual=new Uint8Array(4096);gl.readPixels(0,0,32,32,gl.RGBA,gl.UNSIGNED_BYTE,actual);
   const clip=triangle.map(v=>hasGeneric?[...Array.from({length:3},(_,k)=>constants[0][k]*v[0]+constants[1][k]*v[1]+constants[2][k]),1]:Array.from({length:4},(_,k)=>constants.reduce((sum,c,i)=>sum+c[k]*v[i],0))),ndc=clip.map(v=>[v[0]/v[3],v[1]/v[3]]);let checks=0,inside=0;
   for(let y=0;y<32;y++)for(let x=0;x<32;x++){const pt=[(x+.5)/16-1,(y+.5)/16-1],dist=ndc.map((v,i)=>cross(v,ndc[(i+1)%3],pt));if(dist.some(d=>Math.abs(d)<.08))continue;const hit=dist.every(d=>d>0),expect=hit?[64,191,128,255]:[0,0,0,255];eq(Array.from(actual.subarray((y*32+x)*4,(y*32+x)*4+4)),expect,`nonidentity vertex actual pixel ${hash} ${x},${y}`);checks++;pixels++;if(hit)inside++;}check(inside>10,'nonidentity triangle visible');records.push({label:'original vertex nonidentity actual pixels',hash,clip,ndc,checked:checks,foreground:inside,readbackSha256:await digest(actual)});tile(hash.slice(0,8)+' nonidentity');
   for(const o of [b,extra,ub,tb])gl.deleteBuffer(o);gl.deleteTransformFeedback(tf);gl.deleteVertexArray(vao);gl.deleteProgram(p);
  }
  eq(gl.getError(),gl.NO_ERROR,'final GL errors');const cleanup=Object.fromEntries([...objects].map(([k,v])=>[k,v.size]));eq(Object.values(cleanup),Array(8).fill(0),'actual native GL cleanup');
  return {status:'passed',assertions,pixels,records,cleanup};
 }catch(error){return{status:'failed',assertions,pixels,records,error:{message:error.message,stack:error.stack},glError:gl?.getError()};}
}
