import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync}from'node:child_process';import {createHash}from'node:crypto';
import {runVirglBrowser,browserDocument}from'../../../tools/lib/virgl-browser-runner.mjs';import {plans,bankWords}from'./novel-hardware.mjs';
const output=path.resolve(process.argv[2]),sabotage=process.argv[3]==='sabotage',root=process.cwd(),base=path.relative(root,import.meta.dirname),nativeDir=path.join(output,'native'),nativeBase=path.relative(root,nativeDir),list=plans(),sha=bytes=>createHash('sha256').update(bytes).digest('hex'),word=value=>{const buffer=Buffer.alloc(4);buffer.writeUInt32LE(value);return buffer;},parts=[word(list.length)];
assert.ok(!nativeBase.startsWith('..')&&!path.isAbsolute(nativeBase),'browser inputs must be inside the repository');
await fs.mkdir(nativeDir,{recursive:true});
const literal=list.map(plan=>({name:plan.name,stage:plan.stage,form:plan.form,slot:plan.slot,offset:plan.offset,expectedArlBase:plan.base,expectedVector:plan.last,rawWords:[...bankWords(plan.count,plan.seed,plan.stage,plan.slot).slice(plan.last*4,plan.last*4+4)],shift:plan.shift,expectedBytes:[...bankWords(plan.count,plan.seed,plan.stage,plan.slot).slice(plan.last*4,plan.last*4+4)].map(value=>(value>>>plan.shift)&255)}));
await fs.writeFile(path.join(nativeDir,'novel-literal-predictions.json'),JSON.stringify({beforeNativeAndHardware:true,plans:literal},null,2)+'\n');
for(const plan of list){const vertex=Buffer.from(plan.vertexText),fragment=Buffer.from(plan.fragmentText);parts.push(word(2),...[plan.selectors.signedMask,plan.selectors.unsignedMask,plan.selectors.packedSignedMask,plan.selectors.packedNormalizedMask,plan.selectors.bufferZeroMask].map(word),word(vertex.length),vertex,word(fragment.length),fragment);}
await fs.writeFile(path.join(nativeDir,'novel-cases.bin'),Buffer.concat(parts));await fs.writeFile(path.join(nativeDir,'novel-cases.json'),JSON.stringify({cases:list},null,2)+'\n');
const executable=path.join(root,'renderer/virgl-shader/build/standard-uniform-native/standard-uniform-test'),binaryBefore=sha(await fs.readFile(executable));
const native=execFileSync(executable,[path.join(nativeDir,'novel-cases.bin')],{maxBuffer:16*1024*1024,env:{...process.env,LLVM_PROFILE_FILE:path.join(nativeDir,'novel-native.profraw')}});assert.equal(sha(await fs.readFile(executable)),binaryBefore);await fs.writeFile(path.join(nativeDir,'novel-native.jsonl'),native);
const files=[base+'/novel-hardware.mjs',nativeBase+'/novel-native.jsonl','renderer/virgl-command/constant-domain.mjs'],pinned=[];for(const file of files.slice(0,2)){const bytes=await fs.readFile(path.join(root,file));pinned.push({path:file,size:bytes.length,sha256:sha(bytes)});}
const report=await runVirglBrowser({options:{output},task:'E6-T11d16',boundary:'Fresh critic original signed16 endpoint reads of the LAST declared vectors',reportFields:{nativeExecutable:executable,nativeExecutableSha256:binaryBefore,literalPredictionsSha256:sha(await fs.readFile(path.join(nativeDir,'novel-literal-predictions.json')))},modulePath:'/'+base+'/novel-hardware.mjs',windowReportKey:'__uniformOffsetCriticReport',serializedAcceptance:true,browserArguments:{nativePath:'/'+nativeBase+'/novel-native.jsonl',sabotage},servedFiles:files,pinnedFiles:pinned,coveragePaths:['renderer/virgl-shader/standard.mjs',base+'/novel-hardware.mjs'],html:browserDocument({title:'Original signed endpoint critic',heading:'Original signed endpoint critic',description:'Signed16 endpoints · last declared vectors · original raw words · completed native fences'}),validate(acceptance){assert.equal(acceptance.frames.length,64);assert.ok(acceptance.frames.every(frame=>frame.gpuComplete.fenced&&frame.audit.held&&frame.cleaned));},successMessage:()=> '64 independent signed endpoint hardware attacks passed.'});
if(sabotage){assert.equal(report.status,'failed');const frame=report.acceptance.frames[0];assert.equal(frame.gpuComplete.fenced,true);assert.equal(frame.cleaned,true);assert.equal(frame.sabotageAfterFence,true);assert.equal(frame.audit.held,false);assert.match(report.failure.message,/critic original endpoint pixel assertion after completed native fence/);console.log('Independent endpoint oracle sabotage rejected after completed actual draw/fence.');process.exitCode=0;}else assert.equal(report.status,'passed');
