#!/usr/bin/env bash
# Like run.sh, but bind-mounts the repo at its REAL absolute path (not /work) and sets the
# workdir to the caller's cwd — so absolute-path commands generated by external tools (RISCOF's
# gcc/spike invocations) resolve identically inside the container (E1-T20).
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
. "${here}/versions.env"
repo_root="$(cd "${here}/../.." && pwd)"
[ "${1:-}" = "--" ] && shift
exec docker run --rm \
  --user "$(id -u):$(id -g)" \
  -v "${repo_root}:${repo_root}" \
  -w "$(pwd)" \
  -e HOME=/tmp \
  "${IMAGE_TAG}" \
  "$@"
