#!/usr/bin/env node

// E5-T12a: validate the checked-in W3C physical-code fixture and generate the browser/TypeScript
// table from one source of truth. Keep the generated module JavaScript-compatible so the current
// no-bundler web demo can import keymap.js while TypeScript consumers can import keymap.ts.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const inputDir = path.join(repoRoot, "web", "src", "input");
const fixturePath = path.join(inputDir, "w3c-pc105-codes.json");
const sourcePath = path.join(inputDir, "keymap-source.json");
const generatedPaths = [path.join(inputDir, "keymap.ts"), path.join(inputDir, "keymap.js")];

const fixture = JSON.parse(readFileSync(fixturePath, "utf8"));
const source = JSON.parse(readFileSync(sourcePath, "utf8"));
const codes = fixture.codes;
const entries = source.entries;

function fail(message) {
  throw new Error(`keymap generation: ${message}`);
}

if (fixture.schema !== "w3c-keyboard-code-pc105-v1") fail(`unexpected fixture schema ${fixture.schema}`);
if (source.schema !== "wasm-vm-evdev-keymap-v1") fail(`unexpected source schema ${source.schema}`);
if (!Array.isArray(codes) || codes.length === 0) fail("fixture must contain a non-empty codes array");
if (!Array.isArray(entries) || entries.length === 0) fail("source must contain a non-empty entries array");

const fixtureSeen = new Set();
for (const code of codes) {
  if (typeof code !== "string" || code.length === 0) fail(`invalid fixture code ${String(code)}`);
  if (fixtureSeen.has(code)) fail(`duplicate fixture code identity ${code}`);
  fixtureSeen.add(code);
}

const entrySeen = new Set();
const evdevSeen = new Map();
const edgeSeen = new Set();
const edges = {};
for (const entry of entries) {
  if (!entry || typeof entry.code !== "string" || entry.code.length === 0) {
    fail(`invalid source entry ${JSON.stringify(entry)}`);
  }
  if (entrySeen.has(entry.code)) fail(`duplicate code identity ${entry.code}`);
  entrySeen.add(entry.code);

  if (entry.evdev === null) {
    if (typeof entry.reason !== "string" || entry.reason.length === 0) {
      fail(`unmapped code ${entry.code} needs an explicit reason`);
    }
  } else if (!Number.isInteger(entry.evdev) || entry.evdev < 0 || entry.evdev > 0xffff) {
    fail(`invalid evdev code for ${entry.code}: ${String(entry.evdev)}`);
  } else {
    const previous = evdevSeen.get(entry.evdev);
    if (previous) fail(`duplicate evdev assignment ${entry.evdev}: ${previous} and ${entry.code}`);
    evdevSeen.set(entry.evdev, entry.code);
  }

  if (entry.edge !== undefined) {
    if (typeof entry.edge !== "string" || entry.edge.length === 0) {
      fail(`invalid edge name for ${entry.code}`);
    }
    if (edgeSeen.has(entry.edge)) fail(`duplicate edge name ${entry.edge}`);
    edgeSeen.add(entry.edge);
    edges[entry.edge] = entry.code;
  }
}

const missing = codes.filter((code) => !entrySeen.has(code));
if (missing.length) fail(`missing PC-105 code(s): ${missing.join(", ")}`);
const extra = entries.map((entry) => entry.code).filter((code) => !fixtureSeen.has(code));
if (extra.length) fail(`source code(s) absent from W3C fixture: ${extra.join(", ")}`);
if (entries.length !== codes.length) {
  fail(`fixture/source length mismatch: ${codes.length} codes vs ${entries.length} entries`);
}

const moduleText = `/* Generated by node tools/gen-keymap.mjs from keymap-source.json and w3c-pc105-codes.json. Do not edit. */

const sourceCodes = ${JSON.stringify(codes, null, 2)};
const sourceEntries = ${JSON.stringify(entries, null, 2)};
const sourceEdges = ${JSON.stringify(edges, null, 2)};

/** W3C KeyboardEvent.code values covered by the physical ISO PC-105 table. */
export const PC105_CODES = Object.freeze(sourceCodes);

/** Ordered source rows; evdev null is reserved for explicit, documented unmapped codes. */
export const KEYMAP_ENTRIES = Object.freeze(
  sourceEntries.map((entry) => Object.freeze({ ...entry })),
);

/** Stable named fixtures for edge identities used by the acceptance and adversarial tests. */
export const EDGE_CODES = Object.freeze(sourceEdges);
export const EDGE_EVDEV = Object.freeze(
  Object.fromEntries(
    Object.entries(EDGE_CODES).map(([name, code]) => [
      name,
      KEYMAP_ENTRIES.find((entry) => entry.code === code)?.evdev ?? null,
    ]),
  ),
);

/** Browser-facing lookup. An unmapped row returns null; an absent row is rejected by the oracle. */
export const KEYMAP = new Map(
  KEYMAP_ENTRIES.map((entry) => [entry.code, entry.evdev]),
);

export function evdevForCode(code) {
  return KEYMAP.has(code) ? KEYMAP.get(code) : null;
}

/**
 * Prove that the physical table is a total, one-row-per-identity mapping for the fixture.
 * The optional arguments intentionally make the oracle easy to attack in a scratch copy.
 */
export function assertPc105Coverage(entries = KEYMAP_ENTRIES, fixtureCodes = PC105_CODES) {
  if (!Array.isArray(entries)) throw new Error("keymap oracle: entries must be an array");
  if (!Array.isArray(fixtureCodes)) throw new Error("keymap oracle: fixture codes must be an array");

  const fixtureSet = new Set();
  for (const code of fixtureCodes) {
    if (fixtureSet.has(code)) throw new Error(\`duplicate fixture code identity: \${code}\`);
    fixtureSet.add(code);
  }

  const identitySet = new Set();
  const evdevOwners = new Map();
  for (const entry of entries) {
    if (!entry || typeof entry.code !== "string") {
      throw new Error(\`invalid keymap entry: \${JSON.stringify(entry)}\`);
    }
    if (identitySet.has(entry.code)) {
      throw new Error(\`duplicate code identity: \${entry.code}\`);
    }
    identitySet.add(entry.code);
    if (!fixtureSet.has(entry.code)) {
      throw new Error(\`source code absent from W3C fixture: \${entry.code}\`);
    }

    if (entry.evdev === null) {
      if (typeof entry.reason !== "string" || entry.reason.length === 0) {
        throw new Error(\`unmapped code lacks explicit reason: \${entry.code}\`);
      }
      continue;
    }
    if (!Number.isInteger(entry.evdev) || entry.evdev < 0 || entry.evdev > 0xffff) {
      throw new Error(\`invalid evdev code for \${entry.code}: \${String(entry.evdev)}\`);
    }
    const previous = evdevOwners.get(entry.evdev);
    if (previous) {
      throw new Error(
        \`duplicate evdev assignment: \${entry.evdev} (\${previous} and \${entry.code})\`,
      );
    }
    evdevOwners.set(entry.evdev, entry.code);
  }

  const missing = fixtureCodes.filter((code) => !identitySet.has(code));
  if (missing.length) throw new Error(\`missing PC-105 code(s): \${missing.join(", ")}\`);
  const extra = entries.map((entry) => entry.code).filter((code) => !fixtureSet.has(code));
  if (extra.length) throw new Error(\`unlisted physical code(s): \${extra.join(", ")}\`);
  return true;
}

assertPc105Coverage();
`;

const checkOnly = process.argv.includes("--check");
for (const outputPath of generatedPaths) {
  if (checkOnly) {
    const existing = readFileSync(outputPath, "utf8");
    if (existing !== moduleText) fail(`${path.relative(repoRoot, outputPath)} is stale; run node tools/gen-keymap.mjs`);
  } else {
    writeFileSync(outputPath, moduleText);
  }
}

if (!checkOnly) process.stdout.write(`generated ${generatedPaths.map((p) => path.relative(repoRoot, p)).join(" and ")}\n`);
