import {createVirglShaderBridge} from '/renderer/virgl-shader/index.mjs';
import {createResourceStore,createWebGL2TransferBackend} from '/renderer/virgl-command/resources.mjs';
import {createVirglDrawRenderer} from '/renderer/virgl-command/state.mjs';
const stable=x=>JSON.stringify(x,(_,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v);
const packet=(op,type,words)=>{const b=new Uint8Array(4+words.length*4),v=new DataView(b.buffer);v.setUint32(0,op+type*256+words.length*65536,true);words.forEach((w,i)=>v.setUint32(4+i*4,w,true));return b;};
const bits=x=>{const a=new Float32Array([x]);return new Uint32Array(a.buffer)[0];};
const shader=(id,stage,text)=>{const b=packet(1,4,[id,stage,text.length+1,256,0,...Array(Math.ceil((text.length+1)/4)).fill(0)]);b.set(new TextEncoder().encode(text),24);return b;};
const bind=(id,stage)=>packet(31,0,[id,stage]);
export async function run(sabotage=false){
 const report={status:'running',assertions:0,pixels:0,records:[],events:[]};
 const check=(v,m)=>{report.assertions++;if(!v)throw Error(m);};const eq=(a,b,m)=>check(stable(a)===stable(b),`${m}: expected ${stable(b)}, actual ${stable(a)}`);const ok=(v,m)=>{check(v.ok,m+': '+stable(v));return v;};
 const digest=async b=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',typeof b==='string'?new TextEncoder().encode(b):b))).map(n=>n.toString(16).padStart(2,'0')).join('');
 let gl;
 try {
 const bridge=await createVirglShaderBridge(),anchor=await(await fetch('/anchors.json')).json(),cases=await(await fetch('/browser-cases.json')).json();
 for(const c of cases){const actual=bridge.translatePair({vertexText:c.vertexText,fragmentText:c.fragmentText});if(c.native.ok)eq(actual,c.native,'native/Wasm '+c.name);else{eq(actual.ok,false,'rejected '+c.name);eq(actual.error.code,c.native.error.code,'native/Wasm error code '+c.name);}}
 report.records.push({name:'exact native/Wasm parity',cases:cases.length});
 let getterCalls=0;const pair={vertexText:anchor.vertexText,fragmentText:anchor.fragmentText},rev=Proxy.revocable({},{});rev.revoke();
 const unusual=[null,undefined,[],0,Object.create(pair),{...pair,shaderKey:{}},Object.defineProperty({...pair},'hidden',{value:1}),{...pair,[Symbol('key')]:1},Object.defineProperty({...pair},'vertexText',{get(){getterCalls++;return anchor.vertexText;}}),rev.proxy,new Proxy(pair,{ownKeys(){throw Error('reflect');}}),{vertexText:anchor.vertexText,fragmentText:7}];
 for(let i=0;i<unusual.length;i++){eq(bridge.translatePair(unusual[i]).ok,false,'strict own-data '+i);eq(bridge.translatePair(pair),anchor.pair,'strict request recovery '+i);}eq(getterCalls,0,'request accessors not invoked');let reentered=0;const reflecting=new Proxy({...pair},{ownKeys(target){eq(bridge.translatePair(pair),anchor.pair,'nested reflection pair remains exact');reentered++;return Reflect.ownKeys(target);}});eq(bridge.translatePair(reflecting),anchor.pair,'outer reflection pair remains exact');eq(reentered,1,'bounded reflective reentrancy');
 const retained=bridge.translatePair(pair),retainedText=stable(retained);for(let i=0;i<128;i++){bridge.translate({stage:'vertex',text:i%2?'bad':anchor.vertexText});bridge.translatePair(i%2?{...pair,fragmentText:'bad'}:pair);}eq(stable(retained),retainedText,'owned response survives buffer alternation');
 const canvas=document.querySelector('#gpu');canvas.width=canvas.height=16;gl=canvas.getContext('webgl2',{antialias:false,alpha:true,premultipliedAlpha:false,preserveDrawingBuffer:true});check(gl instanceof WebGL2RenderingContext,'actual WebGL2');const ext=gl.getExtension('WEBGL_debug_renderer_info');report.renderer=gl.getParameter(ext.UNMASKED_RENDERER_WEBGL);check(!/swiftshader|software|llvmpipe|mock/i.test(report.renderer),'actual hardware');
 gl.disable(gl.DITHER);gl.disable(gl.BLEND);gl.disable(gl.CULL_FACE);gl.disable(gl.DEPTH_TEST);
 const points=[[3,3],[6,3],[3,6]],smooth=[[128,64,64,255],[64,128,64,255],[64,64,128,255]];
 const probe=(bytes,mode,label)=>{for(let i=0;i<points.length;i++){const[x,y]=points[i],actual=Array.from(bytes.subarray((y*16+x)*4,(y*16+x)*4+4)),expected=mode==='flat'?[0,0,255,255]:smooth[i];report.records.push({name:label,point:[x,y],actual,expected});eq(actual,expected,'literal unequal-color '+label+' '+x+','+y);report.pixels++;}};
 const tile=(bytes,label)=>{const c=document.createElement('canvas');c.width=c.height=16;c.style.width='160px';c.style.imageRendering='pixelated';const v=new Uint8ClampedArray(1024);for(let y=0;y<16;y++)v.set(bytes.subarray(y*64,y*64+64),(15-y)*64);c.getContext('2d').putImageData(new ImageData(v,16,16),0,0);const f=document.createElement('figure'),s=document.createElement('figcaption');s.textContent=label;f.append(c,s);document.querySelector('#frames').append(f);};
 // The prewritten full-RGBA oracle first runs the original fragment and paired
 // vertex directly, then the renderer's vec2-only inputs reconstruct the same colors.
 const program=gl.createProgram(),v=gl.createShader(gl.VERTEX_SHADER),f=gl.createShader(gl.FRAGMENT_SHADER);for(const[s,source]of[[v,anchor.pair.vertex.glsl],[f,anchor.pair.fragment.glsl]]){gl.shaderSource(s,source);gl.compileShader(s);check(gl.getShaderParameter(s,gl.COMPILE_STATUS),'direct compile');gl.attachShader(program,s);}gl.linkProgram(program);check(gl.getProgramParameter(program,gl.LINK_STATUS),'direct original pair link');gl.useProgram(program);gl.viewport(0,0,16,16);const vao=gl.createVertexArray();gl.bindVertexArray(vao);const directBuffers=[];
 for(const[name,n,values]of[['in_0',4,[-.9375,-.9375,0,1,.5625,-.9375,0,1,-.9375,.5625,0,1]],['in_1',4,[1,0,0,1,0,1,0,1,0,0,1,1]]]){const b=gl.createBuffer();directBuffers.push(b);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(values),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,name);check(loc>=0,'direct attribute '+name);gl.vertexAttribPointer(loc,n,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(loc);}
 const bi=gl.getUniformBlockIndex(program,'VirglBlock'),ub=gl.createBuffer(),sys=new ArrayBuffer(656);new DataView(sys).setFloat32(640,1,true);gl.bindBuffer(gl.UNIFORM_BUFFER,ub);gl.bufferData(gl.UNIFORM_BUFFER,sys,gl.STATIC_DRAW);gl.bindBufferBase(gl.UNIFORM_BUFFER,0,ub);gl.uniformBlockBinding(program,bi,0);gl.clearColor(0,0,0,1);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawArrays(gl.TRIANGLES,0,3);const direct=new Uint8Array(1024);gl.readPixels(0,0,16,16,gl.RGBA,gl.UNSIGNED_BYTE,direct);probe(direct,'flat','unchanged original fragment direct');tile(direct,'Original flat: blue');for(const b of [...directBuffers,ub])gl.deleteBuffer(b);gl.deleteVertexArray(vao);gl.deleteShader(v);gl.deleteShader(f);gl.deleteProgram(program);gl.useProgram(null);
 const vertex=anchor.vertexText.replace('DCL IN[1]','DCL IN[1]\nDCL IN[2]').replace('MOV OUT[1], IN[1]','MOV OUT[1], IN[1]\nMOV OUT[1].z, IN[2].xxxx'),flat=anchor.fragmentText,sm=flat.replace('CONSTANT','PERSPECTIVE');ok(bridge.translatePair({vertexText:vertex,fragmentText:flat}),'three-attribute derived pair');
 // Unique native identities and actual destruction are independently observed.
 let serial=0,mode=null,armed=false,priorSmooth=null,requested=null,label='';const ids=new WeakMap(),live=new Map(),nativeObjects=[];const kinds={createShader:'Shader',createProgram:'Program',createBuffer:'Buffer',createTexture:'Texture',createVertexArray:'VertexArray',createFramebuffer:'Framebuffer',createRenderbuffer:'Renderbuffer',createSampler:'Sampler'};
 const ident=o=>o?ids.get(o):null;
 const proxy=new Proxy(gl,{get(t,k){const fn=Reflect.get(t,k,t);if(typeof fn!=='function')return fn;return(...args)=>{if(mode===k&&kinds[k])return null;if(mode==='compile'&&k==='getShaderParameter'&&args[1]===gl.COMPILE_STATUS)return false;if(mode==='link'&&k==='getProgramParameter'&&args[1]===gl.LINK_STATUS)return false;if(mode==='reflection'&&k==='getFragDataLocation')return 1;if(k==='useProgram'){requested=args[0];if(armed&&args[0])args[0]=priorSmooth;}const r=fn.apply(t,args);if(kinds[k]&&r){const id=++serial;ids.set(r,id);live.set(id,kinds[k]);nativeObjects.push({id,kind:kinds[k],object:r});}if(k.startsWith('delete')&&args[0])live.delete(ident(args[0]));if(k==='linkProgram'||k==='drawElements'||k==='useProgram'||k.startsWith('delete')||kinds[k])report.events.push({label,call:k,id:ident(args[0])??ident(r),current:k==='drawElements'?ident(t.getParameter(gl.CURRENT_PROGRAM)):undefined});return r;};}});
 const allocations=new Map(),backend=ok(createWebGL2TransferBackend(proxy),'backend').backend,tracked={maxTextureSize:backend.maxTextureSize,allocate(meta){const a=backend.allocate(meta);allocations.set(meta.id,a);return a;},destroy:a=>backend.destroy(a),upload:(...a)=>backend.upload(...a),readback:(...a)=>backend.readback(...a),dispose:()=>backend.dispose()};
 const{store,bindings}=ok(createResourceStore({backend:tracked}),'store');let pairCalls=0,retainedCompilerResult;
 const capability={translate:r=>bridge.translate(r),translatePair(r){pairCalls++;const original=bridge.translatePair(r);retainedCompilerResult=original;if(!original.ok)return original;const x=structuredClone(original);retainedCompilerResult=x;if(mode==='key')x.interfaceKey='evil';if(mode==='fs-source')x.fragment.glsl+='\n';if(mode==='vs-version')x.vertex.glsl=x.vertex.glsl.replace('300 es','100');if(mode==='vs-long')x.vertex.glsl+=' '.repeat(65537);if(mode==='vs-output')x.vertex.metadata.outputs.find(q=>q.semantic==='GENERIC').name='vso_g7';return x;}};
 const renderer=ok(createVirglDrawRenderer({gl:proxy,resources:store,bindings,shaderBridge:capability}),'renderer').renderer;const snapshot=()=>ok(renderer.inspect(),'inspect'),execute=(ctx,b,name)=>{label=name;return renderer.executeSubmission(ctx,b);},run=(ctx,b,name)=>ok(execute(ctx,b,name),name);
 const verts=new Uint8Array(new Float32Array([-.9375,-.9375,1,0,0,0,.5625,-.9375,0,1,0,0,-.9375,.5625,0,0,1,0]).buffer),indices=new Uint8Array(new Uint16Array([0,1,2]).buffer);
 for(const[id,target,format,bindFlag,width,height,data]of[[101,0,64,16,verts.length,1,verts],[102,0,64,32,indices.length,1,indices],[103,2,67,10,16,16,new Uint8Array(1024)]]){ok(store.createResource({id,target,format,bind:bindFlag,width,height,depth:1,arraySize:1,lastLevel:0,nrSamples:0,flags:0}),'resource');ok(store.attachBacking(id,[data]),'backing');}
 const setup=(ctx,create=true)=>{if(create){ok(store.createContext(ctx),'store context');ok(renderer.createContext(ctx),'renderer context');for(const r of[101,102,103])ok(store.attachContext(ctx,r),'attach');for(const[r,w]of[[101,verts.length],[102,indices.length]]){const p=ok(store.prepareTransfer(ctx,{opcode:43,fields:{resourceHandle:r,level:0,usage:0,stride:0,layerStride:0,box:{x:0,y:0,z:0,width:w,height:1,depth:1},dataOffset:0,direction:1}}),'transfer');ok(store.executeTransfer(p.ticket),'upload');}}
 for(const b of[shader(1,0,vertex),shader(2,1,flat),shader(3,1,sm),packet(1,8,[10,103,67,0,0]),packet(5,0,[1,0,10]),packet(1,5,[11,0,0,0,29,8,0,0,29,16,0,0,29]),packet(2,5,[11]),packet(6,0,[24,0,101]),packet(11,0,[102,2,0]),packet(4,0,[0,bits(8),bits(8),bits(.5),bits(8),bits(8),bits(.5)]),bind(1,0)])run(ctx,b,'setup');};
 const read=()=>{const fb=gl.createFramebuffer(),old=gl.getParameter(gl.READ_FRAMEBUFFER_BINDING);gl.bindFramebuffer(gl.READ_FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.READ_FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,allocations.get(103).texture,0);eq(gl.checkFramebufferStatus(gl.READ_FRAMEBUFFER),gl.FRAMEBUFFER_COMPLETE,'read FBO');const b=new Uint8Array(1024);gl.bindBuffer(gl.PIXEL_PACK_BUFFER,null);gl.readPixels(0,0,16,16,gl.RGBA,gl.UNSIGNED_BYTE,b);gl.bindFramebuffer(gl.READ_FRAMEBUFFER,old);gl.deleteFramebuffer(fb);return b;};
 const phase=async(ctx,kind,name)=>{run(ctx,bind(kind==='flat'?2:3,1),name+' bind');run(ctx,packet(7,0,[4,0,0,0,bits(1),0,0,0]),name+' clear');armed=sabotage&&kind==='flat';run(ctx,packet(8,0,[0,3,4,1,1,0,0,0,0,0,2,0]),name+' draw');armed=false;const p=gl.getParameter(gl.CURRENT_PROGRAM),b=read();if(kind==='smooth')priorSmooth=p;report.records.push({name,program:ident(p),requested:ident(requested),imageSha256:await digest(b),pairCalls,budgets:snapshot().budgets});probe(b,kind,name);tile(b,name);return p;};
 setup(1);const smoothProgram=await phase(1,'smooth','first smooth'),flatProgram=await phase(1,'flat','first flat');check(smoothProgram!==flatProgram,'different effective interfaces have different native programs');const warm=snapshot(),calls=pairCalls;
 retainedCompilerResult.vertex.glsl='external mutation';retainedCompilerResult.vertex.metadata.outputs.length=0;
 for(let i=0;i<8;i++){check((await phase(1,i%2?'flat':'smooth','warm '+i))===(i%2?flatProgram:smoothProgram),'reuse exact native identity');eq(snapshot().budgets,warm.budgets,'warm budgets bounded');}eq(pairCalls,calls,'warm links avoid repeated pair');
 // Independent failure attacks use fresh fragment generations; same public handle
 // never permits an old flat program to bypass validation.
 for(const fault of['key','fs-source','vs-version','vs-long','vs-output','createShader','compile','createProgram','link','createBuffer','reflection']){
  run(1,bind(3,1),'fault baseline smooth');run(1,packet(3,4,[2]),'destroy old flat');run(1,shader(2,1,flat),'fresh flat selector');const before=snapshot(),liveBefore=[...live].sort();mode=fault;const result=execute(1,bind(2,1),'fault '+fault);mode=null;eq(result.ok,false,'fault rejected '+fault);eq(snapshot(),before,'atomic publication '+fault);eq([...live].sort(),liveBefore,'allocation unwind '+fault);report.records.push({name:'controlled '+fault,error:result.error});await phase(1,'flat','recovery '+fault);
 }
 // Context/subcontext generations and identical numeric selector names remain separate.
 const context1Program=gl.getParameter(gl.CURRENT_PROGRAM);setup(2);const second=await phase(2,'flat','second context');check(second!==context1Program,'context programs isolated');run(2,packet(29,0,[7]),'new subcontext');setup(2,false);const sub=await phase(2,'flat','subcontext7');check(sub!==second,'subcontext native program distinct');run(2,packet(30,0,[7]),'destroy subcontext');await phase(2,'flat','default restored');ok(renderer.destroyContext(2),'destroy context2');ok(store.destroyContext(2),'destroy store context2');setup(2);const replaced=await phase(2,'flat','reused context2');check(replaced!==second,'context generation native program distinct');await phase(1,'smooth','context1 survives');
 const extraVertex=vertex.replace('DCL OUT[1]', 'DCL OUT[7], GENERIC[7]\nDCL OUT[1]').replace('END','MOV OUT[7], IN[1]\nEND');run(1,shader(20,0,extraVertex),'unused smooth vertex semantic');run(1,bind(20,0),'select extra varying vertex');await phase(1,'flat','unused varying remains smooth');
 run(1,bind(0,1),'unbind fragment');run(1,packet(3,4,[2]),'unbound selector destroy');run(1,packet(3,4,[3]),'smooth selector destroy');run(1,bind(0,0),'unbind vertex');run(1,packet(3,4,[1]),'vertex destroy');
 ok(store.dispose(),'store-first dispose');ok(renderer.dispose(),'renderer after store dispose');eq(Object.values(snapshot().budgets).every(x=>x===0),true,'all renderer budgets zero');eq(live.size,0,'all tracked GL objects deleted');for(const o of nativeObjects)eq(gl['is'+o.kind](o.object),false,'actual native collection '+o.id);eq(gl.getError(),gl.NO_ERROR,'zero hardware errors');report.cleanup={budgets:snapshot().budgets,nativeObjects:nativeObjects.length,live:live.size};report.status='passed';
 }catch(error){report.status='failed';report.error={message:error.message,stack:error.stack};report.glError=gl?.getError();}return report;
}
