#!/usr/bin/env python3
"""Generate byte-exact private 92cb identities from verified capture inputs."""
import hashlib
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
SHADERS = ROOT / "evidence/virgl-workload-inventory/captures/es2gears/shaders"
INPUTS = (
    ("vertex", SHADERS / "7bf4d0d0f981a9feb958d6595302b15d564fc846e6d5ee71874f0921b31e613e.tgsi",
     "7bf4d0d0f981a9feb958d6595302b15d564fc846e6d5ee71874f0921b31e613e"),
    ("fragment", SHADERS / "92cb866af48f952b719c54959a439c7330333c6d32897430bc3d4a0a2f63bfba.tgsi",
     "92cb866af48f952b719c54959a439c7330333c6d32897430bc3d4a0a2f63bfba"),
    ("geometry", ROOT / "target/evidence/virgl-92cb-raster/geometry.bin",
     "0d8bf78697b9be39a58c9274e221a89a9903f8587dfa2cf5cf5b754ae82e27ac"),
)
OUT = ROOT / "renderer/virgl-shader/private_92cb_inputs.h"


def quoted(data):
    lines = []
    for line in data.splitlines(keepends=True):
        escaped = line.decode("ascii").replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        lines.append(f'   "{escaped}"')
    return "\n".join(lines)


def generate():
    result = ["/* Generated by tools/virgl-92cb-power-domain/pin_private_inputs.py.",
              " * Byte-exact full capture identity; no numeric compiler fact is inferred here. */",
              "#ifndef WASM_VM_PRIVATE_92CB_INPUTS_H",
              "#define WASM_VM_PRIVATE_92CB_INPUTS_H"]
    for name, path, expected in INPUTS:
        data = path.read_bytes()
        assert hashlib.sha256(data).hexdigest() == expected, f"changed {name} capture"
        if name == "geometry":
            result.append(f"static const unsigned char private_92cb_{name}[] = {{")
            for at in range(0, len(data), 16):
                result.append("   " + ", ".join(f"0x{value:02x}" for value in data[at:at+16]) + ",")
            result.append("};")
        else:
            result.append(f"static const char private_92cb_{name}[] =\n{quoted(data)};")
    result.append("#endif")
    return ("\n".join(result) + "\n").encode("ascii")


if __name__ == "__main__":
    generated = generate()
    if sys.argv[1:] == ["--check"]:
        assert OUT.read_bytes() == generated, "private input pin is stale"
    elif len(sys.argv) == 1:
        OUT.write_bytes(generated)
    else:
        raise SystemExit("usage: pin_private_inputs.py [--check]")
