#!/usr/bin/env python3
"""Assemble a small, package-provenance-bound Omarchy root tree.

The source is treated as a read-only extracted or mounted root.  The
destination must already exist, contain only the exact staging marker, and is
populated only after every package mtree entry, source object, overlay, and
destination path has been validated.  The result is intended for a later
fresh mkfs; it is not a raw-disk privacy claim.
"""

from __future__ import annotations

import argparse
import base64
from dataclasses import dataclass
import gzip
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import shlex
import shutil
import stat
import subprocess
import sys
from typing import Iterable


STAGING_MARKER = ".wasm-vm-omarchy-staging"
STAGING_MARKER_CONTENT = b"wasm-vm-omarchy-staging-v1\n"
PROVENANCE_PATH = "etc/wasm-vm/omarchy-assembly.json"
PACKAGES_TSV_PATH = "etc/wasm-vm/packages.tsv"

MUTABLE_ETC_FILES = {
    "etc/passwd",
    "etc/group",
    "etc/shadow",
    "etc/gshadow",
    "etc/machine-id",
    "etc/hostname",
    "etc/hosts",
    "etc/resolv.conf",
    "etc/mtab",
    "etc/fstab",
    "etc/adjtime",
    "etc/subuid",
    "etc/subgid",
    "etc/ld.so.cache",
    # These are freshly generated by configure-omarchy-demo.py for this guest,
    # never inherited from the VM's locale/repository/shell policy.
    "etc/locale.gen",
    "etc/pacman.conf",
    "etc/pacman.d/mirrorlist",
    "etc/shells",
}
MUTABLE_ETC_PREFIXES = (
    "etc/pacman.d/gnupg",
    "etc/ssh/ssh_host_",
    "etc/systemd/system",
    "etc/systemd/network",
    "etc/NetworkManager/system-connections",
)

# No default exclusions: documentation, caches, boot files, and modules are
# package-owned inputs unless the caller explicitly selects this reviewed
# profile.  The profile name and prefixes are recorded in provenance.
PROFILE_EXCLUSIONS = {
    "default": (),
    "omit-docs-man-cache-boot-modules": (
        "usr/share/doc",
        "usr/share/man",
        "usr/share/info",
        "usr/share/cache",
        "usr/lib/modules",
        "boot",
    ),
}
ALLOWED_FILE_PREFIXES = ("usr", "opt", "etc")
ROOT_ALIAS_PATHS = {"bin", "sbin", "lib", "lib64"}
HOST_ONLY_XATTRS = {"com.apple.provenance"}
PACMAN_LOCAL_METADATA = {"ALPM_DB_VERSION"}
OMITTED_MTREE_PATHS = {".BUILDINFO", ".PKGINFO", ".INSTALL", ".MTREE"}


class AssemblyError(RuntimeError):
    """A fail-closed input, provenance, or output-boundary error."""


@dataclass(frozen=True)
class MtreeEntry:
    path: str
    kind: str
    mode: int | None
    uid: int | None
    gid: int | None
    sha256: str | None
    link: str | None
    package: str
    xattrs: tuple[tuple[str, bytes], ...] = ()


@dataclass(frozen=True)
class Package:
    name: str
    version: str
    directory: str
    entries: tuple[MtreeEntry, ...]
    depends: tuple[str, ...] = ()
    provides: tuple[str, ...] = ()


@dataclass(frozen=True)
class Overlay:
    path: str
    sha256: str
    xattrs: dict[str, bytes]


def _fail(message: str) -> None:
    # Messages are deliberately path-only for content/provenance failures.
    raise AssemblyError(message)


def _absolute(path: Path, label: str) -> Path:
    if not path.is_absolute():
        path = Path.cwd() / path
    path = Path(os.path.abspath(os.fspath(path)))
    for component in [path, *path.parents]:
        if component.is_symlink():
            _fail(f"{label} is a symlink")
    return path


def _within(path: PurePosixPath, prefix: str) -> bool:
    return path.as_posix() == prefix or path.as_posix().startswith(prefix + "/")


def _normal_guest_path(raw: str) -> str:
    if raw.startswith("/"):
        _fail("absolute package path")
    if raw.startswith("./"):
        raw = raw[2:]
    parts = PurePosixPath(raw).parts
    if not parts or any(part in ("", ".", "..") for part in parts):
        _fail("package path traversal")
    return "/".join(parts)


def _source_path(source: Path, relative: str) -> Path:
    path = source.joinpath(*PurePosixPath(relative).parts)
    if not _within(PurePosixPath(relative), relative):  # defensive, relative is normalized above
        _fail("source path traversal")
    return path


def _is_mutable_etc(relative: str) -> bool:
    return relative in MUTABLE_ETC_FILES or any(relative.startswith(prefix + "/") for prefix in MUTABLE_ETC_PREFIXES)


def _profile_excluded(relative: str, profile: str) -> bool:
    return any(_within(PurePosixPath(relative), prefix) for prefix in PROFILE_EXCLUSIONS[profile])


def _parse_int(value: str, base: int = 10) -> int:
    try:
        return int(value, base)
    except ValueError:
        _fail("invalid mtree metadata")


def _parse_mtree(path: Path, package: str) -> tuple[MtreeEntry, ...]:
    defaults: dict[str, str] = {}
    entries: list[MtreeEntry] = []
    try:
        stream = gzip.open(path, "rt", encoding="utf-8", errors="strict")
    except OSError:
        _fail("invalid package mtree")
    with stream:
        for raw_line in stream:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            # mtree uses octal escapes, not shell escapes. Preserve them until
            # tokenization is complete; literal placeholder-like names stay literal.
            lexer = shlex.shlex(line, posix=True)
            lexer.escape = ""
            lexer.whitespace_split = True
            lexer.commenters = ""
            try:
                tokens = list(lexer)
            except ValueError:
                _fail("invalid package mtree")
            if not tokens:
                continue
            directive = _decode_mtree_escapes(tokens[0])
            if directive == "/unset":
                for token in tokens[1:]:
                    defaults.pop(token.split("=", 1)[0], None)
                continue
            attrs = {}
            for token in tokens[1:]:
                if "=" not in token:
                    _fail("invalid package mtree")
                key, value = token.split("=", 1)
                attrs[key] = _decode_mtree_escapes(value)
            if directive == "/set":
                defaults.update(attrs)
                continue
            if directive in {".", "./"}:
                continue
            relative = _normal_guest_path(directive)
            if relative in OMITTED_MTREE_PATHS:
                continue
            merged = defaults | attrs
            kind = merged.get("type")
            if kind not in {"file", "link", "dir"}:
                _fail("unsupported package mtree type")
            mode = _parse_int(merged["mode"], 8) if "mode" in merged else None
            uid = _parse_int(merged["uid"]) if "uid" in merged else None
            gid = _parse_int(merged["gid"]) if "gid" in merged else None
            digest = merged.get("sha256digest", merged.get("sha256"))
            if digest is not None and (len(digest) != 64 or any(c not in "0123456789abcdef" for c in digest)):
                _fail("invalid package mtree digest")
            link = merged.get("link")
            entries.append(MtreeEntry(relative, kind, mode, uid, gid, digest, link, package))
    return tuple(entries)


def _decode_mtree_escapes(value: str) -> str:
    return re.sub(
        r"\\([0-7]{3})",
        lambda match: chr(int(match.group(1), 8)),
        value,
    )


def _desc_fields(path: Path) -> tuple[str, str, tuple[str, ...], tuple[str, ...]]:
    try:
        lines = path.read_text(encoding="utf-8", errors="strict").splitlines()
    except (OSError, UnicodeError):
        _fail("invalid package desc")
    fields: dict[str, list[str]] = {}
    current: str | None = None
    for line in lines:
        if line.startswith("%") and line.endswith("%"):
            current = line
        elif current and line and current in {"%NAME%", "%VERSION%", "%DEPENDS%", "%PROVIDES%"}:
            fields.setdefault(current, []).append(line)
    if not fields.get("%NAME%") or not fields.get("%VERSION%"):
        _fail("package desc missing name or version")
    depends = tuple(value for value in fields.get("%DEPENDS%", ()) if value not in {"", "None"})
    provides = tuple(value for value in fields.get("%PROVIDES%", ()) if value not in {"", "None"})
    return fields["%NAME%"][0], fields["%VERSION%"][0], depends, provides


def _load_packages(source: Path, profile_path: Path | None) -> tuple[tuple[Package, ...], dict[str, MtreeEntry], int | None]:
    if profile_path is None:
        _fail("package profile is required")
    try:
        profile = json.loads(profile_path.read_text(encoding="utf-8", errors="strict"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        _fail("invalid package profile")
    if not isinstance(profile, dict) or profile.get("schema", 1) != 1 or not isinstance(profile.get("packages"), list):
        _fail("invalid package profile")
    requested = profile["packages"]
    if not requested or any(not isinstance(name, str) or not name for name in requested) or len(set(requested)) != len(requested):
        _fail("invalid package profile")
    versions = profile.get("versions", {})
    if not isinstance(versions, dict) or any(not isinstance(key, str) or not isinstance(value, str) for key, value in versions.items()):
        _fail("invalid package profile")
    if any(name not in requested for name in versions):
        _fail("invalid package profile")
    installed_bytes = profile.get("installedBytes")
    if installed_bytes is not None and (isinstance(installed_bytes, bool) or not isinstance(installed_bytes, int) or installed_bytes < 0):
        _fail("invalid package profile")
    local = _source_path(source, "var/lib/pacman/local")
    if not local.is_dir() or local.is_symlink():
        _fail("missing pacman local database")
    summaries: dict[str, Package] = {}
    for directory in sorted(local.iterdir(), key=lambda item: item.name):
        if directory.name in PACMAN_LOCAL_METADATA:
            if directory.is_symlink() or not directory.is_file():
                _fail(directory.name)
            continue
        if directory.is_symlink() or not directory.is_dir():
            _fail("invalid pacman package directory")
        desc = directory / "desc"
        files = directory / "files"
        mtree = directory / "mtree"
        if any(not item.is_file() or item.is_symlink() for item in (desc, files, mtree)):
            _fail("incomplete pacman package metadata")
        name, version, depends, provides = _desc_fields(desc)
        summaries[name] = Package(name, version, directory.name, (), depends, provides)
    missing = [name for name in requested if name not in summaries]
    if missing:
        _fail("missing package: " + ",".join(sorted(missing)))
    selected_names = set(requested)

    def dependency_name(value: str) -> str:
        return re.split(r"[<>=: ]", value, maxsplit=1)[0]

    providers: dict[str, set[str]] = {}
    for package in summaries.values():
        for provided in (package.name, *package.provides):
            providers.setdefault(dependency_name(provided), set()).add(package.name)
    for name in sorted(selected_names):
        package = summaries[name]
        for dependency in package.depends:
            dep_name = dependency_name(dependency)
            candidates = providers.get(dep_name, set())
            if not candidates:
                _fail(f"missing dependency: {name}->{dep_name}")
            if not candidates & selected_names:
                _fail(f"dependency not selected: {name}->{dep_name}")

    all_packages: list[Package] = []
    for name in sorted(summaries):
        summary = summaries[name]
        package_dir = local / summary.directory
        mtree = package_dir / "mtree"
        if name in versions and versions[name] != summary.version:
            _fail(f"version mismatch: {name}")
        all_packages.append(Package(summary.name, summary.version, summary.directory, _parse_mtree(mtree, summary.name), summary.depends, summary.provides))
    packages = [package for package in all_packages if package.name in selected_names]
    if not packages:
        _fail("empty pacman local database")
    return tuple(packages), _package_index(tuple(all_packages)), installed_bytes


def _load_overlay(path: Path | None) -> dict[str, Overlay]:
    if path is None:
        return {}
    try:
        document = json.loads(path.read_text(encoding="utf-8", errors="strict"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        _fail("invalid overlay JSON")
    if not isinstance(document, dict) or document.get("schema") != 1 or not isinstance(document.get("entries"), list):
        _fail("invalid overlay JSON")
    result: dict[str, Overlay] = {}
    for item in document["entries"]:
        if not isinstance(item, dict) or not isinstance(item.get("path"), str) or not isinstance(item.get("sha256"), str):
            _fail("invalid overlay entry")
        raw = item["path"]
        if not raw.startswith("/"):
            _fail("overlay path must be absolute")
        relative = _normal_guest_path(raw[1:])
        digest = item["sha256"]
        if len(digest) != 64 or any(c not in "0123456789abcdef" for c in digest):
            _fail(relative)
        if not any(_within(PurePosixPath(relative), prefix) for prefix in ALLOWED_FILE_PREFIXES):
            _fail(relative)
        if relative in MUTABLE_ETC_FILES or _is_mutable_etc(relative):
            _fail(relative)
        xattrs: dict[str, bytes] = {}
        raw_xattrs = item.get("xattrs", {})
        if not isinstance(raw_xattrs, dict):
            _fail(relative)
        for name, encoded in raw_xattrs.items():
            if name != "security.capability" or not isinstance(encoded, str):
                _fail(relative)
            try:
                xattrs[name] = base64.b64decode(encoded, validate=True)
            except (ValueError, TypeError):
                _fail(relative)
        if relative in result and (result[relative].sha256 != digest or result[relative].xattrs != xattrs):
            _fail(relative)
        result[relative] = Overlay(relative, digest, xattrs)
    return result


def _lstat_kind(info: os.stat_result) -> str:
    if stat.S_ISREG(info.st_mode):
        return "file"
    if stat.S_ISLNK(info.st_mode):
        return "link"
    if stat.S_ISDIR(info.st_mode):
        return "dir"
    return "special"


def _hash_file(path: Path) -> str:
    digest = hashlib.sha256()
    flags = os.O_RDONLY
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    try:
        fd = os.open(path, flags)
    except OSError:
        _fail("unreadable package file")
    with os.fdopen(fd, "rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _link_hash(target: str) -> str:
    return hashlib.sha256(target.encode("utf-8", errors="surrogateescape")).hexdigest()


def _source_xattrs(path: Path, relative: str) -> dict[str, bytes]:
    if hasattr(os, "listxattr") and hasattr(os, "getxattr"):
        try:
            names = os.listxattr(path, follow_symlinks=False)
            values = {name: os.getxattr(path, name, follow_symlinks=False) for name in names}
        except OSError:
            _fail(relative)
    else:
        tool = Path("/usr/bin/xattr")
        if not tool.is_file():
            _fail(relative)
        try:
            listed = subprocess.run(
                [os.fspath(tool), "-l", "-s", os.fspath(path)],
                check=False,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
            )
            if listed.returncode != 0:
                _fail(relative)
            names = [line.split(b":", 1)[0].decode("utf-8", "strict") for line in listed.stdout.splitlines() if b":" in line]
            values = {}
            for name in names:
                result = subprocess.run(
                    [os.fspath(tool), "-p", "-x", "-s", name, os.fspath(path)],
                    check=False,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.DEVNULL,
                )
                if result.returncode != 0:
                    _fail(relative)
                values[name] = bytes.fromhex(b"".join(result.stdout.split()).decode("ascii"))
        except (OSError, UnicodeError, ValueError):
            _fail(relative)
    values = {name: value for name, value in values.items() if name not in HOST_ONLY_XATTRS}
    if any(name != "security.capability" for name in values):
        _fail(relative)
    return values


def _verify_xattrs(path: Path, relative: str, overlays: dict[str, Overlay]) -> dict[str, bytes]:
    actual = _source_xattrs(path, relative)
    expected = overlays.get(relative).xattrs if relative in overlays else {}
    if actual != expected:
        _fail(relative)
    return actual


def _safe_guest_link(relative: str, target: str) -> None:
    if target.startswith("/"):
        candidate = PurePosixPath(target.lstrip("/"))
    else:
        candidate = PurePosixPath(relative).parent / target
    normalized = PurePosixPath(os.path.normpath(candidate.as_posix()))
    if normalized == PurePosixPath(".") or any(part == ".." for part in normalized.parts):
        _fail(relative)


def _verify_entry(source: Path, entry: MtreeEntry, overlays: dict[str, Overlay]) -> tuple[str, str | None, dict[str, bytes], bool]:
    path = _source_path(source, entry.path)
    try:
        info = path.lstat()
    except OSError:
        _fail(entry.path)
    actual_kind = _lstat_kind(info)
    if actual_kind != entry.kind:
        _fail(entry.path)
    xattrs = _verify_xattrs(path, entry.path, overlays)
    metadata_mismatch = (
        entry.mode is not None and stat.S_IMODE(info.st_mode) != entry.mode
    ) or (entry.uid is not None and info.st_uid != entry.uid) or (entry.gid is not None and info.st_gid != entry.gid)
    if entry.kind == "dir":
        return actual_kind, None, xattrs, metadata_mismatch
    if entry.kind == "file":
        if entry.sha256 is None:
            _fail(entry.path)
        actual_digest = _hash_file(path)
    else:
        target = os.readlink(path)
        if entry.link is None:
            _fail(entry.path)
        actual_digest = _link_hash(target)
        _safe_guest_link(entry.path, target)
        if target == entry.link:
            return actual_kind, actual_digest, xattrs, metadata_mismatch
    if actual_digest != entry.sha256:
        overlay = overlays.get(entry.path)
        if overlay is None or overlay.sha256 != actual_digest:
            _fail(entry.path)
    return actual_kind, actual_digest, xattrs, metadata_mismatch


def _package_index(packages: tuple[Package, ...]) -> dict[str, MtreeEntry]:
    index: dict[str, MtreeEntry] = {}
    for package in packages:
        for entry in package.entries:
            previous = index.get(entry.path)
            if previous is None:
                index[entry.path] = entry
                continue
            if (previous.kind, previous.sha256, previous.link, previous.mode, previous.uid, previous.gid) != (
                entry.kind,
                entry.sha256,
                entry.link,
                entry.mode,
                entry.uid,
                entry.gid,
            ):
                _fail(entry.path)
    return index


def _walk_scope(source: Path, prefix: str) -> Iterable[tuple[str, os.stat_result]]:
    root = _source_path(source, prefix)
    if not root.exists():
        return
    if root.is_symlink() or not root.is_dir():
        _fail(prefix)
    for current, dirs, files in os.walk(root, topdown=True, followlinks=False):
        current_path = Path(current)
        dirs[:] = sorted(dirs)
        files[:] = sorted(files)
        for name in dirs + files:
            item = current_path / name
            relative = item.relative_to(source).as_posix()
            yield relative, item.lstat()


def _validate_source_and_plan(
    source: Path,
    packages: tuple[Package, ...],
    installed_index: dict[str, MtreeEntry],
    overlays: dict[str, Overlay],
    profile: str,
) -> tuple[dict[str, MtreeEntry], list[str], list[str], list[str]]:
    index = _package_index(packages)
    verified_xattrs: dict[str, dict[str, bytes]] = {}
    exclusions = list(PROFILE_EXCLUSIONS[profile])
    metadata_mismatches: list[str] = []
    excluded_paths: list[str] = []

    def admitted(entry: MtreeEntry) -> bool:
        return any(_within(PurePosixPath(entry.path), prefix) for prefix in ALLOWED_FILE_PREFIXES) or (
            entry.path in ROOT_ALIAS_PATHS and entry.kind == "link" and entry.package == "filesystem"
        )

    # Only selected package entries in the admitted output surface are
    # content-verified. Unselected packages remain ownership metadata used to
    # explain why their source files are omitted; they are never copied.
    for relative, entry in sorted(index.items()):
        if entry.kind not in {"file", "link", "dir"}:
            _fail(relative)
        if _profile_excluded(relative, profile) or _is_mutable_etc(relative) or not admitted(entry):
            excluded_paths.append(relative)
            continue
        _, _, xattrs, metadata_mismatch = _verify_entry(source, entry, overlays)
        verified_xattrs[entry.path] = xattrs
        if metadata_mismatch:
            metadata_mismatches.append(entry.path)

    for alias in sorted(ROOT_ALIAS_PATHS):
        alias_path = _source_path(source, alias)
        if not alias_path.exists() and not alias_path.is_symlink():
            continue
        alias_entry = index.get(alias)
        if not alias_path.is_symlink() or alias_entry is None or alias_entry.kind != "link" or alias_entry.package != "filesystem":
            _fail(alias)

    # Any regular/symlink file in the admitted scopes must be package-owned or
    # explicitly named and hashed by the reviewed overlay. Directories are
    # containers; special files are never admitted.
    for prefix in ALLOWED_FILE_PREFIXES:
        for relative, info in _walk_scope(source, prefix):
            if _profile_excluded(relative, profile) or _is_mutable_etc(relative):
                if _lstat_kind(info) != "dir":
                    excluded_paths.append(relative)
                continue
            kind = _lstat_kind(info)
            if kind == "dir":
                continue
            entry = installed_index.get(relative)
            if entry is not None:
                if relative not in index:
                    excluded_paths.append(relative)
                continue
            # Unowned files, personal /etc additions, and special files are
            # recorded as omitted. They are never copied and never become an
            # implicit overlay candidate.
            excluded_paths.append(relative)

    for relative, overlay in overlays.items():
        if relative not in index:
            _fail(relative)
        if relative not in {path for path, entry in index.items() if admitted(entry) and not _profile_excluded(path, profile) and not _is_mutable_etc(path)}:
            _fail(relative)

    plan: dict[str, MtreeEntry] = {}
    for relative, entry in sorted(index.items()):
        if _profile_excluded(relative, profile) or _is_mutable_etc(relative):
            continue
        if admitted(entry):
            plan[relative] = MtreeEntry(
                entry.path,
                entry.kind,
                entry.mode,
                entry.uid,
                entry.gid,
                entry.sha256,
                entry.link,
                entry.package,
                tuple(sorted(verified_xattrs.get(relative, {}).items())),
            )
    return plan, exclusions, metadata_mismatches, sorted(set(excluded_paths))


def _require_staging(staging: Path) -> None:
    if not staging.is_dir() or staging.is_symlink():
        _fail("staging is not a directory")
    children = list(staging.iterdir())
    marker = staging / STAGING_MARKER
    if len(children) != 1 or marker not in children or marker.is_symlink() or not marker.is_file() or marker.read_bytes() != STAGING_MARKER_CONTENT:
        _fail("staging is not a new marked directory")


def _ensure_parent(staging: Path, relative: str) -> Path:
    parent = staging.joinpath(*PurePosixPath(relative).parent.parts)
    current = staging
    for part in PurePosixPath(relative).parent.parts:
        current = current / part
        if current.exists() or current.is_symlink():
            if current.is_symlink() or not current.is_dir():
                _fail(relative)
        else:
            current.mkdir()
    return parent


def _apply_metadata(path: Path, mode: int | None, uid: int | None, gid: int | None, symlink: bool = False) -> None:
    if os.geteuid() == 0 and uid is not None and gid is not None:
        if symlink:
            os.lchown(path, uid, gid)
        else:
            os.chown(path, uid, gid)
    # On Linux chown clears setuid/setgid. Reapply mtree mode after ownership
    # so privileged assembly preserves the package's reviewed special bits.
    if mode is not None and not symlink:
        os.chmod(path, mode)


def _apply_xattrs(path: Path, relative: str, xattrs: dict[str, bytes], symlink: bool = False) -> None:
    if not xattrs:
        return
    if os.geteuid() != 0:
        _fail(relative)
    for name, value in xattrs.items():
        try:
            if hasattr(os, "setxattr"):
                os.setxattr(path, name, value, follow_symlinks=not symlink)
            else:
                tool = Path("/usr/bin/xattr")
                if not tool.is_file():
                    _fail(relative)
                command = [os.fspath(tool), "-w", "-x"]
                if symlink:
                    command.append("-s")
                command.extend((name, value.hex(), os.fspath(path)))
                result = subprocess.run(
                    command,
                    check=False,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                if result.returncode != 0:
                    _fail(relative)
        except OSError:
            _fail(relative)


def _write_plan(source: Path, staging: Path, plan: dict[str, MtreeEntry]) -> None:
    for relative, entry in plan.items():
        parent = PurePosixPath(relative).parent
        while parent != PurePosixPath("."):
            parent_entry = plan.get(parent.as_posix())
            if parent_entry is not None and parent_entry.kind == "link":
                _fail(relative)
            parent = parent.parent
    # Create package directories only as parents of admitted files. Every
    # parent is checked for symlink traversal before mkdir.
    for relative in sorted(plan, key=lambda item: (item.count("/"), item)):
        entry = plan[relative]
        parent = _ensure_parent(staging, relative)
        destination = staging / relative
        if entry.kind == "dir":
            if destination.is_symlink() or (destination.exists() and not destination.is_dir()):
                _fail(relative)
            if not destination.exists():
                destination.mkdir()
            _apply_metadata(destination, entry.mode, entry.uid, entry.gid)
            _apply_xattrs(destination, relative, dict(entry.xattrs))
        elif entry.kind == "file":
            if destination.exists() or destination.is_symlink():
                _fail(relative)
            shutil.copyfile(_source_path(source, relative), destination)
            _apply_metadata(destination, entry.mode, entry.uid, entry.gid)
            _apply_xattrs(destination, relative, dict(entry.xattrs))
        elif entry.kind == "link":
            if destination.exists() or destination.is_symlink():
                _fail(relative)
            target = os.readlink(_source_path(source, relative))
            _safe_guest_link(relative, target)
            os.symlink(target, destination)
            _apply_metadata(destination, entry.mode, entry.uid, entry.gid, symlink=True)
            _apply_xattrs(destination, relative, dict(entry.xattrs), symlink=True)
        else:
            _fail(relative)


def _write_pacman_metadata(source: Path, staging: Path, packages: tuple[Package, ...]) -> None:
    version_path = _source_path(source, "var/lib/pacman/local/ALPM_DB_VERSION")
    if version_path.is_symlink() or version_path.read_bytes() != b"9\n":
        _fail("unsupported pacman database version")
    _ensure_parent(staging, "var/lib/pacman/local/ALPM_DB_VERSION")
    (staging / "var/lib/pacman/local/ALPM_DB_VERSION").write_bytes(b"9\n")
    for package in packages:
        source_dir = _source_path(source, f"var/lib/pacman/local/{package.directory}")
        relative_dir = f"var/lib/pacman/local/{package.directory}"
        destination_dir = staging / relative_dir
        _ensure_parent(staging, relative_dir + "/desc")
        if destination_dir.is_symlink() or (destination_dir.exists() and not destination_dir.is_dir()):
            _fail(relative_dir)
        if not destination_dir.exists():
            destination_dir.mkdir()
        for filename in ("desc", "files", "mtree"):
            source_file = source_dir / filename
            destination_file = destination_dir / filename
            if destination_file.exists() or destination_file.is_symlink():
                _fail(f"{relative_dir}/{filename}")
            shutil.copyfile(source_file, destination_file)


def _write_metadata(staging: Path, packages: tuple[Package, ...], profile: str, overlays: dict[str, Overlay], plan: dict[str, MtreeEntry], exclusions: list[str], metadata_mismatches: list[str], excluded_paths: list[str], installed_bytes: int | None) -> None:
    metadata_dir = staging / "etc/wasm-vm"
    _ensure_parent(staging, PROVENANCE_PATH)
    metadata_dir.mkdir(exist_ok=True)
    provenance = {
        "schema": 1,
        "kind": "omarchy-package-assembly",
        "provenance_basis": "installed-pacman-mtree; not-upstream-authentication",
        "profile": profile,
        "exclusions": exclusions,
        "files": len(plan),
        "overlays": sorted(overlays),
        "metadata_mismatches": sorted(metadata_mismatches),
        # Omitted paths may themselves reveal personal filenames. Only a count
        # belongs in the distributable image; no source inventory is published.
        "excluded_path_count": len(excluded_paths),
        "installed_bytes": installed_bytes,
        "packages": [{"name": package.name, "version": package.version} for package in packages],
    }
    (staging / PROVENANCE_PATH).write_text(json.dumps(provenance, sort_keys=True, separators=(",", ":")) + "\n", encoding="utf-8")
    (staging / PACKAGES_TSV_PATH).write_text(
        "name\tversion\n" + "".join(f"{package.name}\t{package.version}\n" for package in packages), encoding="utf-8"
    )


def assemble(source_arg: str | os.PathLike[str], staging_arg: str | os.PathLike[str], overlay_arg: str | os.PathLike[str] | None = None, profile: str = "default", packages_arg: str | os.PathLike[str] | None = None) -> Path:
    if profile not in PROFILE_EXCLUSIONS:
        _fail("unknown profile")
    source = _absolute(Path(source_arg), "source")
    staging = _absolute(Path(staging_arg), "staging")
    if source == staging or source in staging.parents or staging in source.parents:
        _fail("source and staging must be separate")
    _require_staging(staging)
    overlay = _load_overlay(Path(overlay_arg) if overlay_arg is not None else None)
    packages, installed_index, installed_bytes = _load_packages(source, Path(packages_arg) if packages_arg is not None else None)
    plan, exclusions, metadata_mismatches, excluded_paths = _validate_source_and_plan(source, packages, installed_index, overlay, profile)
    _write_plan(source, staging, plan)
    _write_pacman_metadata(source, staging, packages)
    _write_metadata(staging, packages, profile, overlay, plan, exclusions, metadata_mismatches, excluded_paths, installed_bytes)
    (staging / ".wasm-vm-disposable-extracted-root").write_bytes(b"wasm-vm-disposable-extracted-root-v1\n")
    return staging


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", help="read-only extracted or mounted root")
    parser.add_argument("staging", help="new marked, initially-empty staging directory")
    parser.add_argument("--packages", required=True, help="reviewed JSON package-closure profile")
    parser.add_argument("--overlay", help="reviewed JSON path/sha256 allowlist")
    parser.add_argument("--profile", choices=tuple(PROFILE_EXCLUSIONS), default="default")
    args = parser.parse_args(argv)
    try:
        assemble(args.source, args.staging, args.overlay, args.profile, args.packages)
    except AssemblyError as exc:
        print(f"assemble-omarchy: refused: {exc}", file=sys.stderr)
        return 2
    except (OSError, ValueError) as exc:
        print(f"assemble-omarchy: failed safely: {type(exc).__name__}", file=sys.stderr)
        return 1
    print("assemble-omarchy: staging ready")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
